export { User } from "firebase/auth";
export declare const firebaseConfig: any;
export declare const app: import("@firebase/app").FirebaseApp;
export declare const auth: import("@firebase/auth").Auth;
export declare function getFirebaseMessage(): Promise<import("@firebase/messaging").Messaging>;
export declare function test1234(): Promise<string>;
export declare function testConsole(): Promise<void>;
export declare function getDeviceToken(): Promise<string>;
export declare function getToken(): Promise<string>;
export declare function isLoggedIn(): boolean;
export declare function getUser(): import("@firebase/auth").User | null;
export declare function signInWithGoogle(): Promise<import("@firebase/auth").User>;
export declare function signInWithEmailPassword(email: string, password: string): Promise<import("@firebase/auth").User>;
export declare function signUpWithEmailPassword(email: string, password: string): Promise<import("@firebase/auth").User>;
export declare function sendEmailVerification(): Promise<void>;
export declare function sendEmailPasswordReset(email: string): Promise<void>;
export declare function signOut(): Promise<void>;
