export declare enum _36_Enums_AsyncTaskType {
    EXPORT_PRODUCT_REQUEST = "EXPORT_PRODUCT_REQUEST",
    EXPORT_PAYOUT_REQUEST = "EXPORT_PAYOUT_REQUEST",
    EXPORT_ORDER = "EXPORT_ORDER",
    EXPORT_ACCOUNTANCY = "EXPORT_ACCOUNTANCY",
    EXPORT_STORE_REPORT = "EXPORT_STORE_REPORT",
    GENERATE_PNG = "GENERATE_PNG",
    SEND_MAIL = "SEND_MAIL",
    UPDATE_FULFILLMENT_COST = "UPDATE_FULFILLMENT_COST"
}
