import type { FulfillmentStatus } from './FulfillmentStatus';
import type { PaymentType } from './PaymentType';
export type ExportOrderResponseDto = {
    OrderId: string;
    ItemCode: string;
    SKU: string;
    VariantName: string;
    Domain: string;
    Quantity: number;
    SupplierCost: number;
    ItemStatus: FulfillmentStatus;
    LastUpdatedAt: string;
    PaidAt: string;
    LastUpdatedDateAt: string;
    PaidDateAt: string;
    LastUpdatedTimeAt: string;
    PaidTimeAt: string;
    FulfilledAt?: string;
    TrackingNumber?: string;
    Carrier?: string;
    UnitPrice: number;
    ShippingFee: number;
    TotalPrice: number;
    BuyerName: string;
    BuyerEmail: string;
    BuyerAddress1: string;
    BuyerAddress2?: string;
    BuyerPhone?: string;
    BuyerCity: string;
    BuyerProvince: string;
    BuyerCountry: string;
    BuyerZip: string;
    BuyerCountryCode: string;
    BuyerProvinceCode?: string;
    SellerEmail: string;
    PaymentGatewayId: string;
    PaymentGatewayName: string;
    GatewayType: PaymentType;
    TransactionId?: string;
};
