export declare enum FulfillmentStatus {
    UNFULFILLED = "UNFULFILLED",
    PARTIALLY_FULFILLED = "PARTIALLY_FULFILLED",
    FULFILLED = "FULFILLED",
    PARTIALLY_PROCESSING = "PARTIALLY_PROCESSING",
    PROCESSING = "PROCESSING"
}
