/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum Permission {
  SUPER_ADMIN_VIEW_PLATFORM_PERFORMANCE = 'SUPER_ADMIN_VIEW_PLATFORM_PERFORMANCE',
  SUPER_ADMIN_VIEW_MARKETING_PERFORMANCE = 'SUPER_ADMIN_VIEW_MARKETING_PERFORMANCE',
  SUPER_ADMIN_VIEW_AGENCY = 'SUPER_ADMIN_VIEW_AGENCY',
  SUPER_ADMIN_ADD_AGENCY = 'SUPER_ADMIN_ADD_AGENCY',
  SUPER_ADMIN_REVENUE_CEILING = 'SUPER_ADMIN_REVENUE_CEILING',
  SUPER_ADMIN_VIEW_REFERRAL_OVERVIEW = 'SUPER_ADMIN_VIEW_REFERRAL_OVERVIEW',
  SUPER_ADMIN_VIEW_REFERRAL_SALES = 'SUPER_ADMIN_VIEW_REFERRAL_SALES',
  SUPER_ADMIN_VIEW_STORE_IN_REFERRAL = 'SUPER_ADMIN_VIEW_STORE_IN_REFERRAL',
  SUPER_ADMIN_ADD_REFERRAL_CODE = 'SUPER_ADMIN_ADD_REFERRAL_CODE',
}
