/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum SellerPermission {
  SELLER_REQUEST_PRODUCT = 'SELLER_REQUEST_PRODUCT',
  SELLER_EDIT_PRODUCT = 'SELLER_EDIT_PRODUCT',
  SELLER_DUPLICATE_PRODUCT = 'SELLER_DUPLICATE_PRODUCT',
  SELLER_CREATE_AND_DUPLICATE_PRODUCT = 'SELLER_CREATE_AND_DUPLICATE_PRODUCT',
  SELLER_DELETE_PRODUCT = 'SELLER_DELETE_PRODUCT',
  SELLER_VIEW_STORE_PERFORMANCE = 'SELLER_VIEW_STORE_PERFORMANCE',
  SELLER_VIEW_LIVE_VIEW = 'SELLER_VIEW_LIVE_VIEW',
  SELLER_EDIT_THEME = 'SELLER_EDIT_THEME',
  SELLER_EDIT_DOMAIN = 'SELLER_EDIT_DOMAIN',
  SELLER_VIEW_TRAFFIC_SOURCES = 'SELLER_VIEW_TRAFFIC_SOURCES',
  SELLER_VIEW_PRODUCT_PERFORMANCE = 'SELLER_VIEW_PRODUCT_PERFORMANCE',
  SELLER_TRACK_ORDER_STATUS = 'SELLER_TRACK_ORDER_STATUS',
  SELLER_MANAGE_ABANDONED_CHECKOUT = 'SELLER_MANAGE_ABANDONED_CHECKOUT',
  SELLER_REFUND_ORDER = 'SELLER_REFUND_ORDER',
  SELLER_MANAGE_CROSS_SELLING = 'SELLER_MANAGE_CROSS_SELLING',
  SELLER_MANAGE_UP_SELLING = 'SELLER_MANAGE_UP_SELLING',
  SELLER_MANAGE_EMAIL_MARKETING = 'SELLER_MANAGE_EMAIL_MARKETING',
  SELLER_REQUEST_PAYOUT = 'SELLER_REQUEST_PAYOUT',
  SELLER_VIEW_TRANSACTION = 'SELLER_VIEW_TRANSACTION',
  SELLER_SETUP_PAYMENT_METHODS = 'SELLER_SETUP_PAYMENT_METHODS',
  SELLER_MANAGE_PAYMENT_PROVIDERS = 'SELLER_MANAGE_PAYMENT_PROVIDERS',
  SELLER_MANAGE_PAYMENT_CARDS = 'SELLER_MANAGE_PAYMENT_CARDS',
  SELLER_MANAGE_STORE_SETTINGS = 'SELLER_MANAGE_STORE_SETTINGS',
  SELLER_MANAGE_SHIPPING = 'SELLER_MANAGE_SHIPPING',
  SELLER_MANAGE_CURRENCY = 'SELLER_MANAGE_CURRENCY',
  SELLER_MANAGE_POLICIES = 'SELLER_MANAGE_POLICIES',
  SELLER_MANAGE_ANALYTICS_TOOLS = 'SELLER_MANAGE_ANALYTICS_TOOLS',
}
