/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum SuperAdminPermission {
  SUPER_ADMIN_VIEW_ACCOUNT_IN_PERMISSION = 'SUPER_ADMIN_VIEW_ACCOUNT_IN_PERMISSION',
  SUPER_ADMIN_ADD_ACCOUNT_IN_PERMISSION = 'SUPER_ADMIN_ADD_ACCOUNT_IN_PERMISSION',
  SUPER_ADMIN_EDIT_ACCOUNT_IN_PERMISSION = 'SUPER_ADMIN_EDIT_ACCOUNT_IN_PERMISSION',
  SUPER_ADMIN_VIEW_ROLE = 'SUPER_ADMIN_VIEW_ROLE',
  SUPER_ADMIN_ADD_ROLE = 'SUPER_ADMIN_ADD_ROLE',
  SUPER_ADMIN_EDIT_ROLE = 'SUPER_ADMIN_EDIT_ROLE',
  SUPER_ADMIN_DELETE_ROLE = 'SUPER_ADMIN_DELETE_ROLE',
}
