import type { BaseHttpRequest } from './core/BaseHttpRequest';
import type { OpenAPIConfig } from './core/OpenAPI';
import { AuthService } from './services/AuthService';
import { CollectionService } from './services/CollectionService';
import { CurrencyService } from './services/CurrencyService';
import { DomainService } from './services/DomainService';
import { FbPixelService } from './services/FbPixelService';
import { OrderService } from './services/OrderService';
import { ProductService } from './services/ProductService';
import { RequestSourcingService } from './services/RequestSourcingService';
import { ReviewService } from './services/ReviewService';
import { SettingService } from './services/SettingService';
import { StaffService } from './services/StaffService';
import { StoreService } from './services/StoreService';
import { StoreTagService } from './services/StoreTagService';
import { ThemeService } from './services/ThemeService';
import { TransactionService } from './services/TransactionService';
import { UploadService } from './services/UploadService';
import { UserService } from './services/UserService';
import { VariantService } from './services/VariantService';
type HttpRequestConstructor = new (config: OpenAPIConfig) => BaseHttpRequest;
export declare class ClientApi {
    readonly auth: AuthService;
    readonly collection: CollectionService;
    readonly currency: CurrencyService;
    readonly domain: DomainService;
    readonly fbPixel: FbPixelService;
    readonly order: OrderService;
    readonly product: ProductService;
    readonly requestSourcing: RequestSourcingService;
    readonly review: ReviewService;
    readonly setting: SettingService;
    readonly staff: StaffService;
    readonly store: StoreService;
    readonly storeTag: StoreTagService;
    readonly theme: ThemeService;
    readonly transaction: TransactionService;
    readonly upload: UploadService;
    readonly user: UserService;
    readonly variant: VariantService;
    readonly request: BaseHttpRequest;
    constructor(config?: Partial<OpenAPIConfig>, HttpRequest?: HttpRequestConstructor);
}
export {};
