"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PerformanceService = exports.PaymentService = exports.OrderRefundsService = exports.OrderService = exports.NotificationService = exports.GoogleAnalyticService = exports.FulfillmentAgencyService = exports.FbPixelService = exports.DomainService = exports.CurrencyService = exports.CollectionService = exports.CampaignService = exports.BankAccountService = exports.AuthService = exports.AsyncTaskService = exports.UserRole = exports.typeFulfillmentPrice = exports.TransactionType = exports.TransactionStatus = exports.TimezoneDto = exports.SyncTrackingStatus = exports.StoreType = exports.StoreStatus = exports.StoreRole = exports.statusRequestPayout = exports.RequestSourcingStatus = exports.RequestPayoutStatus = exports.RefundType = exports.Period = exports.PaymentType = exports.PaymentMethodType = exports.OrderStatus = exports.OrderDisputeStatus = exports.NotificationType = exports.LogoSize = exports.FulfillmentStatus = exports.FulfillmentAgencyStatus = exports.FulfillmentAgencyRole = exports.CustomDomainStatus = exports.CurrencyType = exports.CurrencyCode = exports.CostCalculationMethod = exports.AsyncTaskType = exports.AsyncTaskStatus = exports.OpenAPI = exports.CancelError = exports.CancelablePromise = exports.BaseHttpRequest = exports.ApiError = exports.ClientApi = void 0;
exports.WalletService = exports.VariantComboService = exports.VariantService = exports.UserService = exports.UploadService = exports.TransactionService = exports.TiktokPixelService = exports.ThemeLibraryService = exports.ThemeService = exports.StoreTagService = exports.StoreService = exports.StaffService = exports.SettingService = exports.ReviewService = exports.RequestSourcingService = exports.RequestPayoutService = exports.ProductService = exports.PingPongAccountService = void 0;
/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
var ClientApi_1 = require("./ClientApi");
Object.defineProperty(exports, "ClientApi", { enumerable: true, get: function () { return ClientApi_1.ClientApi; } });
var ApiError_1 = require("./core/ApiError");
Object.defineProperty(exports, "ApiError", { enumerable: true, get: function () { return ApiError_1.ApiError; } });
var BaseHttpRequest_1 = require("./core/BaseHttpRequest");
Object.defineProperty(exports, "BaseHttpRequest", { enumerable: true, get: function () { return BaseHttpRequest_1.BaseHttpRequest; } });
var CancelablePromise_1 = require("./core/CancelablePromise");
Object.defineProperty(exports, "CancelablePromise", { enumerable: true, get: function () { return CancelablePromise_1.CancelablePromise; } });
Object.defineProperty(exports, "CancelError", { enumerable: true, get: function () { return CancelablePromise_1.CancelError; } });
var OpenAPI_1 = require("./core/OpenAPI");
Object.defineProperty(exports, "OpenAPI", { enumerable: true, get: function () { return OpenAPI_1.OpenAPI; } });
var AsyncTaskStatus_1 = require("./models/AsyncTaskStatus");
Object.defineProperty(exports, "AsyncTaskStatus", { enumerable: true, get: function () { return AsyncTaskStatus_1.AsyncTaskStatus; } });
var AsyncTaskType_1 = require("./models/AsyncTaskType");
Object.defineProperty(exports, "AsyncTaskType", { enumerable: true, get: function () { return AsyncTaskType_1.AsyncTaskType; } });
var CostCalculationMethod_1 = require("./models/CostCalculationMethod");
Object.defineProperty(exports, "CostCalculationMethod", { enumerable: true, get: function () { return CostCalculationMethod_1.CostCalculationMethod; } });
var CurrencyCode_1 = require("./models/CurrencyCode");
Object.defineProperty(exports, "CurrencyCode", { enumerable: true, get: function () { return CurrencyCode_1.CurrencyCode; } });
var CurrencyType_1 = require("./models/CurrencyType");
Object.defineProperty(exports, "CurrencyType", { enumerable: true, get: function () { return CurrencyType_1.CurrencyType; } });
var CustomDomainStatus_1 = require("./models/CustomDomainStatus");
Object.defineProperty(exports, "CustomDomainStatus", { enumerable: true, get: function () { return CustomDomainStatus_1.CustomDomainStatus; } });
var FulfillmentAgencyRole_1 = require("./models/FulfillmentAgencyRole");
Object.defineProperty(exports, "FulfillmentAgencyRole", { enumerable: true, get: function () { return FulfillmentAgencyRole_1.FulfillmentAgencyRole; } });
var FulfillmentAgencyStatus_1 = require("./models/FulfillmentAgencyStatus");
Object.defineProperty(exports, "FulfillmentAgencyStatus", { enumerable: true, get: function () { return FulfillmentAgencyStatus_1.FulfillmentAgencyStatus; } });
var FulfillmentStatus_1 = require("./models/FulfillmentStatus");
Object.defineProperty(exports, "FulfillmentStatus", { enumerable: true, get: function () { return FulfillmentStatus_1.FulfillmentStatus; } });
var LogoSize_1 = require("./models/LogoSize");
Object.defineProperty(exports, "LogoSize", { enumerable: true, get: function () { return LogoSize_1.LogoSize; } });
var NotificationType_1 = require("./models/NotificationType");
Object.defineProperty(exports, "NotificationType", { enumerable: true, get: function () { return NotificationType_1.NotificationType; } });
var OrderDisputeStatus_1 = require("./models/OrderDisputeStatus");
Object.defineProperty(exports, "OrderDisputeStatus", { enumerable: true, get: function () { return OrderDisputeStatus_1.OrderDisputeStatus; } });
var OrderStatus_1 = require("./models/OrderStatus");
Object.defineProperty(exports, "OrderStatus", { enumerable: true, get: function () { return OrderStatus_1.OrderStatus; } });
var PaymentMethodType_1 = require("./models/PaymentMethodType");
Object.defineProperty(exports, "PaymentMethodType", { enumerable: true, get: function () { return PaymentMethodType_1.PaymentMethodType; } });
var PaymentType_1 = require("./models/PaymentType");
Object.defineProperty(exports, "PaymentType", { enumerable: true, get: function () { return PaymentType_1.PaymentType; } });
var Period_1 = require("./models/Period");
Object.defineProperty(exports, "Period", { enumerable: true, get: function () { return Period_1.Period; } });
var RefundType_1 = require("./models/RefundType");
Object.defineProperty(exports, "RefundType", { enumerable: true, get: function () { return RefundType_1.RefundType; } });
var RequestPayoutStatus_1 = require("./models/RequestPayoutStatus");
Object.defineProperty(exports, "RequestPayoutStatus", { enumerable: true, get: function () { return RequestPayoutStatus_1.RequestPayoutStatus; } });
var RequestSourcingStatus_1 = require("./models/RequestSourcingStatus");
Object.defineProperty(exports, "RequestSourcingStatus", { enumerable: true, get: function () { return RequestSourcingStatus_1.RequestSourcingStatus; } });
var statusRequestPayout_1 = require("./models/statusRequestPayout");
Object.defineProperty(exports, "statusRequestPayout", { enumerable: true, get: function () { return statusRequestPayout_1.statusRequestPayout; } });
var StoreRole_1 = require("./models/StoreRole");
Object.defineProperty(exports, "StoreRole", { enumerable: true, get: function () { return StoreRole_1.StoreRole; } });
var StoreStatus_1 = require("./models/StoreStatus");
Object.defineProperty(exports, "StoreStatus", { enumerable: true, get: function () { return StoreStatus_1.StoreStatus; } });
var StoreType_1 = require("./models/StoreType");
Object.defineProperty(exports, "StoreType", { enumerable: true, get: function () { return StoreType_1.StoreType; } });
var SyncTrackingStatus_1 = require("./models/SyncTrackingStatus");
Object.defineProperty(exports, "SyncTrackingStatus", { enumerable: true, get: function () { return SyncTrackingStatus_1.SyncTrackingStatus; } });
var TimezoneDto_1 = require("./models/TimezoneDto");
Object.defineProperty(exports, "TimezoneDto", { enumerable: true, get: function () { return TimezoneDto_1.TimezoneDto; } });
var TransactionStatus_1 = require("./models/TransactionStatus");
Object.defineProperty(exports, "TransactionStatus", { enumerable: true, get: function () { return TransactionStatus_1.TransactionStatus; } });
var TransactionType_1 = require("./models/TransactionType");
Object.defineProperty(exports, "TransactionType", { enumerable: true, get: function () { return TransactionType_1.TransactionType; } });
var typeFulfillmentPrice_1 = require("./models/typeFulfillmentPrice");
Object.defineProperty(exports, "typeFulfillmentPrice", { enumerable: true, get: function () { return typeFulfillmentPrice_1.typeFulfillmentPrice; } });
var UserRole_1 = require("./models/UserRole");
Object.defineProperty(exports, "UserRole", { enumerable: true, get: function () { return UserRole_1.UserRole; } });
var AsyncTaskService_1 = require("./services/AsyncTaskService");
Object.defineProperty(exports, "AsyncTaskService", { enumerable: true, get: function () { return AsyncTaskService_1.AsyncTaskService; } });
var AuthService_1 = require("./services/AuthService");
Object.defineProperty(exports, "AuthService", { enumerable: true, get: function () { return AuthService_1.AuthService; } });
var BankAccountService_1 = require("./services/BankAccountService");
Object.defineProperty(exports, "BankAccountService", { enumerable: true, get: function () { return BankAccountService_1.BankAccountService; } });
var CampaignService_1 = require("./services/CampaignService");
Object.defineProperty(exports, "CampaignService", { enumerable: true, get: function () { return CampaignService_1.CampaignService; } });
var CollectionService_1 = require("./services/CollectionService");
Object.defineProperty(exports, "CollectionService", { enumerable: true, get: function () { return CollectionService_1.CollectionService; } });
var CurrencyService_1 = require("./services/CurrencyService");
Object.defineProperty(exports, "CurrencyService", { enumerable: true, get: function () { return CurrencyService_1.CurrencyService; } });
var DomainService_1 = require("./services/DomainService");
Object.defineProperty(exports, "DomainService", { enumerable: true, get: function () { return DomainService_1.DomainService; } });
var FbPixelService_1 = require("./services/FbPixelService");
Object.defineProperty(exports, "FbPixelService", { enumerable: true, get: function () { return FbPixelService_1.FbPixelService; } });
var FulfillmentAgencyService_1 = require("./services/FulfillmentAgencyService");
Object.defineProperty(exports, "FulfillmentAgencyService", { enumerable: true, get: function () { return FulfillmentAgencyService_1.FulfillmentAgencyService; } });
var GoogleAnalyticService_1 = require("./services/GoogleAnalyticService");
Object.defineProperty(exports, "GoogleAnalyticService", { enumerable: true, get: function () { return GoogleAnalyticService_1.GoogleAnalyticService; } });
var NotificationService_1 = require("./services/NotificationService");
Object.defineProperty(exports, "NotificationService", { enumerable: true, get: function () { return NotificationService_1.NotificationService; } });
var OrderService_1 = require("./services/OrderService");
Object.defineProperty(exports, "OrderService", { enumerable: true, get: function () { return OrderService_1.OrderService; } });
var OrderRefundsService_1 = require("./services/OrderRefundsService");
Object.defineProperty(exports, "OrderRefundsService", { enumerable: true, get: function () { return OrderRefundsService_1.OrderRefundsService; } });
var PaymentService_1 = require("./services/PaymentService");
Object.defineProperty(exports, "PaymentService", { enumerable: true, get: function () { return PaymentService_1.PaymentService; } });
var PerformanceService_1 = require("./services/PerformanceService");
Object.defineProperty(exports, "PerformanceService", { enumerable: true, get: function () { return PerformanceService_1.PerformanceService; } });
var PingPongAccountService_1 = require("./services/PingPongAccountService");
Object.defineProperty(exports, "PingPongAccountService", { enumerable: true, get: function () { return PingPongAccountService_1.PingPongAccountService; } });
var ProductService_1 = require("./services/ProductService");
Object.defineProperty(exports, "ProductService", { enumerable: true, get: function () { return ProductService_1.ProductService; } });
var RequestPayoutService_1 = require("./services/RequestPayoutService");
Object.defineProperty(exports, "RequestPayoutService", { enumerable: true, get: function () { return RequestPayoutService_1.RequestPayoutService; } });
var RequestSourcingService_1 = require("./services/RequestSourcingService");
Object.defineProperty(exports, "RequestSourcingService", { enumerable: true, get: function () { return RequestSourcingService_1.RequestSourcingService; } });
var ReviewService_1 = require("./services/ReviewService");
Object.defineProperty(exports, "ReviewService", { enumerable: true, get: function () { return ReviewService_1.ReviewService; } });
var SettingService_1 = require("./services/SettingService");
Object.defineProperty(exports, "SettingService", { enumerable: true, get: function () { return SettingService_1.SettingService; } });
var StaffService_1 = require("./services/StaffService");
Object.defineProperty(exports, "StaffService", { enumerable: true, get: function () { return StaffService_1.StaffService; } });
var StoreService_1 = require("./services/StoreService");
Object.defineProperty(exports, "StoreService", { enumerable: true, get: function () { return StoreService_1.StoreService; } });
var StoreTagService_1 = require("./services/StoreTagService");
Object.defineProperty(exports, "StoreTagService", { enumerable: true, get: function () { return StoreTagService_1.StoreTagService; } });
var ThemeService_1 = require("./services/ThemeService");
Object.defineProperty(exports, "ThemeService", { enumerable: true, get: function () { return ThemeService_1.ThemeService; } });
var ThemeLibraryService_1 = require("./services/ThemeLibraryService");
Object.defineProperty(exports, "ThemeLibraryService", { enumerable: true, get: function () { return ThemeLibraryService_1.ThemeLibraryService; } });
var TiktokPixelService_1 = require("./services/TiktokPixelService");
Object.defineProperty(exports, "TiktokPixelService", { enumerable: true, get: function () { return TiktokPixelService_1.TiktokPixelService; } });
var TransactionService_1 = require("./services/TransactionService");
Object.defineProperty(exports, "TransactionService", { enumerable: true, get: function () { return TransactionService_1.TransactionService; } });
var UploadService_1 = require("./services/UploadService");
Object.defineProperty(exports, "UploadService", { enumerable: true, get: function () { return UploadService_1.UploadService; } });
var UserService_1 = require("./services/UserService");
Object.defineProperty(exports, "UserService", { enumerable: true, get: function () { return UserService_1.UserService; } });
var VariantService_1 = require("./services/VariantService");
Object.defineProperty(exports, "VariantService", { enumerable: true, get: function () { return VariantService_1.VariantService; } });
var VariantComboService_1 = require("./services/VariantComboService");
Object.defineProperty(exports, "VariantComboService", { enumerable: true, get: function () { return VariantComboService_1.VariantComboService; } });
var WalletService_1 = require("./services/WalletService");
Object.defineProperty(exports, "WalletService", { enumerable: true, get: function () { return WalletService_1.WalletService; } });
