/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ClientApi } from './ClientApi';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export { ActionOrderFraud } from './models/ActionOrderFraud';
export { ActiveDetection } from './models/ActiveDetection';
export type { AddPaymentToStores } from './models/AddPaymentToStores';
export type { AddPlatformProductStoresDto } from './models/AddPlatformProductStoresDto';
export type { AddPlatformProductTagDto } from './models/AddPlatformProductTagDto';
export type { AddPlatformVariantToGroupDto } from './models/AddPlatformVariantToGroupDto';
export type { AdminTag } from './models/AdminTag';
export type { ApproveRequestSourcingDto } from './models/ApproveRequestSourcingDto';
export type { ApproveStoreDto } from './models/ApproveStoreDto';
export type { AsyncTask } from './models/AsyncTask';
export type { AsyncTaskError } from './models/AsyncTaskError';
export { AsyncTaskStatus } from './models/AsyncTaskStatus';
export { AsyncTaskType } from './models/AsyncTaskType';
export type { AuthData } from './models/AuthData';
export type { AuthStoreData } from './models/AuthStoreData';
export type { AvailableSet } from './models/AvailableSet';
export type { BankAccount } from './models/BankAccount';
export type { bankInfo } from './models/bankInfo';
export type { BatchPayload } from './models/BatchPayload';
export type { BillingInfo } from './models/BillingInfo';
export type { Campaign } from './models/Campaign';
export type { CampaignDto } from './models/CampaignDto';
export type { ChangeActiveTheme } from './models/ChangeActiveTheme';
export type { ChangeUserPasswordDto } from './models/ChangeUserPasswordDto';
export type { CloneProductDto } from './models/CloneProductDto';
export type { Collection } from './models/Collection';
export { CollectionField_name } from './models/CollectionField_name';
export { CollectionField_price } from './models/CollectionField_price';
export { CollectionField_tag } from './models/CollectionField_tag';
export { CollectionStatus } from './models/CollectionStatus';
export { CollectionType } from './models/CollectionType';
export { CombineOperator } from './models/CombineOperator';
export type { ComboItemDto } from './models/ComboItemDto';
export type { ConditionOperation } from './models/ConditionOperation';
export type { ContactFormDto } from './models/ContactFormDto';
export type { Coordinate } from './models/Coordinate';
export { CostCalculationMethod } from './models/CostCalculationMethod';
export type { CreateBankAccountDto } from './models/CreateBankAccountDto';
export type { CreateCollectionDto } from './models/CreateCollectionDto';
export type { CreateComboDto } from './models/CreateComboDto';
export type { CreateCurrencyDto } from './models/CreateCurrencyDto';
export type { CreateDiscountDto } from './models/CreateDiscountDto';
export type { CreateDomainDto } from './models/CreateDomainDto';
export type { CreateFbPixelDto } from './models/CreateFbPixelDto';
export type { CreateFulfillmentAgencyDto } from './models/CreateFulfillmentAgencyDto';
export type { CreateGADto } from './models/CreateGADto';
export type { CreateGroupPlatformVariantsDto } from './models/CreateGroupPlatformVariantsDto';
export type { CreateNotificationDto } from './models/CreateNotificationDto';
export type { CreateOrderDto } from './models/CreateOrderDto';
export type { CreatePaymentDto } from './models/CreatePaymentDto';
export type { CreatePingPongAccountDto } from './models/CreatePingPongAccountDto';
export type { CreatePlatformProductDto } from './models/CreatePlatformProductDto';
export type { CreatePlatformVariantDto } from './models/CreatePlatformVariantDto';
export type { CreatePlatformVariantsDto } from './models/CreatePlatformVariantsDto';
export type { CreateProductDto } from './models/CreateProductDto';
export type { CreateProductFromSellerInDependeceDto } from './models/CreateProductFromSellerInDependeceDto';
export type { CreateRequestPayoutDto } from './models/CreateRequestPayoutDto';
export type { CreateRequestSourcingDto } from './models/CreateRequestSourcingDto';
export type { CreateReviewDto } from './models/CreateReviewDto';
export type { CreateStaffDto } from './models/CreateStaffDto';
export type { CreateStoreDto } from './models/CreateStoreDto';
export type { CreateStoreTagDto } from './models/CreateStoreTagDto';
export type { CreateTagDto } from './models/CreateTagDto';
export type { CreateThemeDto } from './models/CreateThemeDto';
export type { CreateThemeLibraryDto } from './models/CreateThemeLibraryDto';
export type { CreateTiktokPixelDto } from './models/CreateTiktokPixelDto';
export type { CreateUploadDto } from './models/CreateUploadDto';
export type { CreateVariantsDto } from './models/CreateVariantsDto';
export type { CrossSell } from './models/CrossSell';
export type { CrossSellDto } from './models/CrossSellDto';
export { CrossSellTriggerType } from './models/CrossSellTriggerType';
export { CrossSellType } from './models/CrossSellType';
export type { Currency } from './models/Currency';
export { CurrencyCode } from './models/CurrencyCode';
export { CurrencyType } from './models/CurrencyType';
export type { CustomDomain } from './models/CustomDomain';
export { CustomDomainStatus } from './models/CustomDomainStatus';
export type { Discount } from './models/Discount';
export { DiscountCrossSellType } from './models/DiscountCrossSellType';
export type { DiscountDto } from './models/DiscountDto';
export type { EmailDto } from './models/EmailDto';
export { EnvironmentType } from './models/EnvironmentType';
export type { EventFraudType } from './models/EventFraudType';
export { EventOrderFraud } from './models/EventOrderFraud';
export type { ExportAccountancyResult } from './models/ExportAccountancyResult';
export type { ExportOrderDto } from './models/ExportOrderDto';
export type { ExportOrderResponseDto } from './models/ExportOrderResponseDto';
export type { ExportOrderResult } from './models/ExportOrderResult';
export type { FbPixel } from './models/FbPixel';
export type { FixedCostInfo } from './models/FixedCostInfo';
export type { FraudDetection } from './models/FraudDetection';
export { FraudDetectionStatusType } from './models/FraudDetectionStatusType';
export { FraudDetectionType } from './models/FraudDetectionType';
export { FraudStatusType } from './models/FraudStatusType';
export type { FulfillmentAgency } from './models/FulfillmentAgency';
export { FulfillmentAgencyRole } from './models/FulfillmentAgencyRole';
export { FulfillmentAgencyStatus } from './models/FulfillmentAgencyStatus';
export { FulfillmentStatus } from './models/FulfillmentStatus';
export type { FulfillmentUser } from './models/FulfillmentUser';
export type { GetAllOrderDto } from './models/GetAllOrderDto';
export type { GetAllStoresDto } from './models/GetAllStoresDto';
export type { GoogleAnalytic } from './models/GoogleAnalytic';
export type { GroupPlatformVariant } from './models/GroupPlatformVariant';
export type { JsonArray } from './models/JsonArray';
export type { JsonObject } from './models/JsonObject';
export type { JsonValue } from './models/JsonValue';
export type { LoginDto } from './models/LoginDto';
export { LogoSize } from './models/LogoSize';
export type { ManualFraudDetectionDto } from './models/ManualFraudDetectionDto';
export type { NameConditionDto } from './models/NameConditionDto';
export type { NameDto } from './models/NameDto';
export type { Notification } from './models/Notification';
export type { NotificationData } from './models/NotificationData';
export { NotificationType } from './models/NotificationType';
export { OperatorCollection_CONTAIN } from './models/OperatorCollection_CONTAIN';
export { OperatorCollection_ENDS_WITH } from './models/OperatorCollection_ENDS_WITH';
export { OperatorCollection_EQUAL_TO } from './models/OperatorCollection_EQUAL_TO';
export { OperatorCollection_GREATER_TO } from './models/OperatorCollection_GREATER_TO';
export { OperatorCollection_LESS_TO } from './models/OperatorCollection_LESS_TO';
export { OperatorCollection_NOT_CONTAIN } from './models/OperatorCollection_NOT_CONTAIN';
export { OperatorCollection_NOT_EQUAL_TO } from './models/OperatorCollection_NOT_EQUAL_TO';
export { OperatorCollection_STARTS_WITH } from './models/OperatorCollection_STARTS_WITH';
export type { operatorCondition } from './models/operatorCondition';
export type { Order } from './models/Order';
export { OrderDisputeStatus } from './models/OrderDisputeStatus';
export type { OrderInformationFraudType } from './models/OrderInformationFraudType';
export type { OrderItem } from './models/OrderItem';
export type { OrderItemDto } from './models/OrderItemDto';
export type { OrderRefund } from './models/OrderRefund';
export { OrderStatus } from './models/OrderStatus';
export type { Payment } from './models/Payment';
export { PaymentMethodType } from './models/PaymentMethodType';
export { PaymentType } from './models/PaymentType';
export type { PercentageCostInfo } from './models/PercentageCostInfo';
export { Period } from './models/Period';
export type { PhoneWithCountryCode } from './models/PhoneWithCountryCode';
export type { PhotoDto } from './models/PhotoDto';
export type { Photos } from './models/Photos';
export type { PingPongAccount } from './models/PingPongAccount';
export { PlacementCrossSellEnum } from './models/PlacementCrossSellEnum';
export type { PlatformCostInfo } from './models/PlatformCostInfo';
export type { PlatformProduct } from './models/PlatformProduct';
export type { PlatformProductStore } from './models/PlatformProductStore';
export type { PlatformVariant } from './models/PlatformVariant';
export type { PlatformVariantDto } from './models/PlatformVariantDto';
export type { PriceConditionDto } from './models/PriceConditionDto';
export type { Prisma_JsonValue } from './models/Prisma_JsonValue';
export type { PrismaJson_AsyncTaskResult } from './models/PrismaJson_AsyncTaskResult';
export type { PrismaJson_AvailableSet } from './models/PrismaJson_AvailableSet';
export type { PrismaJson_bankInfo } from './models/PrismaJson_bankInfo';
export type { PrismaJson_BillingInfo } from './models/PrismaJson_BillingInfo';
export type { PrismaJson_Colors } from './models/PrismaJson_Colors';
export type { PrismaJson_ConditionCollection } from './models/PrismaJson_ConditionCollection';
export type { PrismaJson_CostInfo } from './models/PrismaJson_CostInfo';
export type { PrismaJson_DiscountCrossSell } from './models/PrismaJson_DiscountCrossSell';
export type { PrismaJson_FirebaseDeviceToken } from './models/PrismaJson_FirebaseDeviceToken';
export type { PrismaJson_HoldSetting } from './models/PrismaJson_HoldSetting';
export type { PrismaJson_MarginInfo } from './models/PrismaJson_MarginInfo';
export type { PrismaJson_Photos } from './models/PrismaJson_Photos';
export type { PrismaJson_PlacementCrossSellType } from './models/PrismaJson_PlacementCrossSellType';
export type { PrismaJson_PlatformCostInfo } from './models/PrismaJson_PlatformCostInfo';
export type { PrismaJson_ProductDiscountItems } from './models/PrismaJson_ProductDiscountItems';
export type { PrismaJson_ProductRequirementItems } from './models/PrismaJson_ProductRequirementItems';
export type { PrismaJson_RefundOrderItems } from './models/PrismaJson_RefundOrderItems';
export type { PrismaJson_RequestSourcingHistory } from './models/PrismaJson_RequestSourcingHistory';
export type { PrismaJson_SyncBalanceAmount } from './models/PrismaJson_SyncBalanceAmount';
export type { PrismaJson_ThemeNodes } from './models/PrismaJson_ThemeNodes';
export type { PrismaJson_ThemeSetting } from './models/PrismaJson_ThemeSetting';
export type { PrismaJson_ThemeStyle } from './models/PrismaJson_ThemeStyle';
export type { PrismaJson_Timezone } from './models/PrismaJson_Timezone';
export type { PrismaJson_TypeOfFraudService } from './models/PrismaJson_TypeOfFraudService';
export type { PrismaJson_UnavailableBalance } from './models/PrismaJson_UnavailableBalance';
export type { PrismaJson_VariantComboItems } from './models/PrismaJson_VariantComboItems';
export type { PrismaJson_VariantOptions } from './models/PrismaJson_VariantOptions';
export type { PrismaJson_VariantOptionValues } from './models/PrismaJson_VariantOptionValues';
export type { Product } from './models/Product';
export type { ProductPerformance } from './models/ProductPerformance';
export type { ProductPerformanceResult } from './models/ProductPerformanceResult';
export type { ProductVariant } from './models/ProductVariant';
export type { RefundOrderDto } from './models/RefundOrderDto';
export { RefundType } from './models/RefundType';
export type { RejectRequestSourcingDto } from './models/RejectRequestSourcingDto';
export type { RequestPayout } from './models/RequestPayout';
export { RequestPayoutStatus } from './models/RequestPayoutStatus';
export type { RequestSourcing } from './models/RequestSourcing';
export { RequestSourcingStatus } from './models/RequestSourcingStatus';
export type { Review } from './models/Review';
export type { Setting } from './models/Setting';
export type { SQLResult } from './models/SQLResult';
export { statusRequestPayout } from './models/statusRequestPayout';
export type { Store } from './models/Store';
export type { StorePerformance } from './models/StorePerformance';
export type { StoreProductPerformanceResp } from './models/StoreProductPerformanceResp';
export type { StoreProductProfit } from './models/StoreProductProfit';
export type { StoreRevenueOverTime } from './models/StoreRevenueOverTime';
export { StoreRole } from './models/StoreRole';
export { StoreStatus } from './models/StoreStatus';
export { StoreType } from './models/StoreType';
export type { StoreUser } from './models/StoreUser';
export type { SubscribeTopicDto } from './models/SubscribeTopicDto';
export type { SyncBalanceAmount } from './models/SyncBalanceAmount';
export { SyncTrackingStatus } from './models/SyncTrackingStatus';
export type { Tag } from './models/Tag';
export type { TagConditionDto } from './models/TagConditionDto';
export type { Theme } from './models/Theme';
export type { ThemeLibrary } from './models/ThemeLibrary';
export type { ThemePage } from './models/ThemePage';
export type { ThemeTemplate } from './models/ThemeTemplate';
export type { TiktokPixel } from './models/TiktokPixel';
export type { Timezone } from './models/Timezone';
export { TimezoneDto } from './models/TimezoneDto';
export type { TopProductByOrder } from './models/TopProductByOrder';
export type { TopStoreByRevenue } from './models/TopStoreByRevenue';
export type { TopUpWalletDto } from './models/TopUpWalletDto';
export type { Transaction } from './models/Transaction';
export { TransactionStatus } from './models/TransactionStatus';
export { TransactionType } from './models/TransactionType';
export { typeFulfillmentPrice } from './models/typeFulfillmentPrice';
export { TypeOfFraud } from './models/TypeOfFraud';
export type { UnsubscribeTopicDto } from './models/UnsubscribeTopicDto';
export type { UpdateBankAccountDto } from './models/UpdateBankAccountDto';
export type { UpdateCampaignDto } from './models/UpdateCampaignDto';
export type { UpdateCollectionDto } from './models/UpdateCollectionDto';
export type { UpdateCollectionStatusDto } from './models/UpdateCollectionStatusDto';
export type { UpdateComboDto } from './models/UpdateComboDto';
export type { UpdateCombosDto } from './models/UpdateCombosDto';
export type { UpdateComboStatusDto } from './models/UpdateComboStatusDto';
export type { UpdateCrossSellStatusDto } from './models/UpdateCrossSellStatusDto';
export type { UpdateCurrencyDto } from './models/UpdateCurrencyDto';
export type { UpdateDiscountDto } from './models/UpdateDiscountDto';
export type { UpdateFbPixelDto } from './models/UpdateFbPixelDto';
export type { UpdateFulfillmentAgencyDto } from './models/UpdateFulfillmentAgencyDto';
export type { UpdateFulfillmentAgencyStatusDto } from './models/UpdateFulfillmentAgencyStatusDto';
export type { UpdateFulFillmentStatusError } from './models/UpdateFulFillmentStatusError';
export type { UpdateFulFillmentStatusResp } from './models/UpdateFulFillmentStatusResp';
export type { UpdateGADto } from './models/UpdateGADto';
export type { UpdateGroupPlatformVariantsDto } from './models/UpdateGroupPlatformVariantsDto';
export type { UpdateManyStorePaymentMethodDto } from './models/UpdateManyStorePaymentMethodDto';
export type { UpdateNotificationDto } from './models/UpdateNotificationDto';
export type { UpdateOrderRefundDto } from './models/UpdateOrderRefundDto';
export type { UpdateOrderRefundHistoryDto } from './models/UpdateOrderRefundHistoryDto';
export type { UpdateOrderStatusDto } from './models/UpdateOrderStatusDto';
export type { UpdatePaymentDto } from './models/UpdatePaymentDto';
export type { UpdatePingPongAccountDto } from './models/UpdatePingPongAccountDto';
export type { UpdatePlatformProductDto } from './models/UpdatePlatformProductDto';
export type { UpdatePlatformProductStatusDto } from './models/UpdatePlatformProductStatusDto';
export type { UpdatePlatformProductStatusesDto } from './models/UpdatePlatformProductStatusesDto';
export type { UpdatePlatformProductVariantDto } from './models/UpdatePlatformProductVariantDto';
export type { UpdatePlatformVariantDto } from './models/UpdatePlatformVariantDto';
export type { UpdatePlatformVariantsDto } from './models/UpdatePlatformVariantsDto';
export type { UpdatePlatformVariantStatusDto } from './models/UpdatePlatformVariantStatusDto';
export type { UpdateProductDto } from './models/UpdateProductDto';
export type { UpdateProductStatusDto } from './models/UpdateProductStatusDto';
export type { UpdateProductStatusesDto } from './models/UpdateProductStatusesDto';
export type { UpdateRequestPayoutDto } from './models/UpdateRequestPayoutDto';
export type { UpdateRequestSourcingDto } from './models/UpdateRequestSourcingDto';
export type { UpdateReviewDto } from './models/UpdateReviewDto';
export type { UpdateSettingDto } from './models/UpdateSettingDto';
export type { UpdateStaffDto } from './models/UpdateStaffDto';
export type { UpdateStoreDto } from './models/UpdateStoreDto';
export type { UpdateStorePaymentMethodDto } from './models/UpdateStorePaymentMethodDto';
export type { UpdateStoreStatusDto } from './models/UpdateStoreStatusDto';
export type { UpdateThemeDto } from './models/UpdateThemeDto';
export type { UpdateThemeLibraryDto } from './models/UpdateThemeLibraryDto';
export type { UpdateTiktokPixelDto } from './models/UpdateTiktokPixelDto';
export type { UpdateUserDto } from './models/UpdateUserDto';
export type { UpdateVariantDto } from './models/UpdateVariantDto';
export type { UpdateVariantsDto } from './models/UpdateVariantsDto';
export type { UpdateVariantsForSellerInDependenceDto } from './models/UpdateVariantsForSellerInDependenceDto';
export type { UpdateVariantStatusDto } from './models/UpdateVariantStatusDto';
export type { URLDto } from './models/URLDto';
export type { User } from './models/User';
export { UserRole } from './models/UserRole';
export type { VariantCombo } from './models/VariantCombo';
export type { VariantDto } from './models/VariantDto';
export type { VariantOptions } from './models/VariantOptions';
export type { VariantOptionValues } from './models/VariantOptionValues';
export type { Wallet } from './models/Wallet';
export type { WithdrawWalletDto } from './models/WithdrawWalletDto';

export { AsyncTaskService } from './services/AsyncTaskService';
export { AuthService } from './services/AuthService';
export { FulfillmentAgencyService } from './services/FulfillmentAgencyService';
export { NotificationService } from './services/NotificationService';
export { PerformanceService } from './services/PerformanceService';
export { UploadService } from './services/UploadService';
export { UserService } from './services/UserService';
