/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ClientApi } from './ClientApi';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export { _36_Enums_AsyncTaskStatus } from './models/_36_Enums_AsyncTaskStatus';
export { _36_Enums_AsyncTaskType } from './models/_36_Enums_AsyncTaskType';
export { _36_Enums_BoostSaleTriggerType } from './models/_36_Enums_BoostSaleTriggerType';
export { _36_Enums_BoostSaleType } from './models/_36_Enums_BoostSaleType';
export { _36_Enums_CapabilityStatus } from './models/_36_Enums_CapabilityStatus';
export { _36_Enums_CollectionStatus } from './models/_36_Enums_CollectionStatus';
export { _36_Enums_CollectionType } from './models/_36_Enums_CollectionType';
export { _36_Enums_CostCalculationMethod } from './models/_36_Enums_CostCalculationMethod';
export { _36_Enums_CouponApplyingMethod } from './models/_36_Enums_CouponApplyingMethod';
export { _36_Enums_CouponStatus } from './models/_36_Enums_CouponStatus';
export { _36_Enums_CouponType } from './models/_36_Enums_CouponType';
export { _36_Enums_CurrencyType } from './models/_36_Enums_CurrencyType';
export { _36_Enums_CustomDomainStatus } from './models/_36_Enums_CustomDomainStatus';
export { _36_Enums_DomainOrigin } from './models/_36_Enums_DomainOrigin';
export { _36_Enums_EmailTrackingAction } from './models/_36_Enums_EmailTrackingAction';
export { _36_Enums_EnvironmentType } from './models/_36_Enums_EnvironmentType';
export { _36_Enums_FraudDetectionStatusType } from './models/_36_Enums_FraudDetectionStatusType';
export { _36_Enums_FraudDetectionType } from './models/_36_Enums_FraudDetectionType';
export { _36_Enums_FulfillmentAgencyRole } from './models/_36_Enums_FulfillmentAgencyRole';
export { _36_Enums_FulfillmentAgencyStatus } from './models/_36_Enums_FulfillmentAgencyStatus';
export { _36_Enums_FulfillmentAgencyType } from './models/_36_Enums_FulfillmentAgencyType';
export { _36_Enums_FulfillmentPlatform } from './models/_36_Enums_FulfillmentPlatform';
export { _36_Enums_FulfillmentPlatformIntegrationStatus } from './models/_36_Enums_FulfillmentPlatformIntegrationStatus';
export { _36_Enums_FulfillmentStatus } from './models/_36_Enums_FulfillmentStatus';
export { _36_Enums_HistoryTrackingType } from './models/_36_Enums_HistoryTrackingType';
export { _36_Enums_LogoSize } from './models/_36_Enums_LogoSize';
export { _36_Enums_MarketingType } from './models/_36_Enums_MarketingType';
export { _36_Enums_NotificationType } from './models/_36_Enums_NotificationType';
export { _36_Enums_OnboardingStatus } from './models/_36_Enums_OnboardingStatus';
export { _36_Enums_OrderDisputeStatus } from './models/_36_Enums_OrderDisputeStatus';
export { _36_Enums_OrderStatus } from './models/_36_Enums_OrderStatus';
export { _36_Enums_OrderTrackingEmailStatus } from './models/_36_Enums_OrderTrackingEmailStatus';
export { _36_Enums_OrderTrackingRecoveredStatus } from './models/_36_Enums_OrderTrackingRecoveredStatus';
export { _36_Enums_PaymentIntegrationType } from './models/_36_Enums_PaymentIntegrationType';
export { _36_Enums_PaymentMethodType } from './models/_36_Enums_PaymentMethodType';
export { _36_Enums_PaymentType } from './models/_36_Enums_PaymentType';
export { _36_Enums_PingPongAuthStatus } from './models/_36_Enums_PingPongAuthStatus';
export { _36_Enums_PPCPVettingStatus } from './models/_36_Enums_PPCPVettingStatus';
export { _36_Enums_RequestPayoutStatus } from './models/_36_Enums_RequestPayoutStatus';
export { _36_Enums_RequestSourcingStatus } from './models/_36_Enums_RequestSourcingStatus';
export { _36_Enums_RolePermissionType } from './models/_36_Enums_RolePermissionType';
export { _36_Enums_SaleStatus } from './models/_36_Enums_SaleStatus';
export { _36_Enums_SaleUserTrackingType } from './models/_36_Enums_SaleUserTrackingType';
export { _36_Enums_StoreEmailLogStatus } from './models/_36_Enums_StoreEmailLogStatus';
export { _36_Enums_StoreLogType } from './models/_36_Enums_StoreLogType';
export { _36_Enums_StoreRole } from './models/_36_Enums_StoreRole';
export { _36_Enums_StoreStatus } from './models/_36_Enums_StoreStatus';
export { _36_Enums_StoreType } from './models/_36_Enums_StoreType';
export { _36_Enums_StoreUserInviteStatus } from './models/_36_Enums_StoreUserInviteStatus';
export { _36_Enums_SubscriptionFeatureType } from './models/_36_Enums_SubscriptionFeatureType';
export { _36_Enums_SubscriptionInterval } from './models/_36_Enums_SubscriptionInterval';
export { _36_Enums_SubscriptionStatus } from './models/_36_Enums_SubscriptionStatus';
export { _36_Enums_SubscriptionType } from './models/_36_Enums_SubscriptionType';
export { _36_Enums_SyncTrackingStatus } from './models/_36_Enums_SyncTrackingStatus';
export { _36_Enums_TaxProviderOwner } from './models/_36_Enums_TaxProviderOwner';
export { _36_Enums_ThemePageType } from './models/_36_Enums_ThemePageType';
export { _36_Enums_TransactionStatus } from './models/_36_Enums_TransactionStatus';
export { _36_Enums_TransactionType } from './models/_36_Enums_TransactionType';
export { _36_Enums_UserRole } from './models/_36_Enums_UserRole';
export type { AbandonmentStatisticsDto } from './models/AbandonmentStatisticsDto';
export type { AcceptStoreInviteDto } from './models/AcceptStoreInviteDto';
export { ActionOrderFraud } from './models/ActionOrderFraud';
export { ActiveDetection } from './models/ActiveDetection';
export type { ActivePaymentSSFFDto } from './models/ActivePaymentSSFFDto';
export type { AddNewPaymentOnboardingV1Dto } from './models/AddNewPaymentOnboardingV1Dto';
export type { AddPaymentToStores } from './models/AddPaymentToStores';
export type { AddPlatformProductStoresDto } from './models/AddPlatformProductStoresDto';
export type { AddPlatformProductTagDto } from './models/AddPlatformProductTagDto';
export type { AddPlatformVariantToGroupDto } from './models/AddPlatformVariantToGroupDto';
export type { AddRefCodeDto } from './models/AddRefCodeDto';
export type { AdminTag } from './models/AdminTag';
export type { AgencyStatisticResp } from './models/AgencyStatisticResp';
export type { ApproveRequestSourcingDto } from './models/ApproveRequestSourcingDto';
export type { ApproveStoreDto } from './models/ApproveStoreDto';
export type { AsyncTask } from './models/AsyncTask';
export type { AsyncTaskError } from './models/AsyncTaskError';
export type { AuthData } from './models/AuthData';
export type { AuthFulfillmentPlatformData } from './models/AuthFulfillmentPlatformData';
export type { AuthStoreData } from './models/AuthStoreData';
export type { BankAccount } from './models/BankAccount';
export type { bankInfo } from './models/bankInfo';
export type { BoostSale } from './models/BoostSale';
export type { BoostSaleDto } from './models/BoostSaleDto';
export type { BoostSaleTriggerType } from './models/BoostSaleTriggerType';
export type { BoostSaleType } from './models/BoostSaleType';
export { BoughtTogetherType } from './models/BoughtTogetherType';
export type { BulkCreatePingpongAccountDto } from './models/BulkCreatePingpongAccountDto';
export type { BulkDeletePingpongAccountDto } from './models/BulkDeletePingpongAccountDto';
export type { BulkUpDatePingpongAccountDto } from './models/BulkUpDatePingpongAccountDto';
export type { BuyDomainDto } from './models/BuyDomainDto';
export type { Campaign } from './models/Campaign';
export type { CampaignDto } from './models/CampaignDto';
export type { ChangeActiveTheme } from './models/ChangeActiveTheme';
export type { ChangeIntegrationStatusDto } from './models/ChangeIntegrationStatusDto';
export type { ChangePasswordDto } from './models/ChangePasswordDto';
export type { ChangeUserPasswordDto } from './models/ChangeUserPasswordDto';
export type { CheckRejectStatusDto } from './models/CheckRejectStatusDto';
export type { CheckVerifyEmailDto } from './models/CheckVerifyEmailDto';
export type { ClearCacheDto } from './models/ClearCacheDto';
export type { ClickToOrderDto } from './models/ClickToOrderDto';
export type { CloneProductDto } from './models/CloneProductDto';
export type { CloneThemePageDto } from './models/CloneThemePageDto';
export type { Collection } from './models/Collection';
export { CollectionField_name } from './models/CollectionField_name';
export { CollectionField_price } from './models/CollectionField_price';
export { CollectionField_tag } from './models/CollectionField_tag';
export type { CollectionStatus } from './models/CollectionStatus';
export type { CollectionType } from './models/CollectionType';
export { CombineOperator } from './models/CombineOperator';
export type { ComboItemDto } from './models/ComboItemDto';
export type { ComboItemTrackingDto } from './models/ComboItemTrackingDto';
export type { ConditionOperation } from './models/ConditionOperation';
export type { ConnectQuadernoDto } from './models/ConnectQuadernoDto';
export type { ConnectWithPingPongAccountDto } from './models/ConnectWithPingPongAccountDto';
export type { ContactFormDto } from './models/ContactFormDto';
export type { CostCalculationMethod } from './models/CostCalculationMethod';
export type { CountryInformationType } from './models/CountryInformationType';
export type { CouponApplyingMethod } from './models/CouponApplyingMethod';
export { CouponCombinationItem } from './models/CouponCombinationItem';
export type { CouponStatus } from './models/CouponStatus';
export type { CouponType } from './models/CouponType';
export type { CreateAbandonmentOrder } from './models/CreateAbandonmentOrder';
export type { CreateBankAccountDto } from './models/CreateBankAccountDto';
export type { CreateCollectionDefaultDto } from './models/CreateCollectionDefaultDto';
export type { CreateCollectionDto } from './models/CreateCollectionDto';
export type { CreateComboDto } from './models/CreateComboDto';
export type { CreateCouponDto } from './models/CreateCouponDto';
export type { CreateCurrencyDto } from './models/CreateCurrencyDto';
export type { CreateDiscountDto } from './models/CreateDiscountDto';
export type { CreateDomainDto } from './models/CreateDomainDto';
export type { CreateFbPixelDto } from './models/CreateFbPixelDto';
export type { CreateFulfillmentAgencyDto } from './models/CreateFulfillmentAgencyDto';
export type { CreateFulfillmentRoleDto } from './models/CreateFulfillmentRoleDto';
export type { CreateGADto } from './models/CreateGADto';
export type { CreateGroupPlatformVariantsDto } from './models/CreateGroupPlatformVariantsDto';
export type { CreateGTMDto } from './models/CreateGTMDto';
export type { CreateLogDto } from './models/CreateLogDto';
export type { CreateMarketingAccount } from './models/CreateMarketingAccount';
export type { CreateNotificationDto } from './models/CreateNotificationDto';
export type { CreateOrderDto } from './models/CreateOrderDto';
export type { CreateOrderTrackingDto } from './models/CreateOrderTrackingDto';
export type { CreatePaymentDto } from './models/CreatePaymentDto';
export type { CreatePaymentV1Dto } from './models/CreatePaymentV1Dto';
export type { CreatePingPongAccountDto } from './models/CreatePingPongAccountDto';
export type { CreatePlatformProductDto } from './models/CreatePlatformProductDto';
export type { CreatePlatformVariantDto } from './models/CreatePlatformVariantDto';
export type { CreatePlatformVariantsDto } from './models/CreatePlatformVariantsDto';
export type { CreateProductDto } from './models/CreateProductDto';
export type { CreateProductFromSellerInDependenceDto } from './models/CreateProductFromSellerInDependenceDto';
export type { CreateRequestPayoutDto } from './models/CreateRequestPayoutDto';
export type { CreateRequestSourcingDto } from './models/CreateRequestSourcingDto';
export type { CreateReviewDto } from './models/CreateReviewDto';
export type { CreateRoleDto } from './models/CreateRoleDto';
export type { CreateRoleRes } from './models/CreateRoleRes';
export type { CreateSnapChatPixelDto } from './models/CreateSnapChatPixelDto';
export type { CreateStaffDto } from './models/CreateStaffDto';
export type { CreateStaffFulfillmentAgencyDto } from './models/CreateStaffFulfillmentAgencyDto';
export type { CreateStoreDto } from './models/CreateStoreDto';
export type { CreateStoreTagDto } from './models/CreateStoreTagDto';
export type { CreateSubscriptionFeatureDto } from './models/CreateSubscriptionFeatureDto';
export type { CreateSubscriptionPlanDto } from './models/CreateSubscriptionPlanDto';
export type { CreateSuperAdminDto } from './models/CreateSuperAdminDto';
export type { CreateTagDto } from './models/CreateTagDto';
export type { CreateTemplateDto } from './models/CreateTemplateDto';
export type { CreateThemeDto } from './models/CreateThemeDto';
export type { CreateThemeLibraryDto } from './models/CreateThemeLibraryDto';
export type { CreateTiktokPixelDto } from './models/CreateTiktokPixelDto';
export type { CreateUploadDto } from './models/CreateUploadDto';
export type { CreateVariantsDto } from './models/CreateVariantsDto';
export type { Currency } from './models/Currency';
export { CurrencyCode } from './models/CurrencyCode';
export type { CurrencyType } from './models/CurrencyType';
export type { CustomDomain } from './models/CustomDomain';
export type { DefaultSelection_Prisma__36_AdminTagPayload_ } from './models/DefaultSelection_Prisma__36_AdminTagPayload_';
export type { DefaultSelection_Prisma__36_AsyncTaskPayload_ } from './models/DefaultSelection_Prisma__36_AsyncTaskPayload_';
export type { DefaultSelection_Prisma__36_BankAccountPayload_ } from './models/DefaultSelection_Prisma__36_BankAccountPayload_';
export type { DefaultSelection_Prisma__36_BoostSalePayload_ } from './models/DefaultSelection_Prisma__36_BoostSalePayload_';
export type { DefaultSelection_Prisma__36_CampaignPayload_ } from './models/DefaultSelection_Prisma__36_CampaignPayload_';
export type { DefaultSelection_Prisma__36_CollectionPayload_ } from './models/DefaultSelection_Prisma__36_CollectionPayload_';
export type { DefaultSelection_Prisma__36_CurrencyPayload_ } from './models/DefaultSelection_Prisma__36_CurrencyPayload_';
export type { DefaultSelection_Prisma__36_CustomDomainPayload_ } from './models/DefaultSelection_Prisma__36_CustomDomainPayload_';
export type { DefaultSelection_Prisma__36_DiscountPayload_ } from './models/DefaultSelection_Prisma__36_DiscountPayload_';
export type { DefaultSelection_Prisma__36_FbPixelPayload_ } from './models/DefaultSelection_Prisma__36_FbPixelPayload_';
export type { DefaultSelection_Prisma__36_FraudDetectionPayload_ } from './models/DefaultSelection_Prisma__36_FraudDetectionPayload_';
export type { DefaultSelection_Prisma__36_FulfillmentAgencyPayload_ } from './models/DefaultSelection_Prisma__36_FulfillmentAgencyPayload_';
export type { DefaultSelection_Prisma__36_FulfillmentUserPayload_ } from './models/DefaultSelection_Prisma__36_FulfillmentUserPayload_';
export type { DefaultSelection_Prisma__36_GoogleAnalyticPayload_ } from './models/DefaultSelection_Prisma__36_GoogleAnalyticPayload_';
export type { DefaultSelection_Prisma__36_GoogleTagManagerPayload_ } from './models/DefaultSelection_Prisma__36_GoogleTagManagerPayload_';
export type { DefaultSelection_Prisma__36_GroupPlatformVariantPayload_ } from './models/DefaultSelection_Prisma__36_GroupPlatformVariantPayload_';
export type { DefaultSelection_Prisma__36_NotificationPayload_ } from './models/DefaultSelection_Prisma__36_NotificationPayload_';
export type { DefaultSelection_Prisma__36_OrderItemPayload_ } from './models/DefaultSelection_Prisma__36_OrderItemPayload_';
export type { DefaultSelection_Prisma__36_OrderPayload_ } from './models/DefaultSelection_Prisma__36_OrderPayload_';
export type { DefaultSelection_Prisma__36_OrderRefundPayload_ } from './models/DefaultSelection_Prisma__36_OrderRefundPayload_';
export type { DefaultSelection_Prisma__36_PaymentOnboardingPayload_ } from './models/DefaultSelection_Prisma__36_PaymentOnboardingPayload_';
export type { DefaultSelection_Prisma__36_PingPongAccountPayload_ } from './models/DefaultSelection_Prisma__36_PingPongAccountPayload_';
export { DefaultSelection_Prisma__36_PlatformProductPayload_ } from './models/DefaultSelection_Prisma__36_PlatformProductPayload_';
export type { DefaultSelection_Prisma__36_PlatformVariantPayload_ } from './models/DefaultSelection_Prisma__36_PlatformVariantPayload_';
export type { DefaultSelection_Prisma__36_ProductPayload_ } from './models/DefaultSelection_Prisma__36_ProductPayload_';
export type { DefaultSelection_Prisma__36_ProductVariantPayload_ } from './models/DefaultSelection_Prisma__36_ProductVariantPayload_';
export type { DefaultSelection_Prisma__36_RegionalShippingFeePayload_ } from './models/DefaultSelection_Prisma__36_RegionalShippingFeePayload_';
export type { DefaultSelection_Prisma__36_RequestPayoutPayload_ } from './models/DefaultSelection_Prisma__36_RequestPayoutPayload_';
export type { DefaultSelection_Prisma__36_RequestSourcingPayload_ } from './models/DefaultSelection_Prisma__36_RequestSourcingPayload_';
export type { DefaultSelection_Prisma__36_ReviewPayload_ } from './models/DefaultSelection_Prisma__36_ReviewPayload_';
export type { DefaultSelection_Prisma__36_SnapChatPixelPayload_ } from './models/DefaultSelection_Prisma__36_SnapChatPixelPayload_';
export type { DefaultSelection_Prisma__36_StorePayload_ } from './models/DefaultSelection_Prisma__36_StorePayload_';
export type { DefaultSelection_Prisma__36_StoreUserPayload_ } from './models/DefaultSelection_Prisma__36_StoreUserPayload_';
export type { DefaultSelection_Prisma__36_TagPayload_ } from './models/DefaultSelection_Prisma__36_TagPayload_';
export type { DefaultSelection_Prisma__36_ThemeLibraryPayload_ } from './models/DefaultSelection_Prisma__36_ThemeLibraryPayload_';
export type { DefaultSelection_Prisma__36_ThemePagePayload_ } from './models/DefaultSelection_Prisma__36_ThemePagePayload_';
export type { DefaultSelection_Prisma__36_ThemePayload_ } from './models/DefaultSelection_Prisma__36_ThemePayload_';
export type { DefaultSelection_Prisma__36_TiktokPixelPayload_ } from './models/DefaultSelection_Prisma__36_TiktokPixelPayload_';
export type { DefaultSelection_Prisma__36_TransactionPayload_ } from './models/DefaultSelection_Prisma__36_TransactionPayload_';
export type { DefaultSelection_Prisma__36_UserPayload_ } from './models/DefaultSelection_Prisma__36_UserPayload_';
export type { DefaultSelection_Prisma__36_VariantComboPayload_ } from './models/DefaultSelection_Prisma__36_VariantComboPayload_';
export type { DefaultSelection_Prisma__36_WalletPayload_ } from './models/DefaultSelection_Prisma__36_WalletPayload_';
export type { DeleteCouponsDto } from './models/DeleteCouponsDto';
export type { DetailOrderDto } from './models/DetailOrderDto';
export type { DisconnectPaymentDto } from './models/DisconnectPaymentDto';
export type { Discount } from './models/Discount';
export { DiscountBoostSaleType } from './models/DiscountBoostSaleType';
export type { DiscountDto } from './models/DiscountDto';
export { DiscountForQuantityType } from './models/DiscountForQuantityType';
export { DiscountMaximumUses } from './models/DiscountMaximumUses';
export { DiscountMinimumPurchaseRequirement } from './models/DiscountMinimumPurchaseRequirement';
export { DiscountValueType } from './models/DiscountValueType';
export type { EditFulfillmentStaffDto } from './models/EditFulfillmentStaffDto';
export type { EditRoleDto } from './models/EditRoleDto';
export type { EditRoleFulfillmentDto } from './models/EditRoleFulfillmentDto';
export type { EditSuperAdminDto } from './models/EditSuperAdminDto';
export type { EmailDto } from './models/EmailDto';
export { ESendMailStatus } from './models/ESendMailStatus';
export type { EventFraudType } from './models/EventFraudType';
export { EventOrderFraud } from './models/EventOrderFraud';
export { Exclude_PaymentMethodType_CASH_or_BANK_TRANSFER_ } from './models/Exclude_PaymentMethodType_CASH_or_BANK_TRANSFER_';
export { Exclude_RequestSourcingStatus_SELLER_REJECTED_or_SELLER_ACCEPTED_ } from './models/Exclude_RequestSourcingStatus_SELLER_REJECTED_or_SELLER_ACCEPTED_';
export type { ExportAccountancyResult } from './models/ExportAccountancyResult';
export type { ExportOrderDto } from './models/ExportOrderDto';
export type { ExportOrderResponseDto } from './models/ExportOrderResponseDto';
export type { ExportOrderResult } from './models/ExportOrderResult';
export type { ExportPayoutRequestFilterDto } from './models/ExportPayoutRequestFilterDto';
export type { ExportProductRequestFilterDto } from './models/ExportProductRequestFilterDto';
export type { ExportStoreReportDto } from './models/ExportStoreReportDto';
export type { FbPixel } from './models/FbPixel';
export { FilterStoreReferral } from './models/FilterStoreReferral';
export { FilterStoreStatus } from './models/FilterStoreStatus';
export type { FixedCostInfo } from './models/FixedCostInfo';
export type { FraudDetection } from './models/FraudDetection';
export type { FraudDetectionStatusType } from './models/FraudDetectionStatusType';
export { FraudStatusType } from './models/FraudStatusType';
export type { FulfillmentAgency } from './models/FulfillmentAgency';
export type { FulfillmentAgencyStatus } from './models/FulfillmentAgencyStatus';
export type { FulfillmentAgencyType } from './models/FulfillmentAgencyType';
export { FulfillmentPermissions } from './models/FulfillmentPermissions';
export type { FulfillmentPlatform } from './models/FulfillmentPlatform';
export type { FulfillmentPlatformIntegrationStatus } from './models/FulfillmentPlatformIntegrationStatus';
export type { FulfillmentShippingCostDto } from './models/FulfillmentShippingCostDto';
export type { FulfillmentStatus } from './models/FulfillmentStatus';
export type { FulfillmentUser } from './models/FulfillmentUser';
export type { GeneratePartnerReferralsDto } from './models/GeneratePartnerReferralsDto';
export type { GetAccountRequestDto } from './models/GetAccountRequestDto';
export type { GetAllOrderDto } from './models/GetAllOrderDto';
export type { GetAllOrderResult } from './models/GetAllOrderResult';
export type { GetAllProductType } from './models/GetAllProductType';
export type { GetAllStoresDto } from './models/GetAllStoresDto';
export type { GetAutomationMetricStatisticsDto } from './models/GetAutomationMetricStatisticsDto';
export type { GetBatchResult } from './models/GetBatchResult';
export type { GetBoostSalesDto } from './models/GetBoostSalesDto';
export type { GetCrossSellByProductDto } from './models/GetCrossSellByProductDto';
export { GetCustomerTrackingDto } from './models/GetCustomerTrackingDto';
export type { GetCustomerTrackingResultDto } from './models/GetCustomerTrackingResultDto';
export type { GetDetailFulfillmentDto } from './models/GetDetailFulfillmentDto';
export type { GetDetailSellerInvitedDto } from './models/GetDetailSellerInvitedDto';
export type { GetGmvByStore } from './models/GetGmvByStore';
export type { GetGmvPerFulfillmentAgency } from './models/GetGmvPerFulfillmentAgency';
export type { GetImageTrackingDto } from './models/GetImageTrackingDto';
export type { GetListRoleDto } from './models/GetListRoleDto';
export type { GetListRoleFulfillmentDto } from './models/GetListRoleFulfillmentDto';
export type { GetListSellerByInvitedBySaleDto } from './models/GetListSellerByInvitedBySaleDto';
export type { GetListStoreMarketingDto } from './models/GetListStoreMarketingDto';
export type { GetListSuperAdminDto } from './models/GetListSuperAdminDto';
export type { GetListTaxProviderDto } from './models/GetListTaxProviderDto';
export type { GetOrderResult } from './models/GetOrderResult';
export type { GetOverviewStatisticsDto } from './models/GetOverviewStatisticsDto';
export type { GetPaginateTopLandingPageResultDto } from './models/GetPaginateTopLandingPageResultDto';
export type { GetPerformingStatisticsDto } from './models/GetPerformingStatisticsDto';
export type { GetPermissionsFulfillAgencyRes } from './models/GetPermissionsFulfillAgencyRes';
export type { GetPermissionsRes } from './models/GetPermissionsRes';
export type { GetPlatformProductDto } from './models/GetPlatformProductDto';
export type { GetReferralSaleDto } from './models/GetReferralSaleDto';
export type { GetRequestingAmountDto } from './models/GetRequestingAmountDto';
export type { GetRequestPayoutDto } from './models/GetRequestPayoutDto';
export type { GetRevenueStoreByFulfillmentDto } from './models/GetRevenueStoreByFulfillmentDto';
export type { GetRevenueStoreByFulfillmentResult } from './models/GetRevenueStoreByFulfillmentResult';
export type { GetSalePerformanceDto } from './models/GetSalePerformanceDto';
export type { GetStatsDeviceDto } from './models/GetStatsDeviceDto';
export type { GetStatsRefererDto } from './models/GetStatsRefererDto';
export type { getStatusCombosType } from './models/getStatusCombosType';
export type { GetStoreActiveThemeV2QueryDto } from './models/GetStoreActiveThemeV2QueryDto';
export type { GetStoreAddPingpongDto } from './models/GetStoreAddPingpongDto';
export type { GetStoreManagementDto } from './models/GetStoreManagementDto';
export type { GetStoreReportDto } from './models/GetStoreReportDto';
export type { GetStoreReportResultDto } from './models/GetStoreReportResultDto';
export type { GetStoreStatisticsAbandonmentDto } from './models/GetStoreStatisticsAbandonmentDto';
export type { GetSummaryReferralDto } from './models/GetSummaryReferralDto';
export type { GetSummaryReferralResult } from './models/GetSummaryReferralResult';
export type { GetTopCountryDto } from './models/GetTopCountryDto';
export type { GetTopDto } from './models/GetTopDto';
export type { GetTopLandingPageDto } from './models/GetTopLandingPageDto';
export type { GetTopLandingPageResultDto } from './models/GetTopLandingPageResultDto';
export type { GetTopRevenueStore } from './models/GetTopRevenueStore';
export type { GetTrackingImageSaleDto } from './models/GetTrackingImageSaleDto';
export type { GetTrackingOrderCheckoutDto } from './models/GetTrackingOrderCheckoutDto';
export type { GetTrackingPerformanceDto } from './models/GetTrackingPerformanceDto';
export type { GetTrackingRetentionRateDto } from './models/GetTrackingRetentionRateDto';
export type { GetTrackingRetentionRateResultDto } from './models/GetTrackingRetentionRateResultDto';
export type { GetTrafficSourceDto } from './models/GetTrafficSourceDto';
export type { getVariantsType } from './models/getVariantsType';
export type { GoogleAnalytic } from './models/GoogleAnalytic';
export type { GoogleTagManager } from './models/GoogleTagManager';
export type { GroupPlatformVariant } from './models/GroupPlatformVariant';
export type { HistoryItem } from './models/HistoryItem';
export type { HistoryTrackingOrderDto } from './models/HistoryTrackingOrderDto';
export type { HistoryTrackingType } from './models/HistoryTrackingType';
export type { ImportPlatformProductDto } from './models/ImportPlatformProductDto';
export type { ImportPlatformVariantDto } from './models/ImportPlatformVariantDto';
export type { IntegrationWithFulfillmentPlatformDto } from './models/IntegrationWithFulfillmentPlatformDto';
export type { InviteStoreStaffDto } from './models/InviteStoreStaffDto';
export type { IsUserEmailFoundDto } from './models/IsUserEmailFoundDto';
export type { KlaviyoDto } from './models/KlaviyoDto';
export type { ListAbandonmentOrdersDto } from './models/ListAbandonmentOrdersDto';
export type { ListCountryCode } from './models/ListCountryCode';
export type { ListCouponsQueryParams } from './models/ListCouponsQueryParams';
export type { ListFulfillmentStaffDto } from './models/ListFulfillmentStaffDto';
export type { ListProductsForThemePageQueryDto } from './models/ListProductsForThemePageQueryDto';
export type { ListStoreStaffDto } from './models/ListStoreStaffDto';
export type { ListThemePagesForActiveThemeQueryDto } from './models/ListThemePagesForActiveThemeQueryDto';
export type { LiveCoordinates } from './models/LiveCoordinates';
export type { LocationResult } from './models/LocationResult';
export type { LoginDto } from './models/LoginDto';
export type { LogoSize } from './models/LogoSize';
export type { ManualFraudDetectionDto } from './models/ManualFraudDetectionDto';
export type { MapPermission } from './models/MapPermission';
export type { NameConditionDto } from './models/NameConditionDto';
export type { NameDto } from './models/NameDto';
export type { Notification } from './models/Notification';
export type { NotificationData } from './models/NotificationData';
export type { NotificationType } from './models/NotificationType';
export { OnboardingProduct } from './models/OnboardingProduct';
export { OperatorCollection_CONTAIN } from './models/OperatorCollection_CONTAIN';
export { OperatorCollection_ENDS_WITH } from './models/OperatorCollection_ENDS_WITH';
export { OperatorCollection_EQUAL_TO } from './models/OperatorCollection_EQUAL_TO';
export { OperatorCollection_GREATER_TO } from './models/OperatorCollection_GREATER_TO';
export { OperatorCollection_LESS_TO } from './models/OperatorCollection_LESS_TO';
export { OperatorCollection_NOT_CONTAIN } from './models/OperatorCollection_NOT_CONTAIN';
export { OperatorCollection_NOT_EQUAL_TO } from './models/OperatorCollection_NOT_EQUAL_TO';
export { OperatorCollection_STARTS_WITH } from './models/OperatorCollection_STARTS_WITH';
export type { operatorCondition } from './models/operatorCondition';
export type { operatorConditionDefaultCollection } from './models/operatorConditionDefaultCollection';
export type { Order } from './models/Order';
export type { OrderDisputeStatus } from './models/OrderDisputeStatus';
export type { OrderInformationFraudType } from './models/OrderInformationFraudType';
export type { OrderItem } from './models/OrderItem';
export type { OrderItemDto } from './models/OrderItemDto';
export type { OrderItemTrackingDto } from './models/OrderItemTrackingDto';
export type { OrderRefund } from './models/OrderRefund';
export type { OrderStatus } from './models/OrderStatus';
export { OrderTrackingEmailStatusDto } from './models/OrderTrackingEmailStatusDto';
export { OrderTrackingRecoveredStatusDto } from './models/OrderTrackingRecoveredStatusDto';
export { OtpType } from './models/OtpType';
export { PageNameType } from './models/PageNameType';
export type { Partial_CreateSubscriptionFeatureDto_ } from './models/Partial_CreateSubscriptionFeatureDto_';
export type { PaymentDirectApiDto } from './models/PaymentDirectApiDto';
export { paymentIntegrationTypeEnum_DIRECT_API } from './models/paymentIntegrationTypeEnum_DIRECT_API';
export { paymentIntegrationTypeEnum_ONBOARDING } from './models/paymentIntegrationTypeEnum_ONBOARDING';
export type { PaymentMethodIdDto } from './models/PaymentMethodIdDto';
export type { PaymentOnboarding } from './models/PaymentOnboarding';
export type { PaymentOnboardingDto } from './models/PaymentOnboardingDto';
export type { PaymentType } from './models/PaymentType';
export type { PaymentTypeCustom } from './models/PaymentTypeCustom';
export type { PayPlatformTransactionFeeDebtDto } from './models/PayPlatformTransactionFeeDebtDto';
export type { PayPlatformTransactionFeeDto } from './models/PayPlatformTransactionFeeDto';
export type { PaySubscriptionInvoiceDto } from './models/PaySubscriptionInvoiceDto';
export type { PercentageCostInfo } from './models/PercentageCostInfo';
export { Period } from './models/Period';
export { Permission } from './models/Permission';
export type { PhoneWithCountryCode } from './models/PhoneWithCountryCode';
export type { PhotoDto } from './models/PhotoDto';
export type { PingPongAccount } from './models/PingPongAccount';
export { PingPongFeePayer } from './models/PingPongFeePayer';
export { PingPongTransactionStatus } from './models/PingPongTransactionStatus';
export { PingPongTransactionType } from './models/PingPongTransactionType';
export { PlacementBoostSaleEnum } from './models/PlacementBoostSaleEnum';
export type { PlatformProduct } from './models/PlatformProduct';
export type { PlatformProductStore } from './models/PlatformProductStore';
export type { PlatformVariant } from './models/PlatformVariant';
export type { PlatformVariantDto } from './models/PlatformVariantDto';
export type { PreviewPayoutRequestDto } from './models/PreviewPayoutRequestDto';
export type { PriceConditionDto } from './models/PriceConditionDto';
export type { Prisma_NullableDateTimeFieldUpdateOperationsInput } from './models/Prisma_NullableDateTimeFieldUpdateOperationsInput';
export type { PrismaJson_AsyncTaskResult } from './models/PrismaJson_AsyncTaskResult';
export type { PrismaJson_AvailableSet } from './models/PrismaJson_AvailableSet';
export type { PrismaJson_bankInfo } from './models/PrismaJson_bankInfo';
export type { PrismaJson_BillingInfo } from './models/PrismaJson_BillingInfo';
export type { PrismaJson_Colors } from './models/PrismaJson_Colors';
export type { PrismaJson_ConditionCollection } from './models/PrismaJson_ConditionCollection';
export type { PrismaJson_CostInfo } from './models/PrismaJson_CostInfo';
export type { PrismaJson_CountryInformation } from './models/PrismaJson_CountryInformation';
export type { PrismaJson_CouponCombination } from './models/PrismaJson_CouponCombination';
export type { PrismaJson_CreateComboItems } from './models/PrismaJson_CreateComboItems';
export type { PrismaJson_CreateOrderItems } from './models/PrismaJson_CreateOrderItems';
export type { PrismaJson_CustomVariantOptions } from './models/PrismaJson_CustomVariantOptions';
export type { PrismaJson_CustomVariantOptionValues } from './models/PrismaJson_CustomVariantOptionValues';
export type { PrismaJson_DataInformationsOnboarding } from './models/PrismaJson_DataInformationsOnboarding';
export type { PrismaJson_DiscountBoostSale } from './models/PrismaJson_DiscountBoostSale';
export type { PrismaJson_DomainContactInfo } from './models/PrismaJson_DomainContactInfo';
export type { PrismaJson_FirebaseDeviceToken } from './models/PrismaJson_FirebaseDeviceToken';
export type { PrismaJson_HistoryRequestPayout } from './models/PrismaJson_HistoryRequestPayout';
export type { PrismaJson_HistoryTrackingDetail } from './models/PrismaJson_HistoryTrackingDetail';
export type { PrismaJson_HoldSetting } from './models/PrismaJson_HoldSetting';
export type { PrismaJson_MarginInfo } from './models/PrismaJson_MarginInfo';
export type { PrismaJson_OnboardingProducts } from './models/PrismaJson_OnboardingProducts';
export type { PrismaJson_OrderItemInformation } from './models/PrismaJson_OrderItemInformation';
export type { PrismaJson_Permissions } from './models/PrismaJson_Permissions';
export type { PrismaJson_Photos } from './models/PrismaJson_Photos';
export type { PrismaJson_PingPongMoney } from './models/PrismaJson_PingPongMoney';
export type { PrismaJson_PingPongServiceCharge } from './models/PrismaJson_PingPongServiceCharge';
export type { PrismaJson_PingPongTransaction } from './models/PrismaJson_PingPongTransaction';
export type { PrismaJson_PingPongTrialCalculation } from './models/PrismaJson_PingPongTrialCalculation';
export type { PrismaJson_PlacementBoostSaleType } from './models/PrismaJson_PlacementBoostSaleType';
export type { PrismaJson_PlatformCostInfo } from './models/PrismaJson_PlatformCostInfo';
export type { PrismaJson_ProductDiscountItems } from './models/PrismaJson_ProductDiscountItems';
export type { PrismaJson_ProductHistoryVariants } from './models/PrismaJson_ProductHistoryVariants';
export type { PrismaJson_ProductRequirementItems } from './models/PrismaJson_ProductRequirementItems';
export type { PrismaJson_RefundOrderItems } from './models/PrismaJson_RefundOrderItems';
export type { PrismaJson_RequestSourcingHistory } from './models/PrismaJson_RequestSourcingHistory';
export type { PrismaJson_SettingPayoutRequestDay } from './models/PrismaJson_SettingPayoutRequestDay';
export type { PrismaJson_SettingPayoutRequestTime } from './models/PrismaJson_SettingPayoutRequestTime';
export type { PrismaJson_SyncBalanceAmount } from './models/PrismaJson_SyncBalanceAmount';
export type { PrismaJson_ThemeNodes } from './models/PrismaJson_ThemeNodes';
export type { PrismaJson_ThemeSetting } from './models/PrismaJson_ThemeSetting';
export type { PrismaJson_ThemeStyle } from './models/PrismaJson_ThemeStyle';
export type { PrismaJson_Timezone } from './models/PrismaJson_Timezone';
export type { PrismaJson_TransactionDetails } from './models/PrismaJson_TransactionDetails';
export { PrismaJson_TransactionPaymentMethod } from './models/PrismaJson_TransactionPaymentMethod';
export type { PrismaJson_TypeOfFraudService } from './models/PrismaJson_TypeOfFraudService';
export type { PrismaJson_UnavailableBalance } from './models/PrismaJson_UnavailableBalance';
export type { PrismaJson_UpgradeSubscriptionPlan } from './models/PrismaJson_UpgradeSubscriptionPlan';
export type { PrismaJson_VariantComboItems } from './models/PrismaJson_VariantComboItems';
export type { PrismaJson_VariantOptions } from './models/PrismaJson_VariantOptions';
export type { PrismaJson_VariantOptionValues } from './models/PrismaJson_VariantOptionValues';
export type { PrismaJson_VariantPlatformSnapshot } from './models/PrismaJson_VariantPlatformSnapshot';
export type { Product } from './models/Product';
export type { ProductListType } from './models/ProductListType';
export type { ProductPerformance } from './models/ProductPerformance';
export type { ProductVariant } from './models/ProductVariant';
export type { ReconnectPaymentDto } from './models/ReconnectPaymentDto';
export type { Record_Permission_or_SuperAdminPermission_or_SellerPermission_or_FulfillmentPermissions_boolean_or_undefined_ } from './models/Record_Permission_or_SuperAdminPermission_or_SellerPermission_or_FulfillmentPermissions_boolean_or_undefined_';
export type { Record_string_any_ } from './models/Record_string_any_';
export { ReferralStoreType } from './models/ReferralStoreType';
export type { RefundOrderDto } from './models/RefundOrderDto';
export { RefundType } from './models/RefundType';
export type { RegionalShippingFee } from './models/RegionalShippingFee';
export type { RegionalShippingFeeDto } from './models/RegionalShippingFeeDto';
export type { RejectRequestSourcingDto } from './models/RejectRequestSourcingDto';
export { RelatedProductType } from './models/RelatedProductType';
export type { RenewDomainDto } from './models/RenewDomainDto';
export type { RequestPayout } from './models/RequestPayout';
export type { RequestPayoutStatus } from './models/RequestPayoutStatus';
export type { RequestSourcing } from './models/RequestSourcing';
export type { RequestSourcingStatus } from './models/RequestSourcingStatus';
export type { ResponseGetStoreByPingpong } from './models/ResponseGetStoreByPingpong';
export type { ResponseGetUser } from './models/ResponseGetUser';
export type { ResponsePaginateCursor_StoreTrackingPerformance_ } from './models/ResponsePaginateCursor_StoreTrackingPerformance_';
export type { ResponseStoreAddPingpong } from './models/ResponseStoreAddPingpong';
export type { ResponseTrackingPie } from './models/ResponseTrackingPie';
export type { Review } from './models/Review';
export type { SaleInfoResponsive } from './models/SaleInfoResponsive';
export { SalePerformanceResponsive } from './models/SalePerformanceResponsive';
export type { SaleStatus } from './models/SaleStatus';
export type { SaleUserTrackingType } from './models/SaleUserTrackingType';
export type { SearchBettaSupSellersParams } from './models/SearchBettaSupSellersParams';
export type { SearchBettaSupSellersResponse } from './models/SearchBettaSupSellersResponse';
export type { SearchFulfillmentDto } from './models/SearchFulfillmentDto';
export type { SearchSaleDto } from './models/SearchSaleDto';
export type { SearchSuperAdminDto } from './models/SearchSuperAdminDto';
export { SellerPermission } from './models/SellerPermission';
export type { SendEmailToListStoreDto } from './models/SendEmailToListStoreDto';
export { SendEmailToListStoreStatus } from './models/SendEmailToListStoreStatus';
export type { SendOtpAddPingpongAccountDto } from './models/SendOtpAddPingpongAccountDto';
export type { SendOtpRequestPayoutDto } from './models/SendOtpRequestPayoutDto';
export type { SettingPayoutRequestDto } from './models/SettingPayoutRequestDto';
export type { SnapChatPixel } from './models/SnapChatPixel';
export { sortTrackingPerformance } from './models/sortTrackingPerformance';
export { StatisticsDisplayType } from './models/StatisticsDisplayType';
export type { StatisticsOverviewAbandonedCheckout } from './models/StatisticsOverviewAbandonedCheckout';
export type { StatisticsOverviewConversionValue } from './models/StatisticsOverviewConversionValue';
export { statusRequestPayout } from './models/statusRequestPayout';
export type { Store } from './models/Store';
export type { StoreData } from './models/StoreData';
export type { StoreLogType } from './models/StoreLogType';
export type { StorePerformance } from './models/StorePerformance';
export type { StoreProductPerformanceResp } from './models/StoreProductPerformanceResp';
export type { StoreProductProfit } from './models/StoreProductProfit';
export { StoreResourceAccess } from './models/StoreResourceAccess';
export type { StoreRevenueOverTime } from './models/StoreRevenueOverTime';
export type { StoreRole } from './models/StoreRole';
export type { StoreStatus } from './models/StoreStatus';
export type { StoreTrackingPerformance } from './models/StoreTrackingPerformance';
export type { StoreType } from './models/StoreType';
export type { StoreUser } from './models/StoreUser';
export type { StripeCardPaymentInfo } from './models/StripeCardPaymentInfo';
export type { SubscribeToNewSubscriptionPlanDto } from './models/SubscribeToNewSubscriptionPlanDto';
export type { SubscribeTopicDto } from './models/SubscribeTopicDto';
export type { SubscriptionInterval } from './models/SubscriptionInterval';
export type { SuggestionResponseDto } from './models/SuggestionResponseDto';
export { SuperAdminPermission } from './models/SuperAdminPermission';
export type { SwitchPlatformProductSyncDto } from './models/SwitchPlatformProductSyncDto';
export type { SyncStatusRequestProductDto } from './models/SyncStatusRequestProductDto';
export type { Tag } from './models/Tag';
export type { TagConditionDto } from './models/TagConditionDto';
export type { TaxProviderItem } from './models/TaxProviderItem';
export type { TaxProviderPaymentItem } from './models/TaxProviderPaymentItem';
export type { TaxQueryInformationDto } from './models/TaxQueryInformationDto';
export type { Theme } from './models/Theme';
export type { ThemeLibrary } from './models/ThemeLibrary';
export type { ThemePageType } from './models/ThemePageType';
export type { ThemePageWithDetails } from './models/ThemePageWithDetails';
export type { ThemeWithDetails } from './models/ThemeWithDetails';
export type { TiktokPixel } from './models/TiktokPixel';
export { TimeEmailMarketingUnit } from './models/TimeEmailMarketingUnit';
export { TimezoneDto } from './models/TimezoneDto';
export type { TopProductByOrder } from './models/TopProductByOrder';
export type { TopStoreByRevenue } from './models/TopStoreByRevenue';
export type { TopUpWalletDto } from './models/TopUpWalletDto';
export type { Tracking } from './models/Tracking';
export type { TrackingReferralDto } from './models/TrackingReferralDto';
export type { Transaction } from './models/Transaction';
export type { TransactionStatus } from './models/TransactionStatus';
export { TypeFulfillmentPrice } from './models/TypeFulfillmentPrice';
export { TypeOfFraud } from './models/TypeOfFraud';
export type { UnsubscribeEmailMarketingDto } from './models/UnsubscribeEmailMarketingDto';
export type { UnsubscribeTopicDto } from './models/UnsubscribeTopicDto';
export type { UpdateActiveStatusAutomationEmailMarketingDto } from './models/UpdateActiveStatusAutomationEmailMarketingDto';
export type { UpdateAssignedProductsForThemePageDto } from './models/UpdateAssignedProductsForThemePageDto';
export type { UpdateAutomationEmailMarketingDto } from './models/UpdateAutomationEmailMarketingDto';
export type { UpdateAutomationEmailMarketingOptions } from './models/UpdateAutomationEmailMarketingOptions';
export type { UpdateBankAccountDto } from './models/UpdateBankAccountDto';
export type { UpdateCampaignDto } from './models/UpdateCampaignDto';
export type { UpdateCollectionDefaultDto } from './models/UpdateCollectionDefaultDto';
export type { UpdateCollectionDefaultStatusDto } from './models/UpdateCollectionDefaultStatusDto';
export type { UpdateCollectionDto } from './models/UpdateCollectionDto';
export type { UpdateCollectionStatusDto } from './models/UpdateCollectionStatusDto';
export type { UpdateComboDto } from './models/UpdateComboDto';
export type { UpdateCombosDto } from './models/UpdateCombosDto';
export type { UpdateComboStatusDto } from './models/UpdateComboStatusDto';
export type { UpdateConfigTaxProviderDto } from './models/UpdateConfigTaxProviderDto';
export type { UpdateCouponDto } from './models/UpdateCouponDto';
export type { UpdateCouponStatusDto } from './models/UpdateCouponStatusDto';
export type { UpdateCrossSellStatusDto } from './models/UpdateCrossSellStatusDto';
export type { UpdateCurrencyDto } from './models/UpdateCurrencyDto';
export type { UpdateDiscountDto } from './models/UpdateDiscountDto';
export type { UpdateFbPixelDto } from './models/UpdateFbPixelDto';
export type { UpdateFulfillmentAgencyDto } from './models/UpdateFulfillmentAgencyDto';
export type { UpdateFulfillmentAgencyStatusDto } from './models/UpdateFulfillmentAgencyStatusDto';
export type { UpdateFulFillmentStatusError } from './models/UpdateFulFillmentStatusError';
export type { UpdateFulFillmentStatusResp } from './models/UpdateFulFillmentStatusResp';
export type { UpdateGADto } from './models/UpdateGADto';
export type { UpdateGroupPlatformVariantsDto } from './models/UpdateGroupPlatformVariantsDto';
export type { UpdateGTMDto } from './models/UpdateGTMDto';
export type { UpdateImportedPlatformProductDto } from './models/UpdateImportedPlatformProductDto';
export type { UpdateManyStorePaymentMethodDto } from './models/UpdateManyStorePaymentMethodDto';
export type { UpdateNameTaxProviderDto } from './models/UpdateNameTaxProviderDto';
export type { UpdateNotificationDto } from './models/UpdateNotificationDto';
export type { UpdateOrderDto } from './models/UpdateOrderDto';
export type { UpdateOrderRefundDto } from './models/UpdateOrderRefundDto';
export type { UpdateOrderRefundHistoryDto } from './models/UpdateOrderRefundHistoryDto';
export type { UpdateOrderStatusDto } from './models/UpdateOrderStatusDto';
export type { UpdateOrderTrackingDto } from './models/UpdateOrderTrackingDto';
export type { UpdatePaymentDto } from './models/UpdatePaymentDto';
export type { UpdatePingPongAccountDto } from './models/UpdatePingPongAccountDto';
export type { UpdatePlatformProductDto } from './models/UpdatePlatformProductDto';
export type { UpdatePlatformProductStatusDto } from './models/UpdatePlatformProductStatusDto';
export type { UpdatePlatformProductStatusesDto } from './models/UpdatePlatformProductStatusesDto';
export type { UpdatePlatformProductVariantDto } from './models/UpdatePlatformProductVariantDto';
export type { UpdatePlatformVariantDto } from './models/UpdatePlatformVariantDto';
export type { UpdatePlatformVariantsDto } from './models/UpdatePlatformVariantsDto';
export type { UpdatePlatformVariantStatusDto } from './models/UpdatePlatformVariantStatusDto';
export type { UpdateProductDto } from './models/UpdateProductDto';
export type { UpdateProductStatusDto } from './models/UpdateProductStatusDto';
export type { UpdateProductStatusesDto } from './models/UpdateProductStatusesDto';
export type { UpdateRequestPayoutDto } from './models/UpdateRequestPayoutDto';
export type { UpdateRequestSourcingDto } from './models/UpdateRequestSourcingDto';
export type { UpdateRequestStatusDto } from './models/UpdateRequestStatusDto';
export type { UpdateReviewDto } from './models/UpdateReviewDto';
export type { UpdateSettingDto } from './models/UpdateSettingDto';
export type { UpdateSnapChatPixelDto } from './models/UpdateSnapChatPixelDto';
export type { UpdateStaffDto } from './models/UpdateStaffDto';
export type { UpdateStoreConversionRateDto } from './models/UpdateStoreConversionRateDto';
export type { UpdateStoreDto } from './models/UpdateStoreDto';
export type { UpdateStorePaymentMethodDto } from './models/UpdateStorePaymentMethodDto';
export type { UpdateStoreStaffDto } from './models/UpdateStoreStaffDto';
export type { UpdateStoreStatusDto } from './models/UpdateStoreStatusDto';
export type { UpdateTemplateDto } from './models/UpdateTemplateDto';
export type { UpdateThemeDto } from './models/UpdateThemeDto';
export type { UpdateThemeLibraryDto } from './models/UpdateThemeLibraryDto';
export type { UpdateTiktokPixelDto } from './models/UpdateTiktokPixelDto';
export type { UpdateUserDto } from './models/UpdateUserDto';
export type { UpdateVariantDto } from './models/UpdateVariantDto';
export type { UpdateVariantsDto } from './models/UpdateVariantsDto';
export type { UpdateVariantStatusDto } from './models/UpdateVariantStatusDto';
export type { UpsertRevenueLimitDto } from './models/UpsertRevenueLimitDto';
export type { URLDto } from './models/URLDto';
export type { User } from './models/User';
export type { UserRole } from './models/UserRole';
export { UTMSourceSchema } from './models/UTMSourceSchema';
export type { ValidateQuadernoDto } from './models/ValidateQuadernoDto';
export type { VariantCombo } from './models/VariantCombo';
export type { VariantDto } from './models/VariantDto';
export type { VariantOption } from './models/VariantOption';
export type { VariantOptions } from './models/VariantOptions';
export type { VerifyOtpAddPingpongAccountDto } from './models/VerifyOtpAddPingpongAccountDto';
export type { Wallet } from './models/Wallet';
export { Week } from './models/Week';
export type { WithdrawWalletDto } from './models/WithdrawWalletDto';

export { AsyncTaskService } from './services/AsyncTaskService';
export { AuthService } from './services/AuthService';
export { FulfillmentAgencyService } from './services/FulfillmentAgencyService';
export { FulfillmentPlatformIntegrationService } from './services/FulfillmentPlatformIntegrationService';
export { MarketingService } from './services/MarketingService';
export { MarketingEmailService } from './services/MarketingEmailService';
export { NotificationService } from './services/NotificationService';
export { PerformanceService } from './services/PerformanceService';
export { PermissionService } from './services/PermissionService';
export { ReferralService } from './services/ReferralService';
export { SaleService } from './services/SaleService';
export { SettingService } from './services/SettingService';
export { StatisticsService } from './services/StatisticsService';
export { SubscriptionService } from './services/SubscriptionService';
export { UploadService } from './services/UploadService';
export { UserService } from './services/UserService';
