"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.RefundType = exports.PlacementCrossSellEnum = exports.PhotoDesign = exports.Period = exports.PaymentType = exports.PaymentMethodType = exports.OrderStatus = exports.OrderDisputeStatus = exports.OperatorCollection_STARTS_WITH = exports.OperatorCollection_NOT_EQUAL_TO = exports.OperatorCollection_NOT_CONTAIN = exports.OperatorCollection_LESS_TO = exports.OperatorCollection_GREATER_TO = exports.OperatorCollection_EQUAL_TO = exports.OperatorCollection_ENDS_WITH = exports.OperatorCollection_CONTAIN = exports.NotificationType = exports.LogoSize = exports.LayoutCategory = exports.GetAllTemplateDto = exports.FulfillmentStatus = exports.FulfillmentAgencyStatus = exports.FulfillmentAgencyRole = exports.FileType = exports.EventOrderFraud = exports.EnvironmentType = exports.ElementType = exports.DiscountCrossSellType = exports.CustomDomainStatus = exports.CurrencyType = exports.CurrencyCode = exports.CrossSellType = exports.CrossSellTriggerType = exports.CostCalculationMethod = exports.CombineOperator = exports.CollectionType = exports.CollectionStatus = exports.CollectionField_tag = exports.CollectionField_price = exports.CollectionField_name = exports.AsyncTaskType = exports.AsyncTaskStatus = exports.ActiveDetection = exports.ActionOrderFraud = exports.OpenAPI = exports.CancelError = exports.CancelablePromise = exports.BaseHttpRequest = exports.ApiError = exports.ClientApi = void 0;
exports.UserService = exports.UploadService = exports.PerformanceService = exports.NotificationService = exports.FulfillmentAgencyService = exports.AuthService = exports.AsyncTaskService = exports.UserRole = exports.TypeOfFraud = exports.typeFulfillmentPrice = exports.TransactionType = exports.TransactionStatus = exports.TimezoneDto = exports.SyncTrackingStatus = exports.StoreType = exports.StoreStatus = exports.StoreRole = exports.statusRequestPayout = exports.RequestSourcingStatus = exports.RequestPayoutStatus = void 0;
/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
var ClientApi_1 = require("./ClientApi");
Object.defineProperty(exports, "ClientApi", { enumerable: true, get: function () { return ClientApi_1.ClientApi; } });
var ApiError_1 = require("./core/ApiError");
Object.defineProperty(exports, "ApiError", { enumerable: true, get: function () { return ApiError_1.ApiError; } });
var BaseHttpRequest_1 = require("./core/BaseHttpRequest");
Object.defineProperty(exports, "BaseHttpRequest", { enumerable: true, get: function () { return BaseHttpRequest_1.BaseHttpRequest; } });
var CancelablePromise_1 = require("./core/CancelablePromise");
Object.defineProperty(exports, "CancelablePromise", { enumerable: true, get: function () { return CancelablePromise_1.CancelablePromise; } });
Object.defineProperty(exports, "CancelError", { enumerable: true, get: function () { return CancelablePromise_1.CancelError; } });
var OpenAPI_1 = require("./core/OpenAPI");
Object.defineProperty(exports, "OpenAPI", { enumerable: true, get: function () { return OpenAPI_1.OpenAPI; } });
var ActionOrderFraud_1 = require("./models/ActionOrderFraud");
Object.defineProperty(exports, "ActionOrderFraud", { enumerable: true, get: function () { return ActionOrderFraud_1.ActionOrderFraud; } });
var ActiveDetection_1 = require("./models/ActiveDetection");
Object.defineProperty(exports, "ActiveDetection", { enumerable: true, get: function () { return ActiveDetection_1.ActiveDetection; } });
var AsyncTaskStatus_1 = require("./models/AsyncTaskStatus");
Object.defineProperty(exports, "AsyncTaskStatus", { enumerable: true, get: function () { return AsyncTaskStatus_1.AsyncTaskStatus; } });
var AsyncTaskType_1 = require("./models/AsyncTaskType");
Object.defineProperty(exports, "AsyncTaskType", { enumerable: true, get: function () { return AsyncTaskType_1.AsyncTaskType; } });
var CollectionField_name_1 = require("./models/CollectionField_name");
Object.defineProperty(exports, "CollectionField_name", { enumerable: true, get: function () { return CollectionField_name_1.CollectionField_name; } });
var CollectionField_price_1 = require("./models/CollectionField_price");
Object.defineProperty(exports, "CollectionField_price", { enumerable: true, get: function () { return CollectionField_price_1.CollectionField_price; } });
var CollectionField_tag_1 = require("./models/CollectionField_tag");
Object.defineProperty(exports, "CollectionField_tag", { enumerable: true, get: function () { return CollectionField_tag_1.CollectionField_tag; } });
var CollectionStatus_1 = require("./models/CollectionStatus");
Object.defineProperty(exports, "CollectionStatus", { enumerable: true, get: function () { return CollectionStatus_1.CollectionStatus; } });
var CollectionType_1 = require("./models/CollectionType");
Object.defineProperty(exports, "CollectionType", { enumerable: true, get: function () { return CollectionType_1.CollectionType; } });
var CombineOperator_1 = require("./models/CombineOperator");
Object.defineProperty(exports, "CombineOperator", { enumerable: true, get: function () { return CombineOperator_1.CombineOperator; } });
var CostCalculationMethod_1 = require("./models/CostCalculationMethod");
Object.defineProperty(exports, "CostCalculationMethod", { enumerable: true, get: function () { return CostCalculationMethod_1.CostCalculationMethod; } });
var CrossSellTriggerType_1 = require("./models/CrossSellTriggerType");
Object.defineProperty(exports, "CrossSellTriggerType", { enumerable: true, get: function () { return CrossSellTriggerType_1.CrossSellTriggerType; } });
var CrossSellType_1 = require("./models/CrossSellType");
Object.defineProperty(exports, "CrossSellType", { enumerable: true, get: function () { return CrossSellType_1.CrossSellType; } });
var CurrencyCode_1 = require("./models/CurrencyCode");
Object.defineProperty(exports, "CurrencyCode", { enumerable: true, get: function () { return CurrencyCode_1.CurrencyCode; } });
var CurrencyType_1 = require("./models/CurrencyType");
Object.defineProperty(exports, "CurrencyType", { enumerable: true, get: function () { return CurrencyType_1.CurrencyType; } });
var CustomDomainStatus_1 = require("./models/CustomDomainStatus");
Object.defineProperty(exports, "CustomDomainStatus", { enumerable: true, get: function () { return CustomDomainStatus_1.CustomDomainStatus; } });
var DiscountCrossSellType_1 = require("./models/DiscountCrossSellType");
Object.defineProperty(exports, "DiscountCrossSellType", { enumerable: true, get: function () { return DiscountCrossSellType_1.DiscountCrossSellType; } });
var ElementType_1 = require("./models/ElementType");
Object.defineProperty(exports, "ElementType", { enumerable: true, get: function () { return ElementType_1.ElementType; } });
var EnvironmentType_1 = require("./models/EnvironmentType");
Object.defineProperty(exports, "EnvironmentType", { enumerable: true, get: function () { return EnvironmentType_1.EnvironmentType; } });
var EventOrderFraud_1 = require("./models/EventOrderFraud");
Object.defineProperty(exports, "EventOrderFraud", { enumerable: true, get: function () { return EventOrderFraud_1.EventOrderFraud; } });
var FileType_1 = require("./models/FileType");
Object.defineProperty(exports, "FileType", { enumerable: true, get: function () { return FileType_1.FileType; } });
var FulfillmentAgencyRole_1 = require("./models/FulfillmentAgencyRole");
Object.defineProperty(exports, "FulfillmentAgencyRole", { enumerable: true, get: function () { return FulfillmentAgencyRole_1.FulfillmentAgencyRole; } });
var FulfillmentAgencyStatus_1 = require("./models/FulfillmentAgencyStatus");
Object.defineProperty(exports, "FulfillmentAgencyStatus", { enumerable: true, get: function () { return FulfillmentAgencyStatus_1.FulfillmentAgencyStatus; } });
var FulfillmentStatus_1 = require("./models/FulfillmentStatus");
Object.defineProperty(exports, "FulfillmentStatus", { enumerable: true, get: function () { return FulfillmentStatus_1.FulfillmentStatus; } });
var GetAllTemplateDto_1 = require("./models/GetAllTemplateDto");
Object.defineProperty(exports, "GetAllTemplateDto", { enumerable: true, get: function () { return GetAllTemplateDto_1.GetAllTemplateDto; } });
var LayoutCategory_1 = require("./models/LayoutCategory");
Object.defineProperty(exports, "LayoutCategory", { enumerable: true, get: function () { return LayoutCategory_1.LayoutCategory; } });
var LogoSize_1 = require("./models/LogoSize");
Object.defineProperty(exports, "LogoSize", { enumerable: true, get: function () { return LogoSize_1.LogoSize; } });
var NotificationType_1 = require("./models/NotificationType");
Object.defineProperty(exports, "NotificationType", { enumerable: true, get: function () { return NotificationType_1.NotificationType; } });
var OperatorCollection_CONTAIN_1 = require("./models/OperatorCollection_CONTAIN");
Object.defineProperty(exports, "OperatorCollection_CONTAIN", { enumerable: true, get: function () { return OperatorCollection_CONTAIN_1.OperatorCollection_CONTAIN; } });
var OperatorCollection_ENDS_WITH_1 = require("./models/OperatorCollection_ENDS_WITH");
Object.defineProperty(exports, "OperatorCollection_ENDS_WITH", { enumerable: true, get: function () { return OperatorCollection_ENDS_WITH_1.OperatorCollection_ENDS_WITH; } });
var OperatorCollection_EQUAL_TO_1 = require("./models/OperatorCollection_EQUAL_TO");
Object.defineProperty(exports, "OperatorCollection_EQUAL_TO", { enumerable: true, get: function () { return OperatorCollection_EQUAL_TO_1.OperatorCollection_EQUAL_TO; } });
var OperatorCollection_GREATER_TO_1 = require("./models/OperatorCollection_GREATER_TO");
Object.defineProperty(exports, "OperatorCollection_GREATER_TO", { enumerable: true, get: function () { return OperatorCollection_GREATER_TO_1.OperatorCollection_GREATER_TO; } });
var OperatorCollection_LESS_TO_1 = require("./models/OperatorCollection_LESS_TO");
Object.defineProperty(exports, "OperatorCollection_LESS_TO", { enumerable: true, get: function () { return OperatorCollection_LESS_TO_1.OperatorCollection_LESS_TO; } });
var OperatorCollection_NOT_CONTAIN_1 = require("./models/OperatorCollection_NOT_CONTAIN");
Object.defineProperty(exports, "OperatorCollection_NOT_CONTAIN", { enumerable: true, get: function () { return OperatorCollection_NOT_CONTAIN_1.OperatorCollection_NOT_CONTAIN; } });
var OperatorCollection_NOT_EQUAL_TO_1 = require("./models/OperatorCollection_NOT_EQUAL_TO");
Object.defineProperty(exports, "OperatorCollection_NOT_EQUAL_TO", { enumerable: true, get: function () { return OperatorCollection_NOT_EQUAL_TO_1.OperatorCollection_NOT_EQUAL_TO; } });
var OperatorCollection_STARTS_WITH_1 = require("./models/OperatorCollection_STARTS_WITH");
Object.defineProperty(exports, "OperatorCollection_STARTS_WITH", { enumerable: true, get: function () { return OperatorCollection_STARTS_WITH_1.OperatorCollection_STARTS_WITH; } });
var OrderDisputeStatus_1 = require("./models/OrderDisputeStatus");
Object.defineProperty(exports, "OrderDisputeStatus", { enumerable: true, get: function () { return OrderDisputeStatus_1.OrderDisputeStatus; } });
var OrderStatus_1 = require("./models/OrderStatus");
Object.defineProperty(exports, "OrderStatus", { enumerable: true, get: function () { return OrderStatus_1.OrderStatus; } });
var PaymentMethodType_1 = require("./models/PaymentMethodType");
Object.defineProperty(exports, "PaymentMethodType", { enumerable: true, get: function () { return PaymentMethodType_1.PaymentMethodType; } });
var PaymentType_1 = require("./models/PaymentType");
Object.defineProperty(exports, "PaymentType", { enumerable: true, get: function () { return PaymentType_1.PaymentType; } });
var Period_1 = require("./models/Period");
Object.defineProperty(exports, "Period", { enumerable: true, get: function () { return Period_1.Period; } });
var PhotoDesign_1 = require("./models/PhotoDesign");
Object.defineProperty(exports, "PhotoDesign", { enumerable: true, get: function () { return PhotoDesign_1.PhotoDesign; } });
var PlacementCrossSellEnum_1 = require("./models/PlacementCrossSellEnum");
Object.defineProperty(exports, "PlacementCrossSellEnum", { enumerable: true, get: function () { return PlacementCrossSellEnum_1.PlacementCrossSellEnum; } });
var RefundType_1 = require("./models/RefundType");
Object.defineProperty(exports, "RefundType", { enumerable: true, get: function () { return RefundType_1.RefundType; } });
var RequestPayoutStatus_1 = require("./models/RequestPayoutStatus");
Object.defineProperty(exports, "RequestPayoutStatus", { enumerable: true, get: function () { return RequestPayoutStatus_1.RequestPayoutStatus; } });
var RequestSourcingStatus_1 = require("./models/RequestSourcingStatus");
Object.defineProperty(exports, "RequestSourcingStatus", { enumerable: true, get: function () { return RequestSourcingStatus_1.RequestSourcingStatus; } });
var statusRequestPayout_1 = require("./models/statusRequestPayout");
Object.defineProperty(exports, "statusRequestPayout", { enumerable: true, get: function () { return statusRequestPayout_1.statusRequestPayout; } });
var StoreRole_1 = require("./models/StoreRole");
Object.defineProperty(exports, "StoreRole", { enumerable: true, get: function () { return StoreRole_1.StoreRole; } });
var StoreStatus_1 = require("./models/StoreStatus");
Object.defineProperty(exports, "StoreStatus", { enumerable: true, get: function () { return StoreStatus_1.StoreStatus; } });
var StoreType_1 = require("./models/StoreType");
Object.defineProperty(exports, "StoreType", { enumerable: true, get: function () { return StoreType_1.StoreType; } });
var SyncTrackingStatus_1 = require("./models/SyncTrackingStatus");
Object.defineProperty(exports, "SyncTrackingStatus", { enumerable: true, get: function () { return SyncTrackingStatus_1.SyncTrackingStatus; } });
var TimezoneDto_1 = require("./models/TimezoneDto");
Object.defineProperty(exports, "TimezoneDto", { enumerable: true, get: function () { return TimezoneDto_1.TimezoneDto; } });
var TransactionStatus_1 = require("./models/TransactionStatus");
Object.defineProperty(exports, "TransactionStatus", { enumerable: true, get: function () { return TransactionStatus_1.TransactionStatus; } });
var TransactionType_1 = require("./models/TransactionType");
Object.defineProperty(exports, "TransactionType", { enumerable: true, get: function () { return TransactionType_1.TransactionType; } });
var typeFulfillmentPrice_1 = require("./models/typeFulfillmentPrice");
Object.defineProperty(exports, "typeFulfillmentPrice", { enumerable: true, get: function () { return typeFulfillmentPrice_1.typeFulfillmentPrice; } });
var TypeOfFraud_1 = require("./models/TypeOfFraud");
Object.defineProperty(exports, "TypeOfFraud", { enumerable: true, get: function () { return TypeOfFraud_1.TypeOfFraud; } });
var UserRole_1 = require("./models/UserRole");
Object.defineProperty(exports, "UserRole", { enumerable: true, get: function () { return UserRole_1.UserRole; } });
var AsyncTaskService_1 = require("./services/AsyncTaskService");
Object.defineProperty(exports, "AsyncTaskService", { enumerable: true, get: function () { return AsyncTaskService_1.AsyncTaskService; } });
var AuthService_1 = require("./services/AuthService");
Object.defineProperty(exports, "AuthService", { enumerable: true, get: function () { return AuthService_1.AuthService; } });
var FulfillmentAgencyService_1 = require("./services/FulfillmentAgencyService");
Object.defineProperty(exports, "FulfillmentAgencyService", { enumerable: true, get: function () { return FulfillmentAgencyService_1.FulfillmentAgencyService; } });
var NotificationService_1 = require("./services/NotificationService");
Object.defineProperty(exports, "NotificationService", { enumerable: true, get: function () { return NotificationService_1.NotificationService; } });
var PerformanceService_1 = require("./services/PerformanceService");
Object.defineProperty(exports, "PerformanceService", { enumerable: true, get: function () { return PerformanceService_1.PerformanceService; } });
var UploadService_1 = require("./services/UploadService");
Object.defineProperty(exports, "UploadService", { enumerable: true, get: function () { return UploadService_1.UploadService; } });
var UserService_1 = require("./services/UserService");
Object.defineProperty(exports, "UserService", { enumerable: true, get: function () { return UserService_1.UserService; } });
