"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports._36_Enums_SaleUserTrackingType = exports._36_Enums_SaleStatus = exports._36_Enums_RolePermissionType = exports._36_Enums_RequestSourcingStatus = exports._36_Enums_RequestPayoutStatus = exports._36_Enums_PPCPVettingStatus = exports._36_Enums_PingPongAuthStatus = exports._36_Enums_PaymentType = exports._36_Enums_PaymentMethodType = exports._36_Enums_PaymentIntegrationType = exports._36_Enums_OrderTrackingRecoveredStatus = exports._36_Enums_OrderTrackingEmailStatus = exports._36_Enums_OrderStatus = exports._36_Enums_OrderDisputeStatus = exports._36_Enums_OnboardingStatus = exports._36_Enums_NotificationType = exports._36_Enums_MarketingType = exports._36_Enums_LogoSize = exports._36_Enums_HistoryTrackingType = exports._36_Enums_FulfillmentStatus = exports._36_Enums_FulfillmentPlatformIntegrationStatus = exports._36_Enums_FulfillmentPlatform = exports._36_Enums_FulfillmentAgencyType = exports._36_Enums_FulfillmentAgencyStatus = exports._36_Enums_FulfillmentAgencyRole = exports._36_Enums_FraudDetectionType = exports._36_Enums_FraudDetectionStatusType = exports._36_Enums_EnvironmentType = exports._36_Enums_EmailTrackingAction = exports._36_Enums_EmailDomainStatus = exports._36_Enums_DomainOrigin = exports._36_Enums_CustomDomainStatus = exports._36_Enums_CurrencyType = exports._36_Enums_CouponType = exports._36_Enums_CouponStatus = exports._36_Enums_CouponApplyingMethod = exports._36_Enums_CostCalculationMethod = exports._36_Enums_CollectionType = exports._36_Enums_CollectionStatus = exports._36_Enums_CapabilityStatus = exports._36_Enums_BoostSaleType = exports._36_Enums_BoostSaleTriggerType = exports._36_Enums_AsyncTaskType = exports._36_Enums_AsyncTaskStatus = exports.OpenAPI = exports.CancelError = exports.CancelablePromise = exports.BaseHttpRequest = exports.ApiError = exports.ClientApi = void 0;
exports.OtpType = exports.OrderTrackingRecoveredStatusDto = exports.OrderTrackingEmailStatusDto = exports.OperatorCollection_STARTS_WITH = exports.OperatorCollection_NOT_EQUAL_TO = exports.OperatorCollection_NOT_CONTAIN = exports.OperatorCollection_LESS_TO = exports.OperatorCollection_GREATER_TO = exports.OperatorCollection_EQUAL_TO = exports.OperatorCollection_ENDS_WITH = exports.OperatorCollection_CONTAIN = exports.OnboardingProduct = exports.GetCustomerTrackingDto = exports.FulfillmentPermissions = exports.FraudStatusType = exports.FilterStoreStatus = exports.FilterStoreReferral = exports.Exclude_RequestSourcingStatus_SELLER_REJECTED_or_SELLER_ACCEPTED_ = exports.EventOrderFraud = exports.ESendMailStatus = exports.DiscountValueType = exports.DiscountMinimumPurchaseRequirement = exports.DiscountForQuantityType = exports.DiscountBoostSaleType = exports.DefaultSelection_Prisma__36_PlatformProductPayload_ = exports.CurrencyCode = exports.CouponCombinationItem = exports.CombineOperator = exports.CollectionField_tag = exports.CollectionField_price = exports.CollectionField_name = exports.BoughtTogetherType = exports.ActiveDetection = exports.ActionOrderFraud = exports._36_Enums_UserRole = exports._36_Enums_TransactionType = exports._36_Enums_TransactionStatus = exports._36_Enums_ThemePageType = exports._36_Enums_TaxProviderOwner = exports._36_Enums_SyncTrackingStatus = exports._36_Enums_SubscriptionType = exports._36_Enums_SubscriptionStatus = exports._36_Enums_SubscriptionInterval = exports._36_Enums_SubscriptionFeatureType = exports._36_Enums_StoreUserInviteStatus = exports._36_Enums_StoreType = exports._36_Enums_StoreStatus = exports._36_Enums_StoreRole = exports._36_Enums_StoreLogType = exports._36_Enums_StoreEmailLogStatus = void 0;
exports.UserService = exports.UploadService = exports.MarketingService = exports.AuthService = exports.Week = exports.UTMSourceSchema = exports.TypeOfFraud = exports.TypeFulfillmentPrice = exports.TimezoneDto = exports.TimeEmailMarketingUnit = exports.SuperAdminPermission = exports.StoreResourceAccess = exports.statusRequestPayout = exports.StatisticsDisplayType = exports.sortTrackingPerformance = exports.SendEmailToListStoreStatus = exports.SellerPermission = exports.SalePerformanceResponsive = exports.RelatedProductType = exports.RefundType = exports.ReferralStoreType = exports.PrismaJson_TransactionPaymentMethod = exports.PlacementBoostSaleEnum = exports.Permission = exports.Period = exports.paymentIntegrationTypeEnum_ONBOARDING = exports.paymentIntegrationTypeEnum_DIRECT_API = exports.PaymentAndEmailDomainSetupStatus = exports.PageNameType = void 0;
/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
var ClientApi_1 = require("./ClientApi");
Object.defineProperty(exports, "ClientApi", { enumerable: true, get: function () { return ClientApi_1.ClientApi; } });
var ApiError_1 = require("./core/ApiError");
Object.defineProperty(exports, "ApiError", { enumerable: true, get: function () { return ApiError_1.ApiError; } });
var BaseHttpRequest_1 = require("./core/BaseHttpRequest");
Object.defineProperty(exports, "BaseHttpRequest", { enumerable: true, get: function () { return BaseHttpRequest_1.BaseHttpRequest; } });
var CancelablePromise_1 = require("./core/CancelablePromise");
Object.defineProperty(exports, "CancelablePromise", { enumerable: true, get: function () { return CancelablePromise_1.CancelablePromise; } });
Object.defineProperty(exports, "CancelError", { enumerable: true, get: function () { return CancelablePromise_1.CancelError; } });
var OpenAPI_1 = require("./core/OpenAPI");
Object.defineProperty(exports, "OpenAPI", { enumerable: true, get: function () { return OpenAPI_1.OpenAPI; } });
var _36_Enums_AsyncTaskStatus_1 = require("./models/_36_Enums_AsyncTaskStatus");
Object.defineProperty(exports, "_36_Enums_AsyncTaskStatus", { enumerable: true, get: function () { return _36_Enums_AsyncTaskStatus_1._36_Enums_AsyncTaskStatus; } });
var _36_Enums_AsyncTaskType_1 = require("./models/_36_Enums_AsyncTaskType");
Object.defineProperty(exports, "_36_Enums_AsyncTaskType", { enumerable: true, get: function () { return _36_Enums_AsyncTaskType_1._36_Enums_AsyncTaskType; } });
var _36_Enums_BoostSaleTriggerType_1 = require("./models/_36_Enums_BoostSaleTriggerType");
Object.defineProperty(exports, "_36_Enums_BoostSaleTriggerType", { enumerable: true, get: function () { return _36_Enums_BoostSaleTriggerType_1._36_Enums_BoostSaleTriggerType; } });
var _36_Enums_BoostSaleType_1 = require("./models/_36_Enums_BoostSaleType");
Object.defineProperty(exports, "_36_Enums_BoostSaleType", { enumerable: true, get: function () { return _36_Enums_BoostSaleType_1._36_Enums_BoostSaleType; } });
var _36_Enums_CapabilityStatus_1 = require("./models/_36_Enums_CapabilityStatus");
Object.defineProperty(exports, "_36_Enums_CapabilityStatus", { enumerable: true, get: function () { return _36_Enums_CapabilityStatus_1._36_Enums_CapabilityStatus; } });
var _36_Enums_CollectionStatus_1 = require("./models/_36_Enums_CollectionStatus");
Object.defineProperty(exports, "_36_Enums_CollectionStatus", { enumerable: true, get: function () { return _36_Enums_CollectionStatus_1._36_Enums_CollectionStatus; } });
var _36_Enums_CollectionType_1 = require("./models/_36_Enums_CollectionType");
Object.defineProperty(exports, "_36_Enums_CollectionType", { enumerable: true, get: function () { return _36_Enums_CollectionType_1._36_Enums_CollectionType; } });
var _36_Enums_CostCalculationMethod_1 = require("./models/_36_Enums_CostCalculationMethod");
Object.defineProperty(exports, "_36_Enums_CostCalculationMethod", { enumerable: true, get: function () { return _36_Enums_CostCalculationMethod_1._36_Enums_CostCalculationMethod; } });
var _36_Enums_CouponApplyingMethod_1 = require("./models/_36_Enums_CouponApplyingMethod");
Object.defineProperty(exports, "_36_Enums_CouponApplyingMethod", { enumerable: true, get: function () { return _36_Enums_CouponApplyingMethod_1._36_Enums_CouponApplyingMethod; } });
var _36_Enums_CouponStatus_1 = require("./models/_36_Enums_CouponStatus");
Object.defineProperty(exports, "_36_Enums_CouponStatus", { enumerable: true, get: function () { return _36_Enums_CouponStatus_1._36_Enums_CouponStatus; } });
var _36_Enums_CouponType_1 = require("./models/_36_Enums_CouponType");
Object.defineProperty(exports, "_36_Enums_CouponType", { enumerable: true, get: function () { return _36_Enums_CouponType_1._36_Enums_CouponType; } });
var _36_Enums_CurrencyType_1 = require("./models/_36_Enums_CurrencyType");
Object.defineProperty(exports, "_36_Enums_CurrencyType", { enumerable: true, get: function () { return _36_Enums_CurrencyType_1._36_Enums_CurrencyType; } });
var _36_Enums_CustomDomainStatus_1 = require("./models/_36_Enums_CustomDomainStatus");
Object.defineProperty(exports, "_36_Enums_CustomDomainStatus", { enumerable: true, get: function () { return _36_Enums_CustomDomainStatus_1._36_Enums_CustomDomainStatus; } });
var _36_Enums_DomainOrigin_1 = require("./models/_36_Enums_DomainOrigin");
Object.defineProperty(exports, "_36_Enums_DomainOrigin", { enumerable: true, get: function () { return _36_Enums_DomainOrigin_1._36_Enums_DomainOrigin; } });
var _36_Enums_EmailDomainStatus_1 = require("./models/_36_Enums_EmailDomainStatus");
Object.defineProperty(exports, "_36_Enums_EmailDomainStatus", { enumerable: true, get: function () { return _36_Enums_EmailDomainStatus_1._36_Enums_EmailDomainStatus; } });
var _36_Enums_EmailTrackingAction_1 = require("./models/_36_Enums_EmailTrackingAction");
Object.defineProperty(exports, "_36_Enums_EmailTrackingAction", { enumerable: true, get: function () { return _36_Enums_EmailTrackingAction_1._36_Enums_EmailTrackingAction; } });
var _36_Enums_EnvironmentType_1 = require("./models/_36_Enums_EnvironmentType");
Object.defineProperty(exports, "_36_Enums_EnvironmentType", { enumerable: true, get: function () { return _36_Enums_EnvironmentType_1._36_Enums_EnvironmentType; } });
var _36_Enums_FraudDetectionStatusType_1 = require("./models/_36_Enums_FraudDetectionStatusType");
Object.defineProperty(exports, "_36_Enums_FraudDetectionStatusType", { enumerable: true, get: function () { return _36_Enums_FraudDetectionStatusType_1._36_Enums_FraudDetectionStatusType; } });
var _36_Enums_FraudDetectionType_1 = require("./models/_36_Enums_FraudDetectionType");
Object.defineProperty(exports, "_36_Enums_FraudDetectionType", { enumerable: true, get: function () { return _36_Enums_FraudDetectionType_1._36_Enums_FraudDetectionType; } });
var _36_Enums_FulfillmentAgencyRole_1 = require("./models/_36_Enums_FulfillmentAgencyRole");
Object.defineProperty(exports, "_36_Enums_FulfillmentAgencyRole", { enumerable: true, get: function () { return _36_Enums_FulfillmentAgencyRole_1._36_Enums_FulfillmentAgencyRole; } });
var _36_Enums_FulfillmentAgencyStatus_1 = require("./models/_36_Enums_FulfillmentAgencyStatus");
Object.defineProperty(exports, "_36_Enums_FulfillmentAgencyStatus", { enumerable: true, get: function () { return _36_Enums_FulfillmentAgencyStatus_1._36_Enums_FulfillmentAgencyStatus; } });
var _36_Enums_FulfillmentAgencyType_1 = require("./models/_36_Enums_FulfillmentAgencyType");
Object.defineProperty(exports, "_36_Enums_FulfillmentAgencyType", { enumerable: true, get: function () { return _36_Enums_FulfillmentAgencyType_1._36_Enums_FulfillmentAgencyType; } });
var _36_Enums_FulfillmentPlatform_1 = require("./models/_36_Enums_FulfillmentPlatform");
Object.defineProperty(exports, "_36_Enums_FulfillmentPlatform", { enumerable: true, get: function () { return _36_Enums_FulfillmentPlatform_1._36_Enums_FulfillmentPlatform; } });
var _36_Enums_FulfillmentPlatformIntegrationStatus_1 = require("./models/_36_Enums_FulfillmentPlatformIntegrationStatus");
Object.defineProperty(exports, "_36_Enums_FulfillmentPlatformIntegrationStatus", { enumerable: true, get: function () { return _36_Enums_FulfillmentPlatformIntegrationStatus_1._36_Enums_FulfillmentPlatformIntegrationStatus; } });
var _36_Enums_FulfillmentStatus_1 = require("./models/_36_Enums_FulfillmentStatus");
Object.defineProperty(exports, "_36_Enums_FulfillmentStatus", { enumerable: true, get: function () { return _36_Enums_FulfillmentStatus_1._36_Enums_FulfillmentStatus; } });
var _36_Enums_HistoryTrackingType_1 = require("./models/_36_Enums_HistoryTrackingType");
Object.defineProperty(exports, "_36_Enums_HistoryTrackingType", { enumerable: true, get: function () { return _36_Enums_HistoryTrackingType_1._36_Enums_HistoryTrackingType; } });
var _36_Enums_LogoSize_1 = require("./models/_36_Enums_LogoSize");
Object.defineProperty(exports, "_36_Enums_LogoSize", { enumerable: true, get: function () { return _36_Enums_LogoSize_1._36_Enums_LogoSize; } });
var _36_Enums_MarketingType_1 = require("./models/_36_Enums_MarketingType");
Object.defineProperty(exports, "_36_Enums_MarketingType", { enumerable: true, get: function () { return _36_Enums_MarketingType_1._36_Enums_MarketingType; } });
var _36_Enums_NotificationType_1 = require("./models/_36_Enums_NotificationType");
Object.defineProperty(exports, "_36_Enums_NotificationType", { enumerable: true, get: function () { return _36_Enums_NotificationType_1._36_Enums_NotificationType; } });
var _36_Enums_OnboardingStatus_1 = require("./models/_36_Enums_OnboardingStatus");
Object.defineProperty(exports, "_36_Enums_OnboardingStatus", { enumerable: true, get: function () { return _36_Enums_OnboardingStatus_1._36_Enums_OnboardingStatus; } });
var _36_Enums_OrderDisputeStatus_1 = require("./models/_36_Enums_OrderDisputeStatus");
Object.defineProperty(exports, "_36_Enums_OrderDisputeStatus", { enumerable: true, get: function () { return _36_Enums_OrderDisputeStatus_1._36_Enums_OrderDisputeStatus; } });
var _36_Enums_OrderStatus_1 = require("./models/_36_Enums_OrderStatus");
Object.defineProperty(exports, "_36_Enums_OrderStatus", { enumerable: true, get: function () { return _36_Enums_OrderStatus_1._36_Enums_OrderStatus; } });
var _36_Enums_OrderTrackingEmailStatus_1 = require("./models/_36_Enums_OrderTrackingEmailStatus");
Object.defineProperty(exports, "_36_Enums_OrderTrackingEmailStatus", { enumerable: true, get: function () { return _36_Enums_OrderTrackingEmailStatus_1._36_Enums_OrderTrackingEmailStatus; } });
var _36_Enums_OrderTrackingRecoveredStatus_1 = require("./models/_36_Enums_OrderTrackingRecoveredStatus");
Object.defineProperty(exports, "_36_Enums_OrderTrackingRecoveredStatus", { enumerable: true, get: function () { return _36_Enums_OrderTrackingRecoveredStatus_1._36_Enums_OrderTrackingRecoveredStatus; } });
var _36_Enums_PaymentIntegrationType_1 = require("./models/_36_Enums_PaymentIntegrationType");
Object.defineProperty(exports, "_36_Enums_PaymentIntegrationType", { enumerable: true, get: function () { return _36_Enums_PaymentIntegrationType_1._36_Enums_PaymentIntegrationType; } });
var _36_Enums_PaymentMethodType_1 = require("./models/_36_Enums_PaymentMethodType");
Object.defineProperty(exports, "_36_Enums_PaymentMethodType", { enumerable: true, get: function () { return _36_Enums_PaymentMethodType_1._36_Enums_PaymentMethodType; } });
var _36_Enums_PaymentType_1 = require("./models/_36_Enums_PaymentType");
Object.defineProperty(exports, "_36_Enums_PaymentType", { enumerable: true, get: function () { return _36_Enums_PaymentType_1._36_Enums_PaymentType; } });
var _36_Enums_PingPongAuthStatus_1 = require("./models/_36_Enums_PingPongAuthStatus");
Object.defineProperty(exports, "_36_Enums_PingPongAuthStatus", { enumerable: true, get: function () { return _36_Enums_PingPongAuthStatus_1._36_Enums_PingPongAuthStatus; } });
var _36_Enums_PPCPVettingStatus_1 = require("./models/_36_Enums_PPCPVettingStatus");
Object.defineProperty(exports, "_36_Enums_PPCPVettingStatus", { enumerable: true, get: function () { return _36_Enums_PPCPVettingStatus_1._36_Enums_PPCPVettingStatus; } });
var _36_Enums_RequestPayoutStatus_1 = require("./models/_36_Enums_RequestPayoutStatus");
Object.defineProperty(exports, "_36_Enums_RequestPayoutStatus", { enumerable: true, get: function () { return _36_Enums_RequestPayoutStatus_1._36_Enums_RequestPayoutStatus; } });
var _36_Enums_RequestSourcingStatus_1 = require("./models/_36_Enums_RequestSourcingStatus");
Object.defineProperty(exports, "_36_Enums_RequestSourcingStatus", { enumerable: true, get: function () { return _36_Enums_RequestSourcingStatus_1._36_Enums_RequestSourcingStatus; } });
var _36_Enums_RolePermissionType_1 = require("./models/_36_Enums_RolePermissionType");
Object.defineProperty(exports, "_36_Enums_RolePermissionType", { enumerable: true, get: function () { return _36_Enums_RolePermissionType_1._36_Enums_RolePermissionType; } });
var _36_Enums_SaleStatus_1 = require("./models/_36_Enums_SaleStatus");
Object.defineProperty(exports, "_36_Enums_SaleStatus", { enumerable: true, get: function () { return _36_Enums_SaleStatus_1._36_Enums_SaleStatus; } });
var _36_Enums_SaleUserTrackingType_1 = require("./models/_36_Enums_SaleUserTrackingType");
Object.defineProperty(exports, "_36_Enums_SaleUserTrackingType", { enumerable: true, get: function () { return _36_Enums_SaleUserTrackingType_1._36_Enums_SaleUserTrackingType; } });
var _36_Enums_StoreEmailLogStatus_1 = require("./models/_36_Enums_StoreEmailLogStatus");
Object.defineProperty(exports, "_36_Enums_StoreEmailLogStatus", { enumerable: true, get: function () { return _36_Enums_StoreEmailLogStatus_1._36_Enums_StoreEmailLogStatus; } });
var _36_Enums_StoreLogType_1 = require("./models/_36_Enums_StoreLogType");
Object.defineProperty(exports, "_36_Enums_StoreLogType", { enumerable: true, get: function () { return _36_Enums_StoreLogType_1._36_Enums_StoreLogType; } });
var _36_Enums_StoreRole_1 = require("./models/_36_Enums_StoreRole");
Object.defineProperty(exports, "_36_Enums_StoreRole", { enumerable: true, get: function () { return _36_Enums_StoreRole_1._36_Enums_StoreRole; } });
var _36_Enums_StoreStatus_1 = require("./models/_36_Enums_StoreStatus");
Object.defineProperty(exports, "_36_Enums_StoreStatus", { enumerable: true, get: function () { return _36_Enums_StoreStatus_1._36_Enums_StoreStatus; } });
var _36_Enums_StoreType_1 = require("./models/_36_Enums_StoreType");
Object.defineProperty(exports, "_36_Enums_StoreType", { enumerable: true, get: function () { return _36_Enums_StoreType_1._36_Enums_StoreType; } });
var _36_Enums_StoreUserInviteStatus_1 = require("./models/_36_Enums_StoreUserInviteStatus");
Object.defineProperty(exports, "_36_Enums_StoreUserInviteStatus", { enumerable: true, get: function () { return _36_Enums_StoreUserInviteStatus_1._36_Enums_StoreUserInviteStatus; } });
var _36_Enums_SubscriptionFeatureType_1 = require("./models/_36_Enums_SubscriptionFeatureType");
Object.defineProperty(exports, "_36_Enums_SubscriptionFeatureType", { enumerable: true, get: function () { return _36_Enums_SubscriptionFeatureType_1._36_Enums_SubscriptionFeatureType; } });
var _36_Enums_SubscriptionInterval_1 = require("./models/_36_Enums_SubscriptionInterval");
Object.defineProperty(exports, "_36_Enums_SubscriptionInterval", { enumerable: true, get: function () { return _36_Enums_SubscriptionInterval_1._36_Enums_SubscriptionInterval; } });
var _36_Enums_SubscriptionStatus_1 = require("./models/_36_Enums_SubscriptionStatus");
Object.defineProperty(exports, "_36_Enums_SubscriptionStatus", { enumerable: true, get: function () { return _36_Enums_SubscriptionStatus_1._36_Enums_SubscriptionStatus; } });
var _36_Enums_SubscriptionType_1 = require("./models/_36_Enums_SubscriptionType");
Object.defineProperty(exports, "_36_Enums_SubscriptionType", { enumerable: true, get: function () { return _36_Enums_SubscriptionType_1._36_Enums_SubscriptionType; } });
var _36_Enums_SyncTrackingStatus_1 = require("./models/_36_Enums_SyncTrackingStatus");
Object.defineProperty(exports, "_36_Enums_SyncTrackingStatus", { enumerable: true, get: function () { return _36_Enums_SyncTrackingStatus_1._36_Enums_SyncTrackingStatus; } });
var _36_Enums_TaxProviderOwner_1 = require("./models/_36_Enums_TaxProviderOwner");
Object.defineProperty(exports, "_36_Enums_TaxProviderOwner", { enumerable: true, get: function () { return _36_Enums_TaxProviderOwner_1._36_Enums_TaxProviderOwner; } });
var _36_Enums_ThemePageType_1 = require("./models/_36_Enums_ThemePageType");
Object.defineProperty(exports, "_36_Enums_ThemePageType", { enumerable: true, get: function () { return _36_Enums_ThemePageType_1._36_Enums_ThemePageType; } });
var _36_Enums_TransactionStatus_1 = require("./models/_36_Enums_TransactionStatus");
Object.defineProperty(exports, "_36_Enums_TransactionStatus", { enumerable: true, get: function () { return _36_Enums_TransactionStatus_1._36_Enums_TransactionStatus; } });
var _36_Enums_TransactionType_1 = require("./models/_36_Enums_TransactionType");
Object.defineProperty(exports, "_36_Enums_TransactionType", { enumerable: true, get: function () { return _36_Enums_TransactionType_1._36_Enums_TransactionType; } });
var _36_Enums_UserRole_1 = require("./models/_36_Enums_UserRole");
Object.defineProperty(exports, "_36_Enums_UserRole", { enumerable: true, get: function () { return _36_Enums_UserRole_1._36_Enums_UserRole; } });
var ActionOrderFraud_1 = require("./models/ActionOrderFraud");
Object.defineProperty(exports, "ActionOrderFraud", { enumerable: true, get: function () { return ActionOrderFraud_1.ActionOrderFraud; } });
var ActiveDetection_1 = require("./models/ActiveDetection");
Object.defineProperty(exports, "ActiveDetection", { enumerable: true, get: function () { return ActiveDetection_1.ActiveDetection; } });
var BoughtTogetherType_1 = require("./models/BoughtTogetherType");
Object.defineProperty(exports, "BoughtTogetherType", { enumerable: true, get: function () { return BoughtTogetherType_1.BoughtTogetherType; } });
var CollectionField_name_1 = require("./models/CollectionField_name");
Object.defineProperty(exports, "CollectionField_name", { enumerable: true, get: function () { return CollectionField_name_1.CollectionField_name; } });
var CollectionField_price_1 = require("./models/CollectionField_price");
Object.defineProperty(exports, "CollectionField_price", { enumerable: true, get: function () { return CollectionField_price_1.CollectionField_price; } });
var CollectionField_tag_1 = require("./models/CollectionField_tag");
Object.defineProperty(exports, "CollectionField_tag", { enumerable: true, get: function () { return CollectionField_tag_1.CollectionField_tag; } });
var CombineOperator_1 = require("./models/CombineOperator");
Object.defineProperty(exports, "CombineOperator", { enumerable: true, get: function () { return CombineOperator_1.CombineOperator; } });
var CouponCombinationItem_1 = require("./models/CouponCombinationItem");
Object.defineProperty(exports, "CouponCombinationItem", { enumerable: true, get: function () { return CouponCombinationItem_1.CouponCombinationItem; } });
var CurrencyCode_1 = require("./models/CurrencyCode");
Object.defineProperty(exports, "CurrencyCode", { enumerable: true, get: function () { return CurrencyCode_1.CurrencyCode; } });
var DefaultSelection_Prisma__36_PlatformProductPayload_1 = require("./models/DefaultSelection_Prisma__36_PlatformProductPayload_");
Object.defineProperty(exports, "DefaultSelection_Prisma__36_PlatformProductPayload_", { enumerable: true, get: function () { return DefaultSelection_Prisma__36_PlatformProductPayload_1.DefaultSelection_Prisma__36_PlatformProductPayload_; } });
var DiscountBoostSaleType_1 = require("./models/DiscountBoostSaleType");
Object.defineProperty(exports, "DiscountBoostSaleType", { enumerable: true, get: function () { return DiscountBoostSaleType_1.DiscountBoostSaleType; } });
var DiscountForQuantityType_1 = require("./models/DiscountForQuantityType");
Object.defineProperty(exports, "DiscountForQuantityType", { enumerable: true, get: function () { return DiscountForQuantityType_1.DiscountForQuantityType; } });
var DiscountMinimumPurchaseRequirement_1 = require("./models/DiscountMinimumPurchaseRequirement");
Object.defineProperty(exports, "DiscountMinimumPurchaseRequirement", { enumerable: true, get: function () { return DiscountMinimumPurchaseRequirement_1.DiscountMinimumPurchaseRequirement; } });
var DiscountValueType_1 = require("./models/DiscountValueType");
Object.defineProperty(exports, "DiscountValueType", { enumerable: true, get: function () { return DiscountValueType_1.DiscountValueType; } });
var ESendMailStatus_1 = require("./models/ESendMailStatus");
Object.defineProperty(exports, "ESendMailStatus", { enumerable: true, get: function () { return ESendMailStatus_1.ESendMailStatus; } });
var EventOrderFraud_1 = require("./models/EventOrderFraud");
Object.defineProperty(exports, "EventOrderFraud", { enumerable: true, get: function () { return EventOrderFraud_1.EventOrderFraud; } });
var Exclude_RequestSourcingStatus_SELLER_REJECTED_or_SELLER_ACCEPTED_1 = require("./models/Exclude_RequestSourcingStatus_SELLER_REJECTED_or_SELLER_ACCEPTED_");
Object.defineProperty(exports, "Exclude_RequestSourcingStatus_SELLER_REJECTED_or_SELLER_ACCEPTED_", { enumerable: true, get: function () { return Exclude_RequestSourcingStatus_SELLER_REJECTED_or_SELLER_ACCEPTED_1.Exclude_RequestSourcingStatus_SELLER_REJECTED_or_SELLER_ACCEPTED_; } });
var FilterStoreReferral_1 = require("./models/FilterStoreReferral");
Object.defineProperty(exports, "FilterStoreReferral", { enumerable: true, get: function () { return FilterStoreReferral_1.FilterStoreReferral; } });
var FilterStoreStatus_1 = require("./models/FilterStoreStatus");
Object.defineProperty(exports, "FilterStoreStatus", { enumerable: true, get: function () { return FilterStoreStatus_1.FilterStoreStatus; } });
var FraudStatusType_1 = require("./models/FraudStatusType");
Object.defineProperty(exports, "FraudStatusType", { enumerable: true, get: function () { return FraudStatusType_1.FraudStatusType; } });
var FulfillmentPermissions_1 = require("./models/FulfillmentPermissions");
Object.defineProperty(exports, "FulfillmentPermissions", { enumerable: true, get: function () { return FulfillmentPermissions_1.FulfillmentPermissions; } });
var GetCustomerTrackingDto_1 = require("./models/GetCustomerTrackingDto");
Object.defineProperty(exports, "GetCustomerTrackingDto", { enumerable: true, get: function () { return GetCustomerTrackingDto_1.GetCustomerTrackingDto; } });
var OnboardingProduct_1 = require("./models/OnboardingProduct");
Object.defineProperty(exports, "OnboardingProduct", { enumerable: true, get: function () { return OnboardingProduct_1.OnboardingProduct; } });
var OperatorCollection_CONTAIN_1 = require("./models/OperatorCollection_CONTAIN");
Object.defineProperty(exports, "OperatorCollection_CONTAIN", { enumerable: true, get: function () { return OperatorCollection_CONTAIN_1.OperatorCollection_CONTAIN; } });
var OperatorCollection_ENDS_WITH_1 = require("./models/OperatorCollection_ENDS_WITH");
Object.defineProperty(exports, "OperatorCollection_ENDS_WITH", { enumerable: true, get: function () { return OperatorCollection_ENDS_WITH_1.OperatorCollection_ENDS_WITH; } });
var OperatorCollection_EQUAL_TO_1 = require("./models/OperatorCollection_EQUAL_TO");
Object.defineProperty(exports, "OperatorCollection_EQUAL_TO", { enumerable: true, get: function () { return OperatorCollection_EQUAL_TO_1.OperatorCollection_EQUAL_TO; } });
var OperatorCollection_GREATER_TO_1 = require("./models/OperatorCollection_GREATER_TO");
Object.defineProperty(exports, "OperatorCollection_GREATER_TO", { enumerable: true, get: function () { return OperatorCollection_GREATER_TO_1.OperatorCollection_GREATER_TO; } });
var OperatorCollection_LESS_TO_1 = require("./models/OperatorCollection_LESS_TO");
Object.defineProperty(exports, "OperatorCollection_LESS_TO", { enumerable: true, get: function () { return OperatorCollection_LESS_TO_1.OperatorCollection_LESS_TO; } });
var OperatorCollection_NOT_CONTAIN_1 = require("./models/OperatorCollection_NOT_CONTAIN");
Object.defineProperty(exports, "OperatorCollection_NOT_CONTAIN", { enumerable: true, get: function () { return OperatorCollection_NOT_CONTAIN_1.OperatorCollection_NOT_CONTAIN; } });
var OperatorCollection_NOT_EQUAL_TO_1 = require("./models/OperatorCollection_NOT_EQUAL_TO");
Object.defineProperty(exports, "OperatorCollection_NOT_EQUAL_TO", { enumerable: true, get: function () { return OperatorCollection_NOT_EQUAL_TO_1.OperatorCollection_NOT_EQUAL_TO; } });
var OperatorCollection_STARTS_WITH_1 = require("./models/OperatorCollection_STARTS_WITH");
Object.defineProperty(exports, "OperatorCollection_STARTS_WITH", { enumerable: true, get: function () { return OperatorCollection_STARTS_WITH_1.OperatorCollection_STARTS_WITH; } });
var OrderTrackingEmailStatusDto_1 = require("./models/OrderTrackingEmailStatusDto");
Object.defineProperty(exports, "OrderTrackingEmailStatusDto", { enumerable: true, get: function () { return OrderTrackingEmailStatusDto_1.OrderTrackingEmailStatusDto; } });
var OrderTrackingRecoveredStatusDto_1 = require("./models/OrderTrackingRecoveredStatusDto");
Object.defineProperty(exports, "OrderTrackingRecoveredStatusDto", { enumerable: true, get: function () { return OrderTrackingRecoveredStatusDto_1.OrderTrackingRecoveredStatusDto; } });
var OtpType_1 = require("./models/OtpType");
Object.defineProperty(exports, "OtpType", { enumerable: true, get: function () { return OtpType_1.OtpType; } });
var PageNameType_1 = require("./models/PageNameType");
Object.defineProperty(exports, "PageNameType", { enumerable: true, get: function () { return PageNameType_1.PageNameType; } });
var PaymentAndEmailDomainSetupStatus_1 = require("./models/PaymentAndEmailDomainSetupStatus");
Object.defineProperty(exports, "PaymentAndEmailDomainSetupStatus", { enumerable: true, get: function () { return PaymentAndEmailDomainSetupStatus_1.PaymentAndEmailDomainSetupStatus; } });
var paymentIntegrationTypeEnum_DIRECT_API_1 = require("./models/paymentIntegrationTypeEnum_DIRECT_API");
Object.defineProperty(exports, "paymentIntegrationTypeEnum_DIRECT_API", { enumerable: true, get: function () { return paymentIntegrationTypeEnum_DIRECT_API_1.paymentIntegrationTypeEnum_DIRECT_API; } });
var paymentIntegrationTypeEnum_ONBOARDING_1 = require("./models/paymentIntegrationTypeEnum_ONBOARDING");
Object.defineProperty(exports, "paymentIntegrationTypeEnum_ONBOARDING", { enumerable: true, get: function () { return paymentIntegrationTypeEnum_ONBOARDING_1.paymentIntegrationTypeEnum_ONBOARDING; } });
var Period_1 = require("./models/Period");
Object.defineProperty(exports, "Period", { enumerable: true, get: function () { return Period_1.Period; } });
var Permission_1 = require("./models/Permission");
Object.defineProperty(exports, "Permission", { enumerable: true, get: function () { return Permission_1.Permission; } });
var PlacementBoostSaleEnum_1 = require("./models/PlacementBoostSaleEnum");
Object.defineProperty(exports, "PlacementBoostSaleEnum", { enumerable: true, get: function () { return PlacementBoostSaleEnum_1.PlacementBoostSaleEnum; } });
var PrismaJson_TransactionPaymentMethod_1 = require("./models/PrismaJson_TransactionPaymentMethod");
Object.defineProperty(exports, "PrismaJson_TransactionPaymentMethod", { enumerable: true, get: function () { return PrismaJson_TransactionPaymentMethod_1.PrismaJson_TransactionPaymentMethod; } });
var ReferralStoreType_1 = require("./models/ReferralStoreType");
Object.defineProperty(exports, "ReferralStoreType", { enumerable: true, get: function () { return ReferralStoreType_1.ReferralStoreType; } });
var RefundType_1 = require("./models/RefundType");
Object.defineProperty(exports, "RefundType", { enumerable: true, get: function () { return RefundType_1.RefundType; } });
var RelatedProductType_1 = require("./models/RelatedProductType");
Object.defineProperty(exports, "RelatedProductType", { enumerable: true, get: function () { return RelatedProductType_1.RelatedProductType; } });
var SalePerformanceResponsive_1 = require("./models/SalePerformanceResponsive");
Object.defineProperty(exports, "SalePerformanceResponsive", { enumerable: true, get: function () { return SalePerformanceResponsive_1.SalePerformanceResponsive; } });
var SellerPermission_1 = require("./models/SellerPermission");
Object.defineProperty(exports, "SellerPermission", { enumerable: true, get: function () { return SellerPermission_1.SellerPermission; } });
var SendEmailToListStoreStatus_1 = require("./models/SendEmailToListStoreStatus");
Object.defineProperty(exports, "SendEmailToListStoreStatus", { enumerable: true, get: function () { return SendEmailToListStoreStatus_1.SendEmailToListStoreStatus; } });
var sortTrackingPerformance_1 = require("./models/sortTrackingPerformance");
Object.defineProperty(exports, "sortTrackingPerformance", { enumerable: true, get: function () { return sortTrackingPerformance_1.sortTrackingPerformance; } });
var StatisticsDisplayType_1 = require("./models/StatisticsDisplayType");
Object.defineProperty(exports, "StatisticsDisplayType", { enumerable: true, get: function () { return StatisticsDisplayType_1.StatisticsDisplayType; } });
var statusRequestPayout_1 = require("./models/statusRequestPayout");
Object.defineProperty(exports, "statusRequestPayout", { enumerable: true, get: function () { return statusRequestPayout_1.statusRequestPayout; } });
var StoreResourceAccess_1 = require("./models/StoreResourceAccess");
Object.defineProperty(exports, "StoreResourceAccess", { enumerable: true, get: function () { return StoreResourceAccess_1.StoreResourceAccess; } });
var SuperAdminPermission_1 = require("./models/SuperAdminPermission");
Object.defineProperty(exports, "SuperAdminPermission", { enumerable: true, get: function () { return SuperAdminPermission_1.SuperAdminPermission; } });
var TimeEmailMarketingUnit_1 = require("./models/TimeEmailMarketingUnit");
Object.defineProperty(exports, "TimeEmailMarketingUnit", { enumerable: true, get: function () { return TimeEmailMarketingUnit_1.TimeEmailMarketingUnit; } });
var TimezoneDto_1 = require("./models/TimezoneDto");
Object.defineProperty(exports, "TimezoneDto", { enumerable: true, get: function () { return TimezoneDto_1.TimezoneDto; } });
var TypeFulfillmentPrice_1 = require("./models/TypeFulfillmentPrice");
Object.defineProperty(exports, "TypeFulfillmentPrice", { enumerable: true, get: function () { return TypeFulfillmentPrice_1.TypeFulfillmentPrice; } });
var TypeOfFraud_1 = require("./models/TypeOfFraud");
Object.defineProperty(exports, "TypeOfFraud", { enumerable: true, get: function () { return TypeOfFraud_1.TypeOfFraud; } });
var UTMSourceSchema_1 = require("./models/UTMSourceSchema");
Object.defineProperty(exports, "UTMSourceSchema", { enumerable: true, get: function () { return UTMSourceSchema_1.UTMSourceSchema; } });
var Week_1 = require("./models/Week");
Object.defineProperty(exports, "Week", { enumerable: true, get: function () { return Week_1.Week; } });
var AuthService_1 = require("./services/AuthService");
Object.defineProperty(exports, "AuthService", { enumerable: true, get: function () { return AuthService_1.AuthService; } });
var MarketingService_1 = require("./services/MarketingService");
Object.defineProperty(exports, "MarketingService", { enumerable: true, get: function () { return MarketingService_1.MarketingService; } });
var UploadService_1 = require("./services/UploadService");
Object.defineProperty(exports, "UploadService", { enumerable: true, get: function () { return UploadService_1.UploadService; } });
var UserService_1 = require("./services/UserService");
Object.defineProperty(exports, "UserService", { enumerable: true, get: function () { return UserService_1.UserService; } });
