/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ClientApi } from './ClientApi';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AbandonmentStatisticsDto } from './models/AbandonmentStatisticsDto';
export { ActionOrderFraud } from './models/ActionOrderFraud';
export { ActiveDetection } from './models/ActiveDetection';
export type { AddPaymentToStores } from './models/AddPaymentToStores';
export type { AddPlatformProductStoresDto } from './models/AddPlatformProductStoresDto';
export type { AddPlatformProductTagDto } from './models/AddPlatformProductTagDto';
export type { AddPlatformVariantToGroupDto } from './models/AddPlatformVariantToGroupDto';
export type { AdminTag } from './models/AdminTag';
export type { ApproveRequestSourcingDto } from './models/ApproveRequestSourcingDto';
export type { ApproveStoreDto } from './models/ApproveStoreDto';
export type { AsyncTask } from './models/AsyncTask';
export type { AsyncTaskError } from './models/AsyncTaskError';
export { AsyncTaskStatus } from './models/AsyncTaskStatus';
export { AsyncTaskType } from './models/AsyncTaskType';
export type { AuthData } from './models/AuthData';
export type { AuthStoreData } from './models/AuthStoreData';
export type { AvailableSet } from './models/AvailableSet';
export type { BankAccount } from './models/BankAccount';
export type { bankInfo } from './models/bankInfo';
export type { BatchPayload } from './models/BatchPayload';
export type { BillingInfo } from './models/BillingInfo';
export type { BoostSale } from './models/BoostSale';
export type { BoostSaleDto } from './models/BoostSaleDto';
export { BoostSaleTriggerType } from './models/BoostSaleTriggerType';
export { BoostSaleType } from './models/BoostSaleType';
export { BoughtTogetherType } from './models/BoughtTogetherType';
export type { BuyDomainDto } from './models/BuyDomainDto';
export type { Campaign } from './models/Campaign';
export type { CampaignDto } from './models/CampaignDto';
export type { CaptureOrderDto } from './models/CaptureOrderDto';
export type { ChangeActiveTheme } from './models/ChangeActiveTheme';
export type { ChangeUserPasswordDto } from './models/ChangeUserPasswordDto';
export type { ClickToOrderDto } from './models/ClickToOrderDto';
export type { CloneProductDto } from './models/CloneProductDto';
export type { Collection } from './models/Collection';
export { CollectionField_name } from './models/CollectionField_name';
export { CollectionField_price } from './models/CollectionField_price';
export { CollectionField_tag } from './models/CollectionField_tag';
export { CollectionStatus } from './models/CollectionStatus';
export { CollectionType } from './models/CollectionType';
export { CombineOperator } from './models/CombineOperator';
export type { ComboItemDto } from './models/ComboItemDto';
export type { ComboItemTrackingDto } from './models/ComboItemTrackingDto';
export type { ConditionOperation } from './models/ConditionOperation';
export type { ContactFormDto } from './models/ContactFormDto';
export type { Coordinates } from './models/Coordinates';
export { CostCalculationMethod } from './models/CostCalculationMethod';
export type { CountryInformationType } from './models/CountryInformationType';
export type { CreateAbandonmentOrder } from './models/CreateAbandonmentOrder';
export type { CreateBankAccountDto } from './models/CreateBankAccountDto';
export type { CreateCollectionDto } from './models/CreateCollectionDto';
export type { CreateComboDto } from './models/CreateComboDto';
export type { CreateComboItems } from './models/CreateComboItems';
export type { CreateCurrencyDto } from './models/CreateCurrencyDto';
export type { CreateDiscountDto } from './models/CreateDiscountDto';
export type { CreateDomainDto } from './models/CreateDomainDto';
export type { CreateFbPixelDto } from './models/CreateFbPixelDto';
export type { CreateFulfillmentAgencyDto } from './models/CreateFulfillmentAgencyDto';
export type { CreateGADto } from './models/CreateGADto';
export type { CreateGroupPlatformVariantsDto } from './models/CreateGroupPlatformVariantsDto';
export type { CreateGTMDto } from './models/CreateGTMDto';
export type { CreateMarketingAccount } from './models/CreateMarketingAccount';
export type { CreateNotificationDto } from './models/CreateNotificationDto';
export type { CreateOrderDto } from './models/CreateOrderDto';
export type { CreateOrderItems } from './models/CreateOrderItems';
export type { CreateOrderTrackingDto } from './models/CreateOrderTrackingDto';
export type { CreatePaymentDto } from './models/CreatePaymentDto';
export type { CreatePingPongAccountDto } from './models/CreatePingPongAccountDto';
export type { CreatePlatformProductDto } from './models/CreatePlatformProductDto';
export type { CreatePlatformVariantDto } from './models/CreatePlatformVariantDto';
export type { CreatePlatformVariantsDto } from './models/CreatePlatformVariantsDto';
export type { CreateProductDto } from './models/CreateProductDto';
export type { CreateProductFromSellerInDependenceDto } from './models/CreateProductFromSellerInDependenceDto';
export type { CreateRequestPayoutDto } from './models/CreateRequestPayoutDto';
export type { CreateRequestSourcingDto } from './models/CreateRequestSourcingDto';
export type { CreateReviewDto } from './models/CreateReviewDto';
export type { CreateStaffDto } from './models/CreateStaffDto';
export type { CreateStoreDto } from './models/CreateStoreDto';
export type { CreateStoreTagDto } from './models/CreateStoreTagDto';
export type { CreateTagDto } from './models/CreateTagDto';
export type { CreateTemplateDto } from './models/CreateTemplateDto';
export type { CreateThemeDto } from './models/CreateThemeDto';
export type { CreateThemeLibraryDto } from './models/CreateThemeLibraryDto';
export type { CreateTiktokPixelDto } from './models/CreateTiktokPixelDto';
export type { CreateUploadDto } from './models/CreateUploadDto';
export type { CreateVariantsDto } from './models/CreateVariantsDto';
export type { Currency } from './models/Currency';
export { CurrencyCode } from './models/CurrencyCode';
export { CurrencyType } from './models/CurrencyType';
export type { CustomDomain } from './models/CustomDomain';
export { CustomDomainStatus } from './models/CustomDomainStatus';
export type { Discount } from './models/Discount';
export type { DiscountBoostSale } from './models/DiscountBoostSale';
export { DiscountBoostSaleType } from './models/DiscountBoostSaleType';
export type { DiscountDto } from './models/DiscountDto';
export { DiscountForQuantityType } from './models/DiscountForQuantityType';
export type { DomainContactInfo } from './models/DomainContactInfo';
export { DomainOrigin } from './models/DomainOrigin';
export type { EmailDto } from './models/EmailDto';
export type { EmailTrackingAction } from './models/EmailTrackingAction';
export { EnvironmentType } from './models/EnvironmentType';
export type { EventFraudType } from './models/EventFraudType';
export { EventOrderFraud } from './models/EventOrderFraud';
export type { ExportAccountancyResult } from './models/ExportAccountancyResult';
export type { ExportOrderDto } from './models/ExportOrderDto';
export type { ExportOrderResponseDto } from './models/ExportOrderResponseDto';
export type { ExportOrderResult } from './models/ExportOrderResult';
export type { FbPixel } from './models/FbPixel';
export type { FixedCostInfo } from './models/FixedCostInfo';
export type { FraudDetection } from './models/FraudDetection';
export { FraudDetectionStatusType } from './models/FraudDetectionStatusType';
export { FraudDetectionType } from './models/FraudDetectionType';
export { FraudStatusType } from './models/FraudStatusType';
export type { FulfillmentAgency } from './models/FulfillmentAgency';
export { FulfillmentAgencyRole } from './models/FulfillmentAgencyRole';
export { FulfillmentAgencyStatus } from './models/FulfillmentAgencyStatus';
export { FulfillmentStatus } from './models/FulfillmentStatus';
export type { FulfillmentUser } from './models/FulfillmentUser';
export type { GetAllOrderDto } from './models/GetAllOrderDto';
export type { GetAllStoresDto } from './models/GetAllStoresDto';
export type { GetAutomationMetricStatisticsDto } from './models/GetAutomationMetricStatisticsDto';
export type { getBoostSalesDto } from './models/getBoostSalesDto';
export type { getCrossSellByProductDto } from './models/getCrossSellByProductDto';
export type { GetImageTrackingDto } from './models/GetImageTrackingDto';
export type { GetListStoreMarketingDto } from './models/GetListStoreMarketingDto';
export type { GetOverviewStatisticsDto } from './models/GetOverviewStatisticsDto';
export type { GetPerformingStatisticsDto } from './models/GetPerformingStatisticsDto';
export type { getStatusCombosType } from './models/getStatusCombosType';
export type { GetStoreStatisticsAbandonmentDto } from './models/GetStoreStatisticsAbandonmentDto';
export type { GetTrackingOrderCheckoutDto } from './models/GetTrackingOrderCheckoutDto';
export type { getVariantsType } from './models/getVariantsType';
export type { GoogleAnalytic } from './models/GoogleAnalytic';
export type { GoogleTagManager } from './models/GoogleTagManager';
export type { GroupPlatformVariant } from './models/GroupPlatformVariant';
export type { JsonArray } from './models/JsonArray';
export type { JsonObject } from './models/JsonObject';
export type { JsonValue } from './models/JsonValue';
export type { ListAbandonmentOrdersDto } from './models/ListAbandonmentOrdersDto';
export type { LoginDto } from './models/LoginDto';
export { LogoSize } from './models/LogoSize';
export type { ManualFraudDetectionDto } from './models/ManualFraudDetectionDto';
export { MarketingType } from './models/MarketingType';
export type { NameConditionDto } from './models/NameConditionDto';
export type { NameDto } from './models/NameDto';
export type { Notification } from './models/Notification';
export type { NotificationData } from './models/NotificationData';
export { NotificationType } from './models/NotificationType';
export type { NullableDateTimeFieldUpdateOperationsInput } from './models/NullableDateTimeFieldUpdateOperationsInput';
export { OperatorCollection_CONTAIN } from './models/OperatorCollection_CONTAIN';
export { OperatorCollection_ENDS_WITH } from './models/OperatorCollection_ENDS_WITH';
export { OperatorCollection_EQUAL_TO } from './models/OperatorCollection_EQUAL_TO';
export { OperatorCollection_GREATER_TO } from './models/OperatorCollection_GREATER_TO';
export { OperatorCollection_LESS_TO } from './models/OperatorCollection_LESS_TO';
export { OperatorCollection_NOT_CONTAIN } from './models/OperatorCollection_NOT_CONTAIN';
export { OperatorCollection_NOT_EQUAL_TO } from './models/OperatorCollection_NOT_EQUAL_TO';
export { OperatorCollection_STARTS_WITH } from './models/OperatorCollection_STARTS_WITH';
export type { operatorCondition } from './models/operatorCondition';
export type { Order } from './models/Order';
export { OrderDisputeStatus } from './models/OrderDisputeStatus';
export type { OrderInformationFraudType } from './models/OrderInformationFraudType';
export type { OrderItem } from './models/OrderItem';
export type { OrderItemDto } from './models/OrderItemDto';
export type { OrderItemTrackingDto } from './models/OrderItemTrackingDto';
export type { OrderRefund } from './models/OrderRefund';
export { OrderStatus } from './models/OrderStatus';
export type { OrderTrackingEmailStatus } from './models/OrderTrackingEmailStatus';
export { OrderTrackingEmailStatusDto } from './models/OrderTrackingEmailStatusDto';
export type { OrderTrackingRecoveredStatus } from './models/OrderTrackingRecoveredStatus';
export { OrderTrackingRecoveredStatusDto } from './models/OrderTrackingRecoveredStatusDto';
export type { Payment } from './models/Payment';
export type { PaymentInfo } from './models/PaymentInfo';
export type { PaymentMethodIdDto } from './models/PaymentMethodIdDto';
export { PaymentMethodType } from './models/PaymentMethodType';
export { PaymentType } from './models/PaymentType';
export type { PercentageCostInfo } from './models/PercentageCostInfo';
export { Period } from './models/Period';
export type { PhoneWithCountryCode } from './models/PhoneWithCountryCode';
export type { PhotoDto } from './models/PhotoDto';
export type { Photos } from './models/Photos';
export type { PingPongAccount } from './models/PingPongAccount';
export { PlacementBoostSaleEnum } from './models/PlacementBoostSaleEnum';
export type { PlacementBoostSaleType } from './models/PlacementBoostSaleType';
export type { PlatformCostInfo } from './models/PlatformCostInfo';
export type { PlatformProduct } from './models/PlatformProduct';
export type { PlatformProductStore } from './models/PlatformProductStore';
export type { PlatformVariant } from './models/PlatformVariant';
export type { PlatformVariantDto } from './models/PlatformVariantDto';
export type { PriceConditionDto } from './models/PriceConditionDto';
export type { Prisma_JsonValue } from './models/Prisma_JsonValue';
export type { PrismaJson_AsyncTaskResult } from './models/PrismaJson_AsyncTaskResult';
export type { PrismaJson_AvailableSet } from './models/PrismaJson_AvailableSet';
export type { PrismaJson_bankInfo } from './models/PrismaJson_bankInfo';
export type { PrismaJson_BillingInfo } from './models/PrismaJson_BillingInfo';
export type { PrismaJson_Colors } from './models/PrismaJson_Colors';
export type { PrismaJson_ConditionCollection } from './models/PrismaJson_ConditionCollection';
export type { PrismaJson_CostInfo } from './models/PrismaJson_CostInfo';
export type { PrismaJson_CountryInformation } from './models/PrismaJson_CountryInformation';
export type { PrismaJson_DiscountBoostSale } from './models/PrismaJson_DiscountBoostSale';
export type { PrismaJson_DomainContactInfo } from './models/PrismaJson_DomainContactInfo';
export type { PrismaJson_FirebaseDeviceToken } from './models/PrismaJson_FirebaseDeviceToken';
export type { PrismaJson_HoldSetting } from './models/PrismaJson_HoldSetting';
export type { PrismaJson_MarginInfo } from './models/PrismaJson_MarginInfo';
export type { PrismaJson_Photos } from './models/PrismaJson_Photos';
export type { PrismaJson_PlacementBoostSaleType } from './models/PrismaJson_PlacementBoostSaleType';
export type { PrismaJson_PlatformCostInfo } from './models/PrismaJson_PlatformCostInfo';
export type { PrismaJson_ProductDiscountItems } from './models/PrismaJson_ProductDiscountItems';
export type { PrismaJson_ProductRequirementItems } from './models/PrismaJson_ProductRequirementItems';
export type { PrismaJson_RefundOrderItems } from './models/PrismaJson_RefundOrderItems';
export type { PrismaJson_RequestSourcingHistory } from './models/PrismaJson_RequestSourcingHistory';
export type { PrismaJson_SyncBalanceAmount } from './models/PrismaJson_SyncBalanceAmount';
export type { PrismaJson_ThemeNodes } from './models/PrismaJson_ThemeNodes';
export type { PrismaJson_ThemeSetting } from './models/PrismaJson_ThemeSetting';
export type { PrismaJson_ThemeStyle } from './models/PrismaJson_ThemeStyle';
export type { PrismaJson_Timezone } from './models/PrismaJson_Timezone';
export type { PrismaJson_TransactionDetails } from './models/PrismaJson_TransactionDetails';
export { PrismaJson_TransactionPaymentMethod } from './models/PrismaJson_TransactionPaymentMethod';
export type { PrismaJson_TypeOfFraudService } from './models/PrismaJson_TypeOfFraudService';
export type { PrismaJson_UnavailableBalance } from './models/PrismaJson_UnavailableBalance';
export type { PrismaJson_VariantComboItems } from './models/PrismaJson_VariantComboItems';
export type { PrismaJson_VariantOptions } from './models/PrismaJson_VariantOptions';
export type { PrismaJson_VariantOptionValues } from './models/PrismaJson_VariantOptionValues';
export type { Product } from './models/Product';
export type { ProductPerformance } from './models/ProductPerformance';
export type { ProductVariant } from './models/ProductVariant';
export type { RefundOrderDto } from './models/RefundOrderDto';
export { RefundType } from './models/RefundType';
export type { RegionalShippingFee } from './models/RegionalShippingFee';
export type { RegionalShippingFeeDto } from './models/RegionalShippingFeeDto';
export type { RejectRequestSourcingDto } from './models/RejectRequestSourcingDto';
export { RelatedProductType } from './models/RelatedProductType';
export type { RenewDomainDto } from './models/RenewDomainDto';
export type { RequestPayout } from './models/RequestPayout';
export { RequestPayoutStatus } from './models/RequestPayoutStatus';
export type { RequestSourcing } from './models/RequestSourcing';
export { RequestSourcingStatus } from './models/RequestSourcingStatus';
export type { Response } from './models/Response';
export type { Review } from './models/Review';
export type { SendEmailToListStoreDto } from './models/SendEmailToListStoreDto';
export type { Setting } from './models/Setting';
export type { SQLResult } from './models/SQLResult';
export { StatisticsDisplayType } from './models/StatisticsDisplayType';
export type { StatisticsOverviewAbandonedCheckout } from './models/StatisticsOverviewAbandonedCheckout';
export type { StatisticsOverviewConversionValue } from './models/StatisticsOverviewConversionValue';
export { statusRequestPayout } from './models/statusRequestPayout';
export type { Store } from './models/Store';
export { StoreEmailLogStatus } from './models/StoreEmailLogStatus';
export type { StorePerformance } from './models/StorePerformance';
export type { StoreProductPerformanceResp } from './models/StoreProductPerformanceResp';
export type { StoreProductProfit } from './models/StoreProductProfit';
export type { StoreRevenueOverTime } from './models/StoreRevenueOverTime';
export { StoreRole } from './models/StoreRole';
export { StoreStatus } from './models/StoreStatus';
export { StoreType } from './models/StoreType';
export type { StoreUser } from './models/StoreUser';
export type { SubscribeTopicDto } from './models/SubscribeTopicDto';
export type { SuggestionResponseDto } from './models/SuggestionResponseDto';
export type { SyncBalanceAmount } from './models/SyncBalanceAmount';
export { SyncTrackingStatus } from './models/SyncTrackingStatus';
export type { Tag } from './models/Tag';
export type { TagConditionDto } from './models/TagConditionDto';
export type { Theme } from './models/Theme';
export type { ThemeLibrary } from './models/ThemeLibrary';
export type { ThemePage } from './models/ThemePage';
export type { ThemeTemplate } from './models/ThemeTemplate';
export type { TiktokPixel } from './models/TiktokPixel';
export { TimeEmailMarketingUnit } from './models/TimeEmailMarketingUnit';
export type { Timezone } from './models/Timezone';
export { TimezoneDto } from './models/TimezoneDto';
export type { TopProductByOrder } from './models/TopProductByOrder';
export type { TopStoreByRevenue } from './models/TopStoreByRevenue';
export type { TopUpWalletDto } from './models/TopUpWalletDto';
export type { Transaction } from './models/Transaction';
export { TransactionStatus } from './models/TransactionStatus';
export { TransactionType } from './models/TransactionType';
export { TypeFulfillmentPrice } from './models/TypeFulfillmentPrice';
export { TypeOfFraud } from './models/TypeOfFraud';
export type { TypeOfFraudService } from './models/TypeOfFraudService';
export type { UnsubscribeEmailMarketingDto } from './models/UnsubscribeEmailMarketingDto';
export type { UnsubscribeTopicDto } from './models/UnsubscribeTopicDto';
export type { UpdateActiveStatusAutomationEmailMarketingDto } from './models/UpdateActiveStatusAutomationEmailMarketingDto';
export type { UpdateAutomationEmailMarketingDto } from './models/UpdateAutomationEmailMarketingDto';
export type { UpdateAutomationEmailMarketingOptions } from './models/UpdateAutomationEmailMarketingOptions';
export type { UpdateBankAccountDto } from './models/UpdateBankAccountDto';
export type { UpdateCampaignDto } from './models/UpdateCampaignDto';
export type { UpdateCollectionDto } from './models/UpdateCollectionDto';
export type { UpdateCollectionStatusDto } from './models/UpdateCollectionStatusDto';
export type { UpdateComboDto } from './models/UpdateComboDto';
export type { UpdateCombosDto } from './models/UpdateCombosDto';
export type { UpdateComboStatusDto } from './models/UpdateComboStatusDto';
export type { UpdateCrossSellStatusDto } from './models/UpdateCrossSellStatusDto';
export type { UpdateCurrencyDto } from './models/UpdateCurrencyDto';
export type { UpdateDiscountDto } from './models/UpdateDiscountDto';
export type { UpdateFbPixelDto } from './models/UpdateFbPixelDto';
export type { UpdateFulfillmentAgencyDto } from './models/UpdateFulfillmentAgencyDto';
export type { UpdateFulfillmentAgencyStatusDto } from './models/UpdateFulfillmentAgencyStatusDto';
export type { UpdateFulFillmentStatusError } from './models/UpdateFulFillmentStatusError';
export type { UpdateFulFillmentStatusResp } from './models/UpdateFulFillmentStatusResp';
export type { UpdateGADto } from './models/UpdateGADto';
export type { UpdateGroupPlatformVariantsDto } from './models/UpdateGroupPlatformVariantsDto';
export type { UpdateGTMDto } from './models/UpdateGTMDto';
export type { UpdateManyStorePaymentMethodDto } from './models/UpdateManyStorePaymentMethodDto';
export type { UpdateNotificationDto } from './models/UpdateNotificationDto';
export type { UpdateOrderDto } from './models/UpdateOrderDto';
export type { UpdateOrderRefundDto } from './models/UpdateOrderRefundDto';
export type { UpdateOrderRefundHistoryDto } from './models/UpdateOrderRefundHistoryDto';
export type { UpdateOrderStatusDto } from './models/UpdateOrderStatusDto';
export type { UpdateOrderTrackingDto } from './models/UpdateOrderTrackingDto';
export type { UpdatePaymentDto } from './models/UpdatePaymentDto';
export type { UpdatePingPongAccountDto } from './models/UpdatePingPongAccountDto';
export type { UpdatePlatformProductDto } from './models/UpdatePlatformProductDto';
export type { UpdatePlatformProductStatusDto } from './models/UpdatePlatformProductStatusDto';
export type { UpdatePlatformProductStatusesDto } from './models/UpdatePlatformProductStatusesDto';
export type { UpdatePlatformProductVariantDto } from './models/UpdatePlatformProductVariantDto';
export type { UpdatePlatformVariantDto } from './models/UpdatePlatformVariantDto';
export type { UpdatePlatformVariantsDto } from './models/UpdatePlatformVariantsDto';
export type { UpdatePlatformVariantStatusDto } from './models/UpdatePlatformVariantStatusDto';
export type { UpdateProductDto } from './models/UpdateProductDto';
export type { UpdateProductStatusDto } from './models/UpdateProductStatusDto';
export type { UpdateProductStatusesDto } from './models/UpdateProductStatusesDto';
export type { UpdateRequestPayoutDto } from './models/UpdateRequestPayoutDto';
export type { UpdateRequestSourcingDto } from './models/UpdateRequestSourcingDto';
export type { UpdateReviewDto } from './models/UpdateReviewDto';
export type { UpdateSettingDto } from './models/UpdateSettingDto';
export type { UpdateStaffDto } from './models/UpdateStaffDto';
export type { UpdateStoreDto } from './models/UpdateStoreDto';
export type { UpdateStorePaymentMethodDto } from './models/UpdateStorePaymentMethodDto';
export type { UpdateStoreStatusDto } from './models/UpdateStoreStatusDto';
export type { UpdateTemplateDto } from './models/UpdateTemplateDto';
export type { UpdateThemeDto } from './models/UpdateThemeDto';
export type { UpdateThemeLibraryDto } from './models/UpdateThemeLibraryDto';
export type { UpdateTiktokPixelDto } from './models/UpdateTiktokPixelDto';
export type { UpdateUserDto } from './models/UpdateUserDto';
export type { UpdateVariantDto } from './models/UpdateVariantDto';
export type { UpdateVariantsDto } from './models/UpdateVariantsDto';
export type { UpdateVariantsForSellerInDependenceDto } from './models/UpdateVariantsForSellerInDependenceDto';
export type { UpdateVariantStatusDto } from './models/UpdateVariantStatusDto';
export type { URLDto } from './models/URLDto';
export type { User } from './models/User';
export { UserRole } from './models/UserRole';
export type { VariantCombo } from './models/VariantCombo';
export type { VariantDto } from './models/VariantDto';
export type { VariantOptions } from './models/VariantOptions';
export type { VariantOptionValues } from './models/VariantOptionValues';
export type { Wallet } from './models/Wallet';
export { Week } from './models/Week';
export type { WithdrawWalletDto } from './models/WithdrawWalletDto';

export { MarketingService } from './services/MarketingService';
export { UploadService } from './services/UploadService';
