"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OrderTrackingEmailStatusDto = exports.OrderStatus = exports.OrderDisputeStatus = exports.OperatorCollection_STARTS_WITH = exports.OperatorCollection_NOT_EQUAL_TO = exports.OperatorCollection_NOT_CONTAIN = exports.OperatorCollection_LESS_TO = exports.OperatorCollection_GREATER_TO = exports.OperatorCollection_EQUAL_TO = exports.OperatorCollection_ENDS_WITH = exports.OperatorCollection_CONTAIN = exports.NotificationType = exports.MarketingType = exports.LogoSize = exports.FulfillmentStatus = exports.FulfillmentAgencyType = exports.FulfillmentAgencyStatus = exports.FulfillmentAgencyRole = exports.FraudStatusType = exports.FraudDetectionType = exports.FraudDetectionStatusType = exports.EventOrderFraud = exports.ESendMailStatus = exports.EnvironmentType = exports.DomainOrigin = exports.DiscountForQuantityType = exports.DiscountBoostSaleType = exports.CustomDomainStatus = exports.CurrencyType = exports.CurrencyCode = exports.CostCalculationMethod = exports.CombineOperator = exports.CollectionType = exports.CollectionStatus = exports.CollectionField_tag = exports.CollectionField_price = exports.CollectionField_name = exports.BoughtTogetherType = exports.BoostSaleType = exports.BoostSaleTriggerType = exports.AsyncTaskType = exports.AsyncTaskStatus = exports.ActiveDetection = exports.ActionOrderFraud = exports.OpenAPI = exports.CancelError = exports.CancelablePromise = exports.BaseHttpRequest = exports.ApiError = exports.ClientApi = void 0;
exports.UserService = exports.UploadService = exports.MarketingService = exports.AuthService = exports.Week = exports.UserRole = exports.TypeOfFraud = exports.TypeFulfillmentPrice = exports.TransactionType = exports.TransactionStatus = exports.TimezoneDto = exports.TimeEmailMarketingUnit = exports.SyncTrackingStatus = exports.SubscriptionFeatureType = exports.StoreType = exports.StoreStatus = exports.StoreRole = exports.statusRequestPayout = exports.StatisticsDisplayType = exports.SendEmailToListStoreStatus = exports.RequestSourcingStatus = exports.RequestPayoutStatus = exports.RelatedProductType = exports.RefundType = exports.PrismaJson_TransactionPaymentMethod = exports.PlacementBoostSaleEnum = exports.Period = exports.PaymentType = exports.PaymentMethodType = exports.OrderTrackingRecoveredStatusDto = void 0;
/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
var ClientApi_1 = require("./ClientApi");
Object.defineProperty(exports, "ClientApi", { enumerable: true, get: function () { return ClientApi_1.ClientApi; } });
var ApiError_1 = require("./core/ApiError");
Object.defineProperty(exports, "ApiError", { enumerable: true, get: function () { return ApiError_1.ApiError; } });
var BaseHttpRequest_1 = require("./core/BaseHttpRequest");
Object.defineProperty(exports, "BaseHttpRequest", { enumerable: true, get: function () { return BaseHttpRequest_1.BaseHttpRequest; } });
var CancelablePromise_1 = require("./core/CancelablePromise");
Object.defineProperty(exports, "CancelablePromise", { enumerable: true, get: function () { return CancelablePromise_1.CancelablePromise; } });
Object.defineProperty(exports, "CancelError", { enumerable: true, get: function () { return CancelablePromise_1.CancelError; } });
var OpenAPI_1 = require("./core/OpenAPI");
Object.defineProperty(exports, "OpenAPI", { enumerable: true, get: function () { return OpenAPI_1.OpenAPI; } });
var ActionOrderFraud_1 = require("./models/ActionOrderFraud");
Object.defineProperty(exports, "ActionOrderFraud", { enumerable: true, get: function () { return ActionOrderFraud_1.ActionOrderFraud; } });
var ActiveDetection_1 = require("./models/ActiveDetection");
Object.defineProperty(exports, "ActiveDetection", { enumerable: true, get: function () { return ActiveDetection_1.ActiveDetection; } });
var AsyncTaskStatus_1 = require("./models/AsyncTaskStatus");
Object.defineProperty(exports, "AsyncTaskStatus", { enumerable: true, get: function () { return AsyncTaskStatus_1.AsyncTaskStatus; } });
var AsyncTaskType_1 = require("./models/AsyncTaskType");
Object.defineProperty(exports, "AsyncTaskType", { enumerable: true, get: function () { return AsyncTaskType_1.AsyncTaskType; } });
var BoostSaleTriggerType_1 = require("./models/BoostSaleTriggerType");
Object.defineProperty(exports, "BoostSaleTriggerType", { enumerable: true, get: function () { return BoostSaleTriggerType_1.BoostSaleTriggerType; } });
var BoostSaleType_1 = require("./models/BoostSaleType");
Object.defineProperty(exports, "BoostSaleType", { enumerable: true, get: function () { return BoostSaleType_1.BoostSaleType; } });
var BoughtTogetherType_1 = require("./models/BoughtTogetherType");
Object.defineProperty(exports, "BoughtTogetherType", { enumerable: true, get: function () { return BoughtTogetherType_1.BoughtTogetherType; } });
var CollectionField_name_1 = require("./models/CollectionField_name");
Object.defineProperty(exports, "CollectionField_name", { enumerable: true, get: function () { return CollectionField_name_1.CollectionField_name; } });
var CollectionField_price_1 = require("./models/CollectionField_price");
Object.defineProperty(exports, "CollectionField_price", { enumerable: true, get: function () { return CollectionField_price_1.CollectionField_price; } });
var CollectionField_tag_1 = require("./models/CollectionField_tag");
Object.defineProperty(exports, "CollectionField_tag", { enumerable: true, get: function () { return CollectionField_tag_1.CollectionField_tag; } });
var CollectionStatus_1 = require("./models/CollectionStatus");
Object.defineProperty(exports, "CollectionStatus", { enumerable: true, get: function () { return CollectionStatus_1.CollectionStatus; } });
var CollectionType_1 = require("./models/CollectionType");
Object.defineProperty(exports, "CollectionType", { enumerable: true, get: function () { return CollectionType_1.CollectionType; } });
var CombineOperator_1 = require("./models/CombineOperator");
Object.defineProperty(exports, "CombineOperator", { enumerable: true, get: function () { return CombineOperator_1.CombineOperator; } });
var CostCalculationMethod_1 = require("./models/CostCalculationMethod");
Object.defineProperty(exports, "CostCalculationMethod", { enumerable: true, get: function () { return CostCalculationMethod_1.CostCalculationMethod; } });
var CurrencyCode_1 = require("./models/CurrencyCode");
Object.defineProperty(exports, "CurrencyCode", { enumerable: true, get: function () { return CurrencyCode_1.CurrencyCode; } });
var CurrencyType_1 = require("./models/CurrencyType");
Object.defineProperty(exports, "CurrencyType", { enumerable: true, get: function () { return CurrencyType_1.CurrencyType; } });
var CustomDomainStatus_1 = require("./models/CustomDomainStatus");
Object.defineProperty(exports, "CustomDomainStatus", { enumerable: true, get: function () { return CustomDomainStatus_1.CustomDomainStatus; } });
var DiscountBoostSaleType_1 = require("./models/DiscountBoostSaleType");
Object.defineProperty(exports, "DiscountBoostSaleType", { enumerable: true, get: function () { return DiscountBoostSaleType_1.DiscountBoostSaleType; } });
var DiscountForQuantityType_1 = require("./models/DiscountForQuantityType");
Object.defineProperty(exports, "DiscountForQuantityType", { enumerable: true, get: function () { return DiscountForQuantityType_1.DiscountForQuantityType; } });
var DomainOrigin_1 = require("./models/DomainOrigin");
Object.defineProperty(exports, "DomainOrigin", { enumerable: true, get: function () { return DomainOrigin_1.DomainOrigin; } });
var EnvironmentType_1 = require("./models/EnvironmentType");
Object.defineProperty(exports, "EnvironmentType", { enumerable: true, get: function () { return EnvironmentType_1.EnvironmentType; } });
var ESendMailStatus_1 = require("./models/ESendMailStatus");
Object.defineProperty(exports, "ESendMailStatus", { enumerable: true, get: function () { return ESendMailStatus_1.ESendMailStatus; } });
var EventOrderFraud_1 = require("./models/EventOrderFraud");
Object.defineProperty(exports, "EventOrderFraud", { enumerable: true, get: function () { return EventOrderFraud_1.EventOrderFraud; } });
var FraudDetectionStatusType_1 = require("./models/FraudDetectionStatusType");
Object.defineProperty(exports, "FraudDetectionStatusType", { enumerable: true, get: function () { return FraudDetectionStatusType_1.FraudDetectionStatusType; } });
var FraudDetectionType_1 = require("./models/FraudDetectionType");
Object.defineProperty(exports, "FraudDetectionType", { enumerable: true, get: function () { return FraudDetectionType_1.FraudDetectionType; } });
var FraudStatusType_1 = require("./models/FraudStatusType");
Object.defineProperty(exports, "FraudStatusType", { enumerable: true, get: function () { return FraudStatusType_1.FraudStatusType; } });
var FulfillmentAgencyRole_1 = require("./models/FulfillmentAgencyRole");
Object.defineProperty(exports, "FulfillmentAgencyRole", { enumerable: true, get: function () { return FulfillmentAgencyRole_1.FulfillmentAgencyRole; } });
var FulfillmentAgencyStatus_1 = require("./models/FulfillmentAgencyStatus");
Object.defineProperty(exports, "FulfillmentAgencyStatus", { enumerable: true, get: function () { return FulfillmentAgencyStatus_1.FulfillmentAgencyStatus; } });
var FulfillmentAgencyType_1 = require("./models/FulfillmentAgencyType");
Object.defineProperty(exports, "FulfillmentAgencyType", { enumerable: true, get: function () { return FulfillmentAgencyType_1.FulfillmentAgencyType; } });
var FulfillmentStatus_1 = require("./models/FulfillmentStatus");
Object.defineProperty(exports, "FulfillmentStatus", { enumerable: true, get: function () { return FulfillmentStatus_1.FulfillmentStatus; } });
var LogoSize_1 = require("./models/LogoSize");
Object.defineProperty(exports, "LogoSize", { enumerable: true, get: function () { return LogoSize_1.LogoSize; } });
var MarketingType_1 = require("./models/MarketingType");
Object.defineProperty(exports, "MarketingType", { enumerable: true, get: function () { return MarketingType_1.MarketingType; } });
var NotificationType_1 = require("./models/NotificationType");
Object.defineProperty(exports, "NotificationType", { enumerable: true, get: function () { return NotificationType_1.NotificationType; } });
var OperatorCollection_CONTAIN_1 = require("./models/OperatorCollection_CONTAIN");
Object.defineProperty(exports, "OperatorCollection_CONTAIN", { enumerable: true, get: function () { return OperatorCollection_CONTAIN_1.OperatorCollection_CONTAIN; } });
var OperatorCollection_ENDS_WITH_1 = require("./models/OperatorCollection_ENDS_WITH");
Object.defineProperty(exports, "OperatorCollection_ENDS_WITH", { enumerable: true, get: function () { return OperatorCollection_ENDS_WITH_1.OperatorCollection_ENDS_WITH; } });
var OperatorCollection_EQUAL_TO_1 = require("./models/OperatorCollection_EQUAL_TO");
Object.defineProperty(exports, "OperatorCollection_EQUAL_TO", { enumerable: true, get: function () { return OperatorCollection_EQUAL_TO_1.OperatorCollection_EQUAL_TO; } });
var OperatorCollection_GREATER_TO_1 = require("./models/OperatorCollection_GREATER_TO");
Object.defineProperty(exports, "OperatorCollection_GREATER_TO", { enumerable: true, get: function () { return OperatorCollection_GREATER_TO_1.OperatorCollection_GREATER_TO; } });
var OperatorCollection_LESS_TO_1 = require("./models/OperatorCollection_LESS_TO");
Object.defineProperty(exports, "OperatorCollection_LESS_TO", { enumerable: true, get: function () { return OperatorCollection_LESS_TO_1.OperatorCollection_LESS_TO; } });
var OperatorCollection_NOT_CONTAIN_1 = require("./models/OperatorCollection_NOT_CONTAIN");
Object.defineProperty(exports, "OperatorCollection_NOT_CONTAIN", { enumerable: true, get: function () { return OperatorCollection_NOT_CONTAIN_1.OperatorCollection_NOT_CONTAIN; } });
var OperatorCollection_NOT_EQUAL_TO_1 = require("./models/OperatorCollection_NOT_EQUAL_TO");
Object.defineProperty(exports, "OperatorCollection_NOT_EQUAL_TO", { enumerable: true, get: function () { return OperatorCollection_NOT_EQUAL_TO_1.OperatorCollection_NOT_EQUAL_TO; } });
var OperatorCollection_STARTS_WITH_1 = require("./models/OperatorCollection_STARTS_WITH");
Object.defineProperty(exports, "OperatorCollection_STARTS_WITH", { enumerable: true, get: function () { return OperatorCollection_STARTS_WITH_1.OperatorCollection_STARTS_WITH; } });
var OrderDisputeStatus_1 = require("./models/OrderDisputeStatus");
Object.defineProperty(exports, "OrderDisputeStatus", { enumerable: true, get: function () { return OrderDisputeStatus_1.OrderDisputeStatus; } });
var OrderStatus_1 = require("./models/OrderStatus");
Object.defineProperty(exports, "OrderStatus", { enumerable: true, get: function () { return OrderStatus_1.OrderStatus; } });
var OrderTrackingEmailStatusDto_1 = require("./models/OrderTrackingEmailStatusDto");
Object.defineProperty(exports, "OrderTrackingEmailStatusDto", { enumerable: true, get: function () { return OrderTrackingEmailStatusDto_1.OrderTrackingEmailStatusDto; } });
var OrderTrackingRecoveredStatusDto_1 = require("./models/OrderTrackingRecoveredStatusDto");
Object.defineProperty(exports, "OrderTrackingRecoveredStatusDto", { enumerable: true, get: function () { return OrderTrackingRecoveredStatusDto_1.OrderTrackingRecoveredStatusDto; } });
var PaymentMethodType_1 = require("./models/PaymentMethodType");
Object.defineProperty(exports, "PaymentMethodType", { enumerable: true, get: function () { return PaymentMethodType_1.PaymentMethodType; } });
var PaymentType_1 = require("./models/PaymentType");
Object.defineProperty(exports, "PaymentType", { enumerable: true, get: function () { return PaymentType_1.PaymentType; } });
var Period_1 = require("./models/Period");
Object.defineProperty(exports, "Period", { enumerable: true, get: function () { return Period_1.Period; } });
var PlacementBoostSaleEnum_1 = require("./models/PlacementBoostSaleEnum");
Object.defineProperty(exports, "PlacementBoostSaleEnum", { enumerable: true, get: function () { return PlacementBoostSaleEnum_1.PlacementBoostSaleEnum; } });
var PrismaJson_TransactionPaymentMethod_1 = require("./models/PrismaJson_TransactionPaymentMethod");
Object.defineProperty(exports, "PrismaJson_TransactionPaymentMethod", { enumerable: true, get: function () { return PrismaJson_TransactionPaymentMethod_1.PrismaJson_TransactionPaymentMethod; } });
var RefundType_1 = require("./models/RefundType");
Object.defineProperty(exports, "RefundType", { enumerable: true, get: function () { return RefundType_1.RefundType; } });
var RelatedProductType_1 = require("./models/RelatedProductType");
Object.defineProperty(exports, "RelatedProductType", { enumerable: true, get: function () { return RelatedProductType_1.RelatedProductType; } });
var RequestPayoutStatus_1 = require("./models/RequestPayoutStatus");
Object.defineProperty(exports, "RequestPayoutStatus", { enumerable: true, get: function () { return RequestPayoutStatus_1.RequestPayoutStatus; } });
var RequestSourcingStatus_1 = require("./models/RequestSourcingStatus");
Object.defineProperty(exports, "RequestSourcingStatus", { enumerable: true, get: function () { return RequestSourcingStatus_1.RequestSourcingStatus; } });
var SendEmailToListStoreStatus_1 = require("./models/SendEmailToListStoreStatus");
Object.defineProperty(exports, "SendEmailToListStoreStatus", { enumerable: true, get: function () { return SendEmailToListStoreStatus_1.SendEmailToListStoreStatus; } });
var StatisticsDisplayType_1 = require("./models/StatisticsDisplayType");
Object.defineProperty(exports, "StatisticsDisplayType", { enumerable: true, get: function () { return StatisticsDisplayType_1.StatisticsDisplayType; } });
var statusRequestPayout_1 = require("./models/statusRequestPayout");
Object.defineProperty(exports, "statusRequestPayout", { enumerable: true, get: function () { return statusRequestPayout_1.statusRequestPayout; } });
var StoreRole_1 = require("./models/StoreRole");
Object.defineProperty(exports, "StoreRole", { enumerable: true, get: function () { return StoreRole_1.StoreRole; } });
var StoreStatus_1 = require("./models/StoreStatus");
Object.defineProperty(exports, "StoreStatus", { enumerable: true, get: function () { return StoreStatus_1.StoreStatus; } });
var StoreType_1 = require("./models/StoreType");
Object.defineProperty(exports, "StoreType", { enumerable: true, get: function () { return StoreType_1.StoreType; } });
var SubscriptionFeatureType_1 = require("./models/SubscriptionFeatureType");
Object.defineProperty(exports, "SubscriptionFeatureType", { enumerable: true, get: function () { return SubscriptionFeatureType_1.SubscriptionFeatureType; } });
var SyncTrackingStatus_1 = require("./models/SyncTrackingStatus");
Object.defineProperty(exports, "SyncTrackingStatus", { enumerable: true, get: function () { return SyncTrackingStatus_1.SyncTrackingStatus; } });
var TimeEmailMarketingUnit_1 = require("./models/TimeEmailMarketingUnit");
Object.defineProperty(exports, "TimeEmailMarketingUnit", { enumerable: true, get: function () { return TimeEmailMarketingUnit_1.TimeEmailMarketingUnit; } });
var TimezoneDto_1 = require("./models/TimezoneDto");
Object.defineProperty(exports, "TimezoneDto", { enumerable: true, get: function () { return TimezoneDto_1.TimezoneDto; } });
var TransactionStatus_1 = require("./models/TransactionStatus");
Object.defineProperty(exports, "TransactionStatus", { enumerable: true, get: function () { return TransactionStatus_1.TransactionStatus; } });
var TransactionType_1 = require("./models/TransactionType");
Object.defineProperty(exports, "TransactionType", { enumerable: true, get: function () { return TransactionType_1.TransactionType; } });
var TypeFulfillmentPrice_1 = require("./models/TypeFulfillmentPrice");
Object.defineProperty(exports, "TypeFulfillmentPrice", { enumerable: true, get: function () { return TypeFulfillmentPrice_1.TypeFulfillmentPrice; } });
var TypeOfFraud_1 = require("./models/TypeOfFraud");
Object.defineProperty(exports, "TypeOfFraud", { enumerable: true, get: function () { return TypeOfFraud_1.TypeOfFraud; } });
var UserRole_1 = require("./models/UserRole");
Object.defineProperty(exports, "UserRole", { enumerable: true, get: function () { return UserRole_1.UserRole; } });
var Week_1 = require("./models/Week");
Object.defineProperty(exports, "Week", { enumerable: true, get: function () { return Week_1.Week; } });
var AuthService_1 = require("./services/AuthService");
Object.defineProperty(exports, "AuthService", { enumerable: true, get: function () { return AuthService_1.AuthService; } });
var MarketingService_1 = require("./services/MarketingService");
Object.defineProperty(exports, "MarketingService", { enumerable: true, get: function () { return MarketingService_1.MarketingService; } });
var UploadService_1 = require("./services/UploadService");
Object.defineProperty(exports, "UploadService", { enumerable: true, get: function () { return UploadService_1.UploadService; } });
var UserService_1 = require("./services/UserService");
Object.defineProperty(exports, "UserService", { enumerable: true, get: function () { return UserService_1.UserService; } });
