/**
 * Construct a type with a set of properties K of type T
 */
export type Record_Permission_or_SuperAdminPermission_or_SellerPermission_boolean_or_undefined_ = {
    SUPER_ADMIN_VIEW_PLATFORM_PERFORMANCE: boolean;
    SUPER_ADMIN_VIEW_MARKETING_PERFORMANCE: boolean;
    SUPER_ADMIN_VIEW_AGENCY: boolean;
    SUPER_ADMIN_ADD_AGENCY: boolean;
    SUPER_ADMIN_REVENUE_CEILING: boolean;
    SUPER_ADMIN_VIEW_REFERRAL_OVERVIEW: boolean;
    SUPER_ADMIN_VIEW_REFERRAL_SALES: boolean;
    SUPER_ADMIN_EDIT_REFERRAL_SALES: boolean;
    SUPER_ADMIN_VIEW_STORE_IN_REFERRAL: boolean;
    SUPER_ADMIN_ADD_REFERRAL_CODE: boolean;
    SUPER_ADMIN_VIEW_ACCOUNT_IN_PERMISSION: boolean;
    SUPER_ADMIN_ADD_ACCOUNT_IN_PERMISSION: boolean;
    SUPER_ADMIN_EDIT_ACCOUNT_IN_PERMISSION: boolean;
    SUPER_ADMIN_VIEW_ROLE: boolean;
    SUPER_ADMIN_ADD_ROLE: boolean;
    SUPER_ADMIN_EDIT_ROLE: boolean;
    SUPER_ADMIN_DELETE_ROLE: boolean;
    SELLER_REQUEST_PRODUCT: boolean;
    SELLER_EDIT_PRODUCT: boolean;
    SELLER_DUPLICATE_PRODUCT: boolean;
    SELLER_CREATE_AND_DUPLICATE_PRODUCT: boolean;
    SELLER_DELETE_PRODUCT: boolean;
    SELLER_VIEW_STORE_PERFORMANCE: boolean;
    SELLER_VIEW_LIVE_VIEW: boolean;
    SELLER_EDIT_THEME: boolean;
    SELLER_EDIT_DOMAIN: boolean;
    SELLER_VIEW_TRAFFIC_SOURCES: boolean;
    SELLER_VIEW_PRODUCT_PERFORMANCE: boolean;
    SELLER_TRACK_ORDER_STATUS: boolean;
    SELLER_MANAGE_ABANDONED_CHECKOUT: boolean;
    SELLER_REFUND_ORDER: boolean;
    SELLER_MANAGE_CROSS_SELLING: boolean;
    SELLER_MANAGE_UP_SELLING: boolean;
    SELLER_MANAGE_EMAIL_MARKETING: boolean;
    SELLER_REQUEST_PAYOUT: boolean;
    SELLER_VIEW_TRANSACTION: boolean;
    SELLER_SETUP_PAYMENT_METHODS: boolean;
    SELLER_MANAGE_PAYMENT_PROVIDERS: boolean;
    SELLER_MANAGE_PAYMENT_CARDS: boolean;
    SELLER_MANAGE_STORE_SETTINGS: boolean;
    SELLER_MANAGE_SHIPPING: boolean;
    SELLER_MANAGE_CURRENCY: boolean;
    SELLER_MANAGE_POLICIES: boolean;
    SELLER_MANAGE_ANALYTICS_TOOLS: boolean;
};
