"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FulfillmentPermissions = void 0;
/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
var FulfillmentPermissions;
(function (FulfillmentPermissions) {
    FulfillmentPermissions["FULFILLMENT_AGENCY_VIEW_PLATFORM_PERFORMANCE"] = "FULFILLMENT_AGENCY_VIEW_PLATFORM_PERFORMANCE";
    FulfillmentPermissions["FULFILLMENT_AGENCY_VIEW_PRODUCT_PERFORMANCE"] = "FULFILLMENT_AGENCY_VIEW_PRODUCT_PERFORMANCE";
    FulfillmentPermissions["FULFILLMENT_AGENCY_VIEW_LIVE_VIEW"] = "FULFILLMENT_AGENCY_VIEW_LIVE_VIEW";
    FulfillmentPermissions["FULFILLMENT_AGENCY_VIEW_ORDER"] = "FULFILLMENT_AGENCY_VIEW_ORDER";
    FulfillmentPermissions["FULFILLMENT_AGENCY_VIEW_ORDER_FINANCIAL_DETAIL"] = "FULFILLMENT_AGENCY_VIEW_ORDER_FINANCIAL_DETAIL";
    FulfillmentPermissions["FULFILLMENT_AGENCY_REFUND_ORDER"] = "FULFILLMENT_AGENCY_REFUND_ORDER";
    FulfillmentPermissions["FULFILLMENT_AGENCY_IMPORT_AND_EXPORT_ORDER"] = "FULFILLMENT_AGENCY_IMPORT_AND_EXPORT_ORDER";
    FulfillmentPermissions["FULFILLMENT_AGENCY_MANAGE_PRODUCT_REQUESTING"] = "FULFILLMENT_AGENCY_MANAGE_PRODUCT_REQUESTING";
    FulfillmentPermissions["FULFILLMENT_AGENCY_MANAGE_PRODUCT_CATALOG"] = "FULFILLMENT_AGENCY_MANAGE_PRODUCT_CATALOG";
    FulfillmentPermissions["FULFILLMENT_AGENCY_MANAGE_FINANCE_TRANSACTION"] = "FULFILLMENT_AGENCY_MANAGE_FINANCE_TRANSACTION";
    FulfillmentPermissions["FULFILLMENT_AGENCY_MANAGE_FINANCE_ACCOUNTANCY"] = "FULFILLMENT_AGENCY_MANAGE_FINANCE_ACCOUNTANCY";
    FulfillmentPermissions["FULFILLMENT_AGENCY_VIEW_STORE_MANAGEMENT"] = "FULFILLMENT_AGENCY_VIEW_STORE_MANAGEMENT";
    FulfillmentPermissions["FULFILLMENT_AGENCY_APPROVE_STORE_AND_ASSIGN_GATE"] = "FULFILLMENT_AGENCY_APPROVE_STORE_AND_ASSIGN_GATE";
    FulfillmentPermissions["FULFILLMENT_AGENCY_SETTING_PAYMENT"] = "FULFILLMENT_AGENCY_SETTING_PAYMENT";
    FulfillmentPermissions["FULFILLMENT_AGENCY_SETTING_PAYOUT_REQUEST"] = "FULFILLMENT_AGENCY_SETTING_PAYOUT_REQUEST";
    FulfillmentPermissions["FULFILLMENT_AGENCY_SETTING_POLICY"] = "FULFILLMENT_AGENCY_SETTING_POLICY";
    FulfillmentPermissions["FULFILLMENT_AGENCY_SETTING_FEE_AND_HOLD"] = "FULFILLMENT_AGENCY_SETTING_FEE_AND_HOLD";
    FulfillmentPermissions["FULFILLMENT_AGENCY_SETTING_CONNECT_TO_BETTASUP"] = "FULFILLMENT_AGENCY_SETTING_CONNECT_TO_BETTASUP";
    FulfillmentPermissions["FULFILLMENT_AGENCY_SETTING_REFUND_EXEMPTION"] = "FULFILLMENT_AGENCY_SETTING_REFUND_EXEMPTION";
    FulfillmentPermissions["FULFILLMENT_AGENCY_SETTING_DEFAULT_COLLECTION"] = "FULFILLMENT_AGENCY_SETTING_DEFAULT_COLLECTION";
    FulfillmentPermissions["FULFILLMENT_AGENCY_SETTING_ADDITIONAL_COST"] = "FULFILLMENT_AGENCY_SETTING_ADDITIONAL_COST";
    FulfillmentPermissions["FULFILLMENT_AGENCY_VIEW_INCLUSIVE_FEE"] = "FULFILLMENT_AGENCY_VIEW_INCLUSIVE_FEE";
})(FulfillmentPermissions || (exports.FulfillmentPermissions = FulfillmentPermissions = {}));
