import type { _36_Enums_FulfillmentPlatformIntegrationStatus } from './_36_Enums_FulfillmentPlatformIntegrationStatus';
export type FulfillmentPlatformIntegrationStatus = _36_Enums_FulfillmentPlatformIntegrationStatus;
