import type { PrismaJson_PlatformCostInfo } from './PrismaJson_PlatformCostInfo';
import type { PrismaJson_VariantOptionValues } from './PrismaJson_VariantOptionValues';
export type DefaultSelection_Prisma__36_PlatformVariantPayload_ = {
    fulfillmentPlatformVariantId: string;
    groupPlatformVariantId: number;
    cost: PrismaJson_PlatformCostInfo;
    supplierPrice: number;
    price: number;
    photo: string;
    isEnable: boolean;
    variantOption: PrismaJson_VariantOptionValues;
    SKU: string;
    deleted: boolean;
    platformProductId: number;
    isActive: boolean;
    name: string;
    updatedAt: string;
    createdAt: string;
    id: number;
};
