/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */

export enum NotificationType {
  STORE_APPROVED = 'STORE_APPROVED',
  STORE_REJECTED = 'STORE_REJECTED',
  STORE_ACTIVATED = 'STORE_ACTIVATED',
  STORE_SUSPENDED = 'STORE_SUSPENDED',
  STORE_REQUESTING = 'STORE_REQUESTING',
  PAYOUT_REQUESTING = 'PAYOUT_REQUESTING',
  PAYOUT_APPROVED = 'PAYOUT_APPROVED',
  PAYOUT_REJECTED = 'PAYOUT_REJECTED',
  ORDER_DISPUTED = 'ORDER_DISPUTED',
  ORDER_REFUNDED = 'ORDER_REFUNDED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  FRAUD_DETECTED = 'FRAUD_DETECTED',
  BROADCAST = 'BROADCAST',
}
