import type { BaseHttpRequest } from './core/BaseHttpRequest';
import type { OpenAPIConfig } from './core/OpenAPI';
import { AsyncTaskService } from './services/AsyncTaskService';
import { AuthService } from './services/AuthService';
import { BankAccountService } from './services/BankAccountService';
import { BoostSalesService } from './services/BoostSalesService';
import { CurrencyService } from './services/CurrencyService';
import { DefaultService } from './services/DefaultService';
import { FulfillmentAgencyService } from './services/FulfillmentAgencyService';
import { GroupPlatformVariantService } from './services/GroupPlatformVariantService';
import { NotificationService } from './services/NotificationService';
import { OrderService } from './services/OrderService';
import { OrderRefundsService } from './services/OrderRefundsService';
import { PaymentService } from './services/PaymentService';
import { PerformanceService } from './services/PerformanceService';
import { PingPongAccountService } from './services/PingPongAccountService';
import { PingPongAccountV2Service } from './services/PingPongAccountV2Service';
import { PlatformProductService } from './services/PlatformProductService';
import { PlatformVariantService } from './services/PlatformVariantService';
import { ProductService } from './services/ProductService';
import { RequestPayoutService } from './services/RequestPayoutService';
import { RequestSourcingService } from './services/RequestSourcingService';
import { SettingService } from './services/SettingService';
import { StoreService } from './services/StoreService';
import { StoreTagService } from './services/StoreTagService';
import { TagService } from './services/TagService';
import { ThemeLibraryService } from './services/ThemeLibraryService';
import { TransactionService } from './services/TransactionService';
import { UploadService } from './services/UploadService';
import { UserService } from './services/UserService';
import { VariantService } from './services/VariantService';
import { VariantComboService } from './services/VariantComboService';
import { WalletService } from './services/WalletService';
type HttpRequestConstructor = new (config: OpenAPIConfig) => BaseHttpRequest;
export declare class ClientApi {
    readonly asyncTask: AsyncTaskService;
    readonly auth: AuthService;
    readonly bankAccount: BankAccountService;
    readonly boostSales: BoostSalesService;
    readonly currency: CurrencyService;
    readonly default: DefaultService;
    readonly fulfillmentAgency: FulfillmentAgencyService;
    readonly groupPlatformVariant: GroupPlatformVariantService;
    readonly notification: NotificationService;
    readonly order: OrderService;
    readonly orderRefunds: OrderRefundsService;
    readonly payment: PaymentService;
    readonly performance: PerformanceService;
    readonly pingPongAccount: PingPongAccountService;
    readonly pingPongAccountV2: PingPongAccountV2Service;
    readonly platformProduct: PlatformProductService;
    readonly platformVariant: PlatformVariantService;
    readonly product: ProductService;
    readonly requestPayout: RequestPayoutService;
    readonly requestSourcing: RequestSourcingService;
    readonly setting: SettingService;
    readonly store: StoreService;
    readonly storeTag: StoreTagService;
    readonly tag: TagService;
    readonly themeLibrary: ThemeLibraryService;
    readonly transaction: TransactionService;
    readonly upload: UploadService;
    readonly user: UserService;
    readonly variant: VariantService;
    readonly variantCombo: VariantComboService;
    readonly wallet: WalletService;
    readonly request: BaseHttpRequest;
    constructor(config?: Partial<OpenAPIConfig>, HttpRequest?: HttpRequestConstructor);
}
export {};
