"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserService = exports.UploadService = exports.TransactionService = exports.ThemeTemplateService = exports.StoreService = exports.SettingService = exports.ProductTagService = exports.ProductService = exports.PlatformVariantService = exports.PlatformProductService = exports.PaymentService = exports.OrderService = exports.DefaultService = exports.CurrencyService = exports.AuthService = exports.UserRole = exports.TransactionStatus = exports.StoreStatus = exports.StoreRole = exports.StoreOrderBy = exports.Prisma_SortOrder = exports.PaymentType = exports.FulfillmentStatus = exports.CreateOrderDto = exports.OpenAPI = exports.CancelError = exports.CancelablePromise = exports.BaseHttpRequest = exports.ApiError = exports.ClientApi = void 0;
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
var ClientApi_1 = require("./ClientApi");
Object.defineProperty(exports, "ClientApi", { enumerable: true, get: function () { return ClientApi_1.ClientApi; } });
var ApiError_1 = require("./core/ApiError");
Object.defineProperty(exports, "ApiError", { enumerable: true, get: function () { return ApiError_1.ApiError; } });
var BaseHttpRequest_1 = require("./core/BaseHttpRequest");
Object.defineProperty(exports, "BaseHttpRequest", { enumerable: true, get: function () { return BaseHttpRequest_1.BaseHttpRequest; } });
var CancelablePromise_1 = require("./core/CancelablePromise");
Object.defineProperty(exports, "CancelablePromise", { enumerable: true, get: function () { return CancelablePromise_1.CancelablePromise; } });
Object.defineProperty(exports, "CancelError", { enumerable: true, get: function () { return CancelablePromise_1.CancelError; } });
var OpenAPI_1 = require("./core/OpenAPI");
Object.defineProperty(exports, "OpenAPI", { enumerable: true, get: function () { return OpenAPI_1.OpenAPI; } });
var CreateOrderDto_1 = require("./models/CreateOrderDto");
Object.defineProperty(exports, "CreateOrderDto", { enumerable: true, get: function () { return CreateOrderDto_1.CreateOrderDto; } });
var FulfillmentStatus_1 = require("./models/FulfillmentStatus");
Object.defineProperty(exports, "FulfillmentStatus", { enumerable: true, get: function () { return FulfillmentStatus_1.FulfillmentStatus; } });
var PaymentType_1 = require("./models/PaymentType");
Object.defineProperty(exports, "PaymentType", { enumerable: true, get: function () { return PaymentType_1.PaymentType; } });
var Prisma_SortOrder_1 = require("./models/Prisma_SortOrder");
Object.defineProperty(exports, "Prisma_SortOrder", { enumerable: true, get: function () { return Prisma_SortOrder_1.Prisma_SortOrder; } });
var StoreOrderBy_1 = require("./models/StoreOrderBy");
Object.defineProperty(exports, "StoreOrderBy", { enumerable: true, get: function () { return StoreOrderBy_1.StoreOrderBy; } });
var StoreRole_1 = require("./models/StoreRole");
Object.defineProperty(exports, "StoreRole", { enumerable: true, get: function () { return StoreRole_1.StoreRole; } });
var StoreStatus_1 = require("./models/StoreStatus");
Object.defineProperty(exports, "StoreStatus", { enumerable: true, get: function () { return StoreStatus_1.StoreStatus; } });
var TransactionStatus_1 = require("./models/TransactionStatus");
Object.defineProperty(exports, "TransactionStatus", { enumerable: true, get: function () { return TransactionStatus_1.TransactionStatus; } });
var UserRole_1 = require("./models/UserRole");
Object.defineProperty(exports, "UserRole", { enumerable: true, get: function () { return UserRole_1.UserRole; } });
var AuthService_1 = require("./services/AuthService");
Object.defineProperty(exports, "AuthService", { enumerable: true, get: function () { return AuthService_1.AuthService; } });
var CurrencyService_1 = require("./services/CurrencyService");
Object.defineProperty(exports, "CurrencyService", { enumerable: true, get: function () { return CurrencyService_1.CurrencyService; } });
var DefaultService_1 = require("./services/DefaultService");
Object.defineProperty(exports, "DefaultService", { enumerable: true, get: function () { return DefaultService_1.DefaultService; } });
var OrderService_1 = require("./services/OrderService");
Object.defineProperty(exports, "OrderService", { enumerable: true, get: function () { return OrderService_1.OrderService; } });
var PaymentService_1 = require("./services/PaymentService");
Object.defineProperty(exports, "PaymentService", { enumerable: true, get: function () { return PaymentService_1.PaymentService; } });
var PlatformProductService_1 = require("./services/PlatformProductService");
Object.defineProperty(exports, "PlatformProductService", { enumerable: true, get: function () { return PlatformProductService_1.PlatformProductService; } });
var PlatformVariantService_1 = require("./services/PlatformVariantService");
Object.defineProperty(exports, "PlatformVariantService", { enumerable: true, get: function () { return PlatformVariantService_1.PlatformVariantService; } });
var ProductService_1 = require("./services/ProductService");
Object.defineProperty(exports, "ProductService", { enumerable: true, get: function () { return ProductService_1.ProductService; } });
var ProductTagService_1 = require("./services/ProductTagService");
Object.defineProperty(exports, "ProductTagService", { enumerable: true, get: function () { return ProductTagService_1.ProductTagService; } });
var SettingService_1 = require("./services/SettingService");
Object.defineProperty(exports, "SettingService", { enumerable: true, get: function () { return SettingService_1.SettingService; } });
var StoreService_1 = require("./services/StoreService");
Object.defineProperty(exports, "StoreService", { enumerable: true, get: function () { return StoreService_1.StoreService; } });
var ThemeTemplateService_1 = require("./services/ThemeTemplateService");
Object.defineProperty(exports, "ThemeTemplateService", { enumerable: true, get: function () { return ThemeTemplateService_1.ThemeTemplateService; } });
var TransactionService_1 = require("./services/TransactionService");
Object.defineProperty(exports, "TransactionService", { enumerable: true, get: function () { return TransactionService_1.TransactionService; } });
var UploadService_1 = require("./services/UploadService");
Object.defineProperty(exports, "UploadService", { enumerable: true, get: function () { return UploadService_1.UploadService; } });
var UserService_1 = require("./services/UserService");
Object.defineProperty(exports, "UserService", { enumerable: true, get: function () { return UserService_1.UserService; } });
