export { ClientApi } from './ClientApi';
export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';
export type { AddPaymentToStores } from './models/AddPaymentToStores';
export type { AddPlatformProductStoresDto } from './models/AddPlatformProductStoresDto';
export type { AddPlatformProductTagDto } from './models/AddPlatformProductTagDto';
export type { AdminTag } from './models/AdminTag';
export type { ApproveRequestSourcingDto } from './models/ApproveRequestSourcingDto';
export type { ApproveStoreDto } from './models/ApproveStoreDto';
export type { AsyncTask } from './models/AsyncTask';
export { AsyncTaskStatus } from './models/AsyncTaskStatus';
export { AsyncTaskType } from './models/AsyncTaskType';
export type { AuthData } from './models/AuthData';
export type { AuthStoreData } from './models/AuthStoreData';
export type { BatchPayload } from './models/BatchPayload';
export type { Campaign } from './models/Campaign';
export type { CampaignDto } from './models/CampaignDto';
export type { ChangeActiveTheme } from './models/ChangeActiveTheme';
export type { ChangeUserPasswordDto } from './models/ChangeUserPasswordDto';
export type { Collection } from './models/Collection';
export type { ComboItemDto } from './models/ComboItemDto';
export type { CreateCollectionDto } from './models/CreateCollectionDto';
export type { CreateComboDto } from './models/CreateComboDto';
export type { CreateDiscountDto } from './models/CreateDiscountDto';
export type { CreateDomainDto } from './models/CreateDomainDto';
export type { CreateFbPixelDto } from './models/CreateFbPixelDto';
export type { CreateFulfillmentAgencyDto } from './models/CreateFulfillmentAgencyDto';
export type { CreateNotificationDto } from './models/CreateNotificationDto';
export type { CreateOrderDto } from './models/CreateOrderDto';
export type { CreatePaymentDto } from './models/CreatePaymentDto';
export type { CreatePlatformProductDto } from './models/CreatePlatformProductDto';
export type { CreatePlatformVariantDto } from './models/CreatePlatformVariantDto';
export type { CreatePlatformVariantsDto } from './models/CreatePlatformVariantsDto';
export type { CreateProductDto } from './models/CreateProductDto';
export type { CreateRequestSourcingDto } from './models/CreateRequestSourcingDto';
export type { CreateReviewDto } from './models/CreateReviewDto';
export type { CreateStaffDto } from './models/CreateStaffDto';
export type { CreateStoreDto } from './models/CreateStoreDto';
export type { CreateStoreTagDto } from './models/CreateStoreTagDto';
export type { CreateTagDto } from './models/CreateTagDto';
export type { CreateThemeDto } from './models/CreateThemeDto';
export type { CreateThemeTemplateDto } from './models/CreateThemeTemplateDto';
export type { CreateUploadDto } from './models/CreateUploadDto';
export type { CreatEventDto } from './models/CreatEventDto';
export type { Currency } from './models/Currency';
export type { CustomDomain } from './models/CustomDomain';
export { CustomDomainStatus } from './models/CustomDomainStatus';
export type { Discount } from './models/Discount';
export type { DiscountDto } from './models/DiscountDto';
export type { EmailDto } from './models/EmailDto';
export type { ExportOrderResponseDto } from './models/ExportOrderResponseDto';
export type { ExportOrderResult } from './models/ExportOrderResult';
export type { FbPixel } from './models/FbPixel';
export type { FulfillmentAgency } from './models/FulfillmentAgency';
export { FulfillmentAgencyRole } from './models/FulfillmentAgencyRole';
export { FulfillmentAgencyStatus } from './models/FulfillmentAgencyStatus';
export { FulfillmentStatus } from './models/FulfillmentStatus';
export type { FulfillmentUser } from './models/FulfillmentUser';
export type { JsonArray } from './models/JsonArray';
export type { JsonObject } from './models/JsonObject';
export type { LoginDto } from './models/LoginDto';
export { LogoSize } from './models/LogoSize';
export type { NameDto } from './models/NameDto';
export type { Notification } from './models/Notification';
export type { NotificationData } from './models/NotificationData';
export { NotificationType } from './models/NotificationType';
export type { Order } from './models/Order';
export { OrderDisputeStatus } from './models/OrderDisputeStatus';
export type { OrderItem } from './models/OrderItem';
export type { OrderItemDto } from './models/OrderItemDto';
export type { OrderRefund } from './models/OrderRefund';
export { OrderStatus } from './models/OrderStatus';
export type { Payment } from './models/Payment';
export { PaymentType } from './models/PaymentType';
export { Period } from './models/Period';
export type { PhoneWithCountryCode } from './models/PhoneWithCountryCode';
export type { PhotoDto } from './models/PhotoDto';
export type { Photos } from './models/Photos';
export type { PlatformProduct } from './models/PlatformProduct';
export type { PlatformProductStore } from './models/PlatformProductStore';
export type { PlatformVariant } from './models/PlatformVariant';
export type { PlatformVariantDto } from './models/PlatformVariantDto';
export type { Prisma_JsonValue } from './models/Prisma_JsonValue';
export { Prisma_SortOrder } from './models/Prisma_SortOrder';
export type { PrismaJson_AsyncTaskResult } from './models/PrismaJson_AsyncTaskResult';
export type { PrismaJson_BillingInfo } from './models/PrismaJson_BillingInfo';
export type { PrismaJson_Colors } from './models/PrismaJson_Colors';
export type { PrismaJson_Photos } from './models/PrismaJson_Photos';
export type { PrismaJson_ProductDiscountItems } from './models/PrismaJson_ProductDiscountItems';
export type { PrismaJson_ProductRequirementItems } from './models/PrismaJson_ProductRequirementItems';
export type { PrismaJson_RefundOrderItems } from './models/PrismaJson_RefundOrderItems';
export type { PrismaJson_Timezone } from './models/PrismaJson_Timezone';
export type { PrismaJson_VariantComboItems } from './models/PrismaJson_VariantComboItems';
export type { PrismaJson_VariantOptions } from './models/PrismaJson_VariantOptions';
export type { PrismaJson_VariantOptionValues } from './models/PrismaJson_VariantOptionValues';
export type { Product } from './models/Product';
export type { ProductPerformance } from './models/ProductPerformance';
export type { ProductPerformanceResult } from './models/ProductPerformanceResult';
export type { ProductVariant } from './models/ProductVariant';
export type { RefundOrderDto } from './models/RefundOrderDto';
export { RefundType } from './models/RefundType';
export type { RejectRequestSourcingDto } from './models/RejectRequestSourcingDto';
export type { RequestSourcing } from './models/RequestSourcing';
export { RequestSourcingStatus } from './models/RequestSourcingStatus';
export type { Review } from './models/Review';
export type { Setting } from './models/Setting';
export type { Store } from './models/Store';
export { StoreOrderBy } from './models/StoreOrderBy';
export type { StorePerformance } from './models/StorePerformance';
export type { StoreProductPerformanceResp } from './models/StoreProductPerformanceResp';
export type { StoreRevenue } from './models/StoreRevenue';
export type { StoreRevenueOverTime } from './models/StoreRevenueOverTime';
export { StoreRole } from './models/StoreRole';
export { StoreStatus } from './models/StoreStatus';
export type { StoreUser } from './models/StoreUser';
export type { Tag } from './models/Tag';
export type { Theme } from './models/Theme';
export type { ThemeTemplate } from './models/ThemeTemplate';
export type { Timezone } from './models/Timezone';
export { TimezoneDto } from './models/TimezoneDto';
export type { TopStoreByRevenue } from './models/TopStoreByRevenue';
export type { Transaction } from './models/Transaction';
export { TransactionStatus } from './models/TransactionStatus';
export { TransactionType } from './models/TransactionType';
export type { UpdateCampaignDto } from './models/UpdateCampaignDto';
export type { UpdateCollectionDto } from './models/UpdateCollectionDto';
export type { UpdateComboDto } from './models/UpdateComboDto';
export type { UpdateCombosDto } from './models/UpdateCombosDto';
export type { UpdateComboStatusDto } from './models/UpdateComboStatusDto';
export type { UpdateDiscountDto } from './models/UpdateDiscountDto';
export type { UpdateFbPixelDto } from './models/UpdateFbPixelDto';
export type { UpdateFulfillmentAgencyDto } from './models/UpdateFulfillmentAgencyDto';
export type { UpdateFulfillmentAgencyStatusDto } from './models/UpdateFulfillmentAgencyStatusDto';
export type { UpdateFulFillmentStatusDto } from './models/UpdateFulFillmentStatusDto';
export type { UpdateFulFillmentStatusError } from './models/UpdateFulFillmentStatusError';
export type { UpdateFulFillmentStatusResp } from './models/UpdateFulFillmentStatusResp';
export type { UpdateNotificationDto } from './models/UpdateNotificationDto';
export type { UpdateOrderRefundDto } from './models/UpdateOrderRefundDto';
export type { UpdateOrderRefundHistoryDto } from './models/UpdateOrderRefundHistoryDto';
export type { UpdatePaymentDto } from './models/UpdatePaymentDto';
export type { UpdatePlatformProductDto } from './models/UpdatePlatformProductDto';
export type { UpdatePlatformProductStatusDto } from './models/UpdatePlatformProductStatusDto';
export type { UpdatePlatformProductStatusesDto } from './models/UpdatePlatformProductStatusesDto';
export type { UpdatePlatformVariantDto } from './models/UpdatePlatformVariantDto';
export type { UpdatePlatformVariantsDto } from './models/UpdatePlatformVariantsDto';
export type { UpdatePlatformVariantStatusDto } from './models/UpdatePlatformVariantStatusDto';
export type { UpdateProductDto } from './models/UpdateProductDto';
export type { UpdateProductStatusDto } from './models/UpdateProductStatusDto';
export type { UpdateProductStatusesDto } from './models/UpdateProductStatusesDto';
export type { UpdateRequestSourcingDto } from './models/UpdateRequestSourcingDto';
export type { UpdateReviewDto } from './models/UpdateReviewDto';
export type { UpdateSettingDto } from './models/UpdateSettingDto';
export type { UpdateStaffDto } from './models/UpdateStaffDto';
export type { UpdateStoreDto } from './models/UpdateStoreDto';
export type { UpdateStorePaymentMethodDto } from './models/UpdateStorePaymentMethodDto';
export type { UpdateStoreStatusDto } from './models/UpdateStoreStatusDto';
export type { UpdateThemeDto } from './models/UpdateThemeDto';
export type { UpdateThemeTemplateDto } from './models/UpdateThemeTemplateDto';
export type { UpdateUserDto } from './models/UpdateUserDto';
export type { UpdateVariantDto } from './models/UpdateVariantDto';
export type { UpdateVariantsDto } from './models/UpdateVariantsDto';
export type { UpdateVariantStatusDto } from './models/UpdateVariantStatusDto';
export type { URLDto } from './models/URLDto';
export type { User } from './models/User';
export { UserRole } from './models/UserRole';
export type { VariantCombo } from './models/VariantCombo';
export type { VariantOptions } from './models/VariantOptions';
export type { VariantOptionValues } from './models/VariantOptionValues';
export { AsyncTaskService } from './services/AsyncTaskService';
export { AuthService } from './services/AuthService';
export { CurrencyService } from './services/CurrencyService';
export { FulfillmentAgencyService } from './services/FulfillmentAgencyService';
export { NotificationService } from './services/NotificationService';
export { OrderService } from './services/OrderService';
export { OrderRefundsService } from './services/OrderRefundsService';
export { PaymentService } from './services/PaymentService';
export { PerformanceService } from './services/PerformanceService';
export { PlatformProductService } from './services/PlatformProductService';
export { PlatformVariantService } from './services/PlatformVariantService';
export { ProductService } from './services/ProductService';
export { RequestSourcingService } from './services/RequestSourcingService';
export { SettingService } from './services/SettingService';
export { StoreService } from './services/StoreService';
export { StoreTagService } from './services/StoreTagService';
export { TagService } from './services/TagService';
export { ThemeTemplateService } from './services/ThemeTemplateService';
export { TransactionService } from './services/TransactionService';
export { UploadService } from './services/UploadService';
export { UserService } from './services/UserService';
export { VariantService } from './services/VariantService';
export { VariantComboService } from './services/VariantComboService';
export { WebhookService } from './services/WebhookService';
