export { ClientApi } from './ClientApi';
export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';
export type { AddPlatformProductStoresDto } from './models/AddPlatformProductStoresDto';
export type { AddPlatformProductTagDto } from './models/AddPlatformProductTagDto';
export type { AdminTag } from './models/AdminTag';
export type { ApproveRequestSourcingDto } from './models/ApproveRequestSourcingDto';
export type { AuthData } from './models/AuthData';
export type { AuthStoreData } from './models/AuthStoreData';
export type { BatchPayload } from './models/BatchPayload';
export type { ChangeActiveTheme } from './models/ChangeActiveTheme';
export type { Collection } from './models/Collection';
export type { Color } from './models/Color';
export type { Colors } from './models/Colors';
export type { ConfirmPaypalOrderDto } from './models/ConfirmPaypalOrderDto';
export type { CreateCollectionDto } from './models/CreateCollectionDto';
export type { CreateDomainDto } from './models/CreateDomainDto';
export type { CreateFbPixelDto } from './models/CreateFbPixelDto';
export type { CreateOrderDto } from './models/CreateOrderDto';
export type { CreatePaymentDto } from './models/CreatePaymentDto';
export type { CreatePaypalOrderDto } from './models/CreatePaypalOrderDto';
export type { CreatePlatformProductDto } from './models/CreatePlatformProductDto';
export type { CreatePlatformVariantDto } from './models/CreatePlatformVariantDto';
export type { CreatePlatformVariantsDto } from './models/CreatePlatformVariantsDto';
export type { CreateProductDto } from './models/CreateProductDto';
export type { CreateRequestSourcingDto } from './models/CreateRequestSourcingDto';
export type { CreateReviewDto } from './models/CreateReviewDto';
export type { CreateStaffDto } from './models/CreateStaffDto';
export type { CreateStoreDto } from './models/CreateStoreDto';
export type { CreateStoreTagDto } from './models/CreateStoreTagDto';
export type { CreateTagDto } from './models/CreateTagDto';
export type { CreateThemeDto } from './models/CreateThemeDto';
export type { CreateThemeTemplateDto } from './models/CreateThemeTemplateDto';
export type { CreateTransactionDto } from './models/CreateTransactionDto';
export type { CreateUploadDto } from './models/CreateUploadDto';
export type { Currency } from './models/Currency';
export type { CustomDomain } from './models/CustomDomain';
export { CustomDomainStatus } from './models/CustomDomainStatus';
export type { EmailDto } from './models/EmailDto';
export type { ExportOrderResponseDto } from './models/ExportOrderResponseDto';
export type { FbPixel } from './models/FbPixel';
export { FulfillmentStatus } from './models/FulfillmentStatus';
export type { JsonArray } from './models/JsonArray';
export type { JsonObject } from './models/JsonObject';
export type { LoginDto } from './models/LoginDto';
export type { NameDto } from './models/NameDto';
export type { Omit_Theme_id_or_createdAt_or_updatedAt_or_storeId_or_colors_or_typos_ } from './models/Omit_Theme_id_or_createdAt_or_updatedAt_or_storeId_or_colors_or_typos_';
export type { Order } from './models/Order';
export type { OrderItem } from './models/OrderItem';
export type { OrderItemDto } from './models/OrderItemDto';
export type { Payment } from './models/Payment';
export { PaymentType } from './models/PaymentType';
export type { PhoneWithCountryCode } from './models/PhoneWithCountryCode';
export type { PhotoDto } from './models/PhotoDto';
export type { Photos } from './models/Photos';
export type { Pick_Theme_Exclude_keyofTheme_id_or_createdAt_or_updatedAt_or_storeId_or_colors_or_typos__ } from './models/Pick_Theme_Exclude_keyofTheme_id_or_createdAt_or_updatedAt_or_storeId_or_colors_or_typos__';
export type { PlatformProduct } from './models/PlatformProduct';
export type { PlatformVariant } from './models/PlatformVariant';
export type { PlatformVariantDto } from './models/PlatformVariantDto';
export type { Prisma_JsonValue } from './models/Prisma_JsonValue';
export { Prisma_SortOrder } from './models/Prisma_SortOrder';
export type { PrismaJson_Photos } from './models/PrismaJson_Photos';
export type { PrismaJson_Timezone } from './models/PrismaJson_Timezone';
export type { PrismaJson_VariantOptions } from './models/PrismaJson_VariantOptions';
export type { PrismaJson_VariantOptionValues } from './models/PrismaJson_VariantOptionValues';
export type { Product } from './models/Product';
export type { ProductPerformance } from './models/ProductPerformance';
export type { ProductVariant } from './models/ProductVariant';
export type { RejectRequestSourcingDto } from './models/RejectRequestSourcingDto';
export type { RequestSourcing } from './models/RequestSourcing';
export { RequestSourcingStatus } from './models/RequestSourcingStatus';
export type { Review } from './models/Review';
export type { Setting } from './models/Setting';
export type { Store } from './models/Store';
export { StoreOrderBy } from './models/StoreOrderBy';
export type { StoreRevenue } from './models/StoreRevenue';
export { StoreRole } from './models/StoreRole';
export { StoreStatus } from './models/StoreStatus';
export type { StoreUser } from './models/StoreUser';
export type { Tag } from './models/Tag';
export type { Theme } from './models/Theme';
export type { ThemeTemplate } from './models/ThemeTemplate';
export type { Timezone } from './models/Timezone';
export { TimezoneDto } from './models/TimezoneDto';
export type { TopProductByOrder } from './models/TopProductByOrder';
export type { TopStoreByRevenue } from './models/TopStoreByRevenue';
export type { Transaction } from './models/Transaction';
export { TransactionStatus } from './models/TransactionStatus';
export { TransactionType } from './models/TransactionType';
export type { Typo } from './models/Typo';
export type { Typos } from './models/Typos';
export type { UpdateCollectionDto } from './models/UpdateCollectionDto';
export type { UpdateFbPixelDto } from './models/UpdateFbPixelDto';
export type { UpdateFulFillmentStatusDto } from './models/UpdateFulFillmentStatusDto';
export type { UpdatePlatformProductDto } from './models/UpdatePlatformProductDto';
export type { UpdatePlatformProductStatusDto } from './models/UpdatePlatformProductStatusDto';
export type { UpdatePlatformProductStatusesDto } from './models/UpdatePlatformProductStatusesDto';
export type { UpdatePlatformVariantDto } from './models/UpdatePlatformVariantDto';
export type { UpdatePlatformVariantsDto } from './models/UpdatePlatformVariantsDto';
export type { UpdatePlatformVariantStatusDto } from './models/UpdatePlatformVariantStatusDto';
export type { UpdateProductDto } from './models/UpdateProductDto';
export type { UpdateProductStatusDto } from './models/UpdateProductStatusDto';
export type { UpdateProductStatusesDto } from './models/UpdateProductStatusesDto';
export type { UpdateRequestSourcingDto } from './models/UpdateRequestSourcingDto';
export type { UpdateReviewDto } from './models/UpdateReviewDto';
export type { UpdateSettingDto } from './models/UpdateSettingDto';
export type { UpdateStaffDto } from './models/UpdateStaffDto';
export type { UpdateStoreDto } from './models/UpdateStoreDto';
export type { UpdateStorePaymentMethodDto } from './models/UpdateStorePaymentMethodDto';
export type { UpdateStoreStatusDto } from './models/UpdateStoreStatusDto';
export type { UpdateThemeDto } from './models/UpdateThemeDto';
export type { UpdateThemeTemplateDto } from './models/UpdateThemeTemplateDto';
export type { UpdateUserDto } from './models/UpdateUserDto';
export type { UpdateVariantDto } from './models/UpdateVariantDto';
export type { UpdateVariantsDto } from './models/UpdateVariantsDto';
export type { UpdateVariantStatusDto } from './models/UpdateVariantStatusDto';
export type { URLDto } from './models/URLDto';
export type { User } from './models/User';
export { UserRole } from './models/UserRole';
export type { VariantOptions } from './models/VariantOptions';
export { CollectionService } from './services/CollectionService';
export { CurrencyService } from './services/CurrencyService';
export { OrderService } from './services/OrderService';
export { ProductService } from './services/ProductService';
export { ReviewService } from './services/ReviewService';
export { SettingService } from './services/SettingService';
export { StoreService } from './services/StoreService';
export { StoreTagService } from './services/StoreTagService';
export { ThemeService } from './services/ThemeService';
export { TransactionService } from './services/TransactionService';
export { UploadService } from './services/UploadService';
export { VariantService } from './services/VariantService';
