"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VariantService = exports.UploadService = exports.TransactionService = exports.ThemeService = exports.StoreTagService = exports.StoreService = exports.SettingService = exports.ReviewService = exports.ProductService = exports.OrderService = exports.CurrencyService = exports.CollectionService = exports.UserRole = exports.TransactionType = exports.TransactionStatus = exports.StoreStatus = exports.StoreRole = exports.StoreOrderBy = exports.RequestSourcingStatus = exports.Prisma_SortOrder = exports.PaymentType = exports.FulfillmentStatus = exports.CustomDomainStatus = exports.CreateOrderDto = exports.OpenAPI = exports.CancelError = exports.CancelablePromise = exports.BaseHttpRequest = exports.ApiError = exports.ClientApi = void 0;
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
var ClientApi_1 = require("./ClientApi");
Object.defineProperty(exports, "ClientApi", { enumerable: true, get: function () { return ClientApi_1.ClientApi; } });
var ApiError_1 = require("./core/ApiError");
Object.defineProperty(exports, "ApiError", { enumerable: true, get: function () { return ApiError_1.ApiError; } });
var BaseHttpRequest_1 = require("./core/BaseHttpRequest");
Object.defineProperty(exports, "BaseHttpRequest", { enumerable: true, get: function () { return BaseHttpRequest_1.BaseHttpRequest; } });
var CancelablePromise_1 = require("./core/CancelablePromise");
Object.defineProperty(exports, "CancelablePromise", { enumerable: true, get: function () { return CancelablePromise_1.CancelablePromise; } });
Object.defineProperty(exports, "CancelError", { enumerable: true, get: function () { return CancelablePromise_1.CancelError; } });
var OpenAPI_1 = require("./core/OpenAPI");
Object.defineProperty(exports, "OpenAPI", { enumerable: true, get: function () { return OpenAPI_1.OpenAPI; } });
var CreateOrderDto_1 = require("./models/CreateOrderDto");
Object.defineProperty(exports, "CreateOrderDto", { enumerable: true, get: function () { return CreateOrderDto_1.CreateOrderDto; } });
var CustomDomainStatus_1 = require("./models/CustomDomainStatus");
Object.defineProperty(exports, "CustomDomainStatus", { enumerable: true, get: function () { return CustomDomainStatus_1.CustomDomainStatus; } });
var FulfillmentStatus_1 = require("./models/FulfillmentStatus");
Object.defineProperty(exports, "FulfillmentStatus", { enumerable: true, get: function () { return FulfillmentStatus_1.FulfillmentStatus; } });
var PaymentType_1 = require("./models/PaymentType");
Object.defineProperty(exports, "PaymentType", { enumerable: true, get: function () { return PaymentType_1.PaymentType; } });
var Prisma_SortOrder_1 = require("./models/Prisma_SortOrder");
Object.defineProperty(exports, "Prisma_SortOrder", { enumerable: true, get: function () { return Prisma_SortOrder_1.Prisma_SortOrder; } });
var RequestSourcingStatus_1 = require("./models/RequestSourcingStatus");
Object.defineProperty(exports, "RequestSourcingStatus", { enumerable: true, get: function () { return RequestSourcingStatus_1.RequestSourcingStatus; } });
var StoreOrderBy_1 = require("./models/StoreOrderBy");
Object.defineProperty(exports, "StoreOrderBy", { enumerable: true, get: function () { return StoreOrderBy_1.StoreOrderBy; } });
var StoreRole_1 = require("./models/StoreRole");
Object.defineProperty(exports, "StoreRole", { enumerable: true, get: function () { return StoreRole_1.StoreRole; } });
var StoreStatus_1 = require("./models/StoreStatus");
Object.defineProperty(exports, "StoreStatus", { enumerable: true, get: function () { return StoreStatus_1.StoreStatus; } });
var TransactionStatus_1 = require("./models/TransactionStatus");
Object.defineProperty(exports, "TransactionStatus", { enumerable: true, get: function () { return TransactionStatus_1.TransactionStatus; } });
var TransactionType_1 = require("./models/TransactionType");
Object.defineProperty(exports, "TransactionType", { enumerable: true, get: function () { return TransactionType_1.TransactionType; } });
var UserRole_1 = require("./models/UserRole");
Object.defineProperty(exports, "UserRole", { enumerable: true, get: function () { return UserRole_1.UserRole; } });
var CollectionService_1 = require("./services/CollectionService");
Object.defineProperty(exports, "CollectionService", { enumerable: true, get: function () { return CollectionService_1.CollectionService; } });
var CurrencyService_1 = require("./services/CurrencyService");
Object.defineProperty(exports, "CurrencyService", { enumerable: true, get: function () { return CurrencyService_1.CurrencyService; } });
var OrderService_1 = require("./services/OrderService");
Object.defineProperty(exports, "OrderService", { enumerable: true, get: function () { return OrderService_1.OrderService; } });
var ProductService_1 = require("./services/ProductService");
Object.defineProperty(exports, "ProductService", { enumerable: true, get: function () { return ProductService_1.ProductService; } });
var ReviewService_1 = require("./services/ReviewService");
Object.defineProperty(exports, "ReviewService", { enumerable: true, get: function () { return ReviewService_1.ReviewService; } });
var SettingService_1 = require("./services/SettingService");
Object.defineProperty(exports, "SettingService", { enumerable: true, get: function () { return SettingService_1.SettingService; } });
var StoreService_1 = require("./services/StoreService");
Object.defineProperty(exports, "StoreService", { enumerable: true, get: function () { return StoreService_1.StoreService; } });
var StoreTagService_1 = require("./services/StoreTagService");
Object.defineProperty(exports, "StoreTagService", { enumerable: true, get: function () { return StoreTagService_1.StoreTagService; } });
var ThemeService_1 = require("./services/ThemeService");
Object.defineProperty(exports, "ThemeService", { enumerable: true, get: function () { return ThemeService_1.ThemeService; } });
var TransactionService_1 = require("./services/TransactionService");
Object.defineProperty(exports, "TransactionService", { enumerable: true, get: function () { return TransactionService_1.TransactionService; } });
var UploadService_1 = require("./services/UploadService");
Object.defineProperty(exports, "UploadService", { enumerable: true, get: function () { return UploadService_1.UploadService; } });
var VariantService_1 = require("./services/VariantService");
Object.defineProperty(exports, "VariantService", { enumerable: true, get: function () { return VariantService_1.VariantService; } });
