"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VariantComboService = exports.VariantService = exports.UploadService = exports.ThemeService = exports.StoreTagService = exports.StoreService = exports.SettingService = exports.ReviewService = exports.ProductService = exports.OrderService = exports.CurrencyService = exports.CollectionService = exports.UserRole = exports.TransactionType = exports.TransactionStatus = exports.TimezoneDto = exports.StoreStatus = exports.StoreRole = exports.StoreOrderBy = exports.RequestSourcingStatus = exports.RefundType = exports.Prisma_SortOrder = exports.Period = exports.PaymentType = exports.OrderStatus = exports.OrderDisputeStatus = exports.NotificationType = exports.LogoSize = exports.FulfillmentStatus = exports.FulfillmentAgencyStatus = exports.FulfillmentAgencyRole = exports.CustomDomainStatus = exports.COST_CALCULATION_METHOD = exports.AsyncTaskType = exports.AsyncTaskStatus = exports.OpenAPI = exports.CancelError = exports.CancelablePromise = exports.BaseHttpRequest = exports.ApiError = exports.ClientApi = void 0;
/* generated using openapi-typescript-codegen -- do no edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
var ClientApi_1 = require("./ClientApi");
Object.defineProperty(exports, "ClientApi", { enumerable: true, get: function () { return ClientApi_1.ClientApi; } });
var ApiError_1 = require("./core/ApiError");
Object.defineProperty(exports, "ApiError", { enumerable: true, get: function () { return ApiError_1.ApiError; } });
var BaseHttpRequest_1 = require("./core/BaseHttpRequest");
Object.defineProperty(exports, "BaseHttpRequest", { enumerable: true, get: function () { return BaseHttpRequest_1.BaseHttpRequest; } });
var CancelablePromise_1 = require("./core/CancelablePromise");
Object.defineProperty(exports, "CancelablePromise", { enumerable: true, get: function () { return CancelablePromise_1.CancelablePromise; } });
Object.defineProperty(exports, "CancelError", { enumerable: true, get: function () { return CancelablePromise_1.CancelError; } });
var OpenAPI_1 = require("./core/OpenAPI");
Object.defineProperty(exports, "OpenAPI", { enumerable: true, get: function () { return OpenAPI_1.OpenAPI; } });
var AsyncTaskStatus_1 = require("./models/AsyncTaskStatus");
Object.defineProperty(exports, "AsyncTaskStatus", { enumerable: true, get: function () { return AsyncTaskStatus_1.AsyncTaskStatus; } });
var AsyncTaskType_1 = require("./models/AsyncTaskType");
Object.defineProperty(exports, "AsyncTaskType", { enumerable: true, get: function () { return AsyncTaskType_1.AsyncTaskType; } });
var COST_CALCULATION_METHOD_1 = require("./models/COST_CALCULATION_METHOD");
Object.defineProperty(exports, "COST_CALCULATION_METHOD", { enumerable: true, get: function () { return COST_CALCULATION_METHOD_1.COST_CALCULATION_METHOD; } });
var CustomDomainStatus_1 = require("./models/CustomDomainStatus");
Object.defineProperty(exports, "CustomDomainStatus", { enumerable: true, get: function () { return CustomDomainStatus_1.CustomDomainStatus; } });
var FulfillmentAgencyRole_1 = require("./models/FulfillmentAgencyRole");
Object.defineProperty(exports, "FulfillmentAgencyRole", { enumerable: true, get: function () { return FulfillmentAgencyRole_1.FulfillmentAgencyRole; } });
var FulfillmentAgencyStatus_1 = require("./models/FulfillmentAgencyStatus");
Object.defineProperty(exports, "FulfillmentAgencyStatus", { enumerable: true, get: function () { return FulfillmentAgencyStatus_1.FulfillmentAgencyStatus; } });
var FulfillmentStatus_1 = require("./models/FulfillmentStatus");
Object.defineProperty(exports, "FulfillmentStatus", { enumerable: true, get: function () { return FulfillmentStatus_1.FulfillmentStatus; } });
var LogoSize_1 = require("./models/LogoSize");
Object.defineProperty(exports, "LogoSize", { enumerable: true, get: function () { return LogoSize_1.LogoSize; } });
var NotificationType_1 = require("./models/NotificationType");
Object.defineProperty(exports, "NotificationType", { enumerable: true, get: function () { return NotificationType_1.NotificationType; } });
var OrderDisputeStatus_1 = require("./models/OrderDisputeStatus");
Object.defineProperty(exports, "OrderDisputeStatus", { enumerable: true, get: function () { return OrderDisputeStatus_1.OrderDisputeStatus; } });
var OrderStatus_1 = require("./models/OrderStatus");
Object.defineProperty(exports, "OrderStatus", { enumerable: true, get: function () { return OrderStatus_1.OrderStatus; } });
var PaymentType_1 = require("./models/PaymentType");
Object.defineProperty(exports, "PaymentType", { enumerable: true, get: function () { return PaymentType_1.PaymentType; } });
var Period_1 = require("./models/Period");
Object.defineProperty(exports, "Period", { enumerable: true, get: function () { return Period_1.Period; } });
var Prisma_SortOrder_1 = require("./models/Prisma_SortOrder");
Object.defineProperty(exports, "Prisma_SortOrder", { enumerable: true, get: function () { return Prisma_SortOrder_1.Prisma_SortOrder; } });
var RefundType_1 = require("./models/RefundType");
Object.defineProperty(exports, "RefundType", { enumerable: true, get: function () { return RefundType_1.RefundType; } });
var RequestSourcingStatus_1 = require("./models/RequestSourcingStatus");
Object.defineProperty(exports, "RequestSourcingStatus", { enumerable: true, get: function () { return RequestSourcingStatus_1.RequestSourcingStatus; } });
var StoreOrderBy_1 = require("./models/StoreOrderBy");
Object.defineProperty(exports, "StoreOrderBy", { enumerable: true, get: function () { return StoreOrderBy_1.StoreOrderBy; } });
var StoreRole_1 = require("./models/StoreRole");
Object.defineProperty(exports, "StoreRole", { enumerable: true, get: function () { return StoreRole_1.StoreRole; } });
var StoreStatus_1 = require("./models/StoreStatus");
Object.defineProperty(exports, "StoreStatus", { enumerable: true, get: function () { return StoreStatus_1.StoreStatus; } });
var TimezoneDto_1 = require("./models/TimezoneDto");
Object.defineProperty(exports, "TimezoneDto", { enumerable: true, get: function () { return TimezoneDto_1.TimezoneDto; } });
var TransactionStatus_1 = require("./models/TransactionStatus");
Object.defineProperty(exports, "TransactionStatus", { enumerable: true, get: function () { return TransactionStatus_1.TransactionStatus; } });
var TransactionType_1 = require("./models/TransactionType");
Object.defineProperty(exports, "TransactionType", { enumerable: true, get: function () { return TransactionType_1.TransactionType; } });
var UserRole_1 = require("./models/UserRole");
Object.defineProperty(exports, "UserRole", { enumerable: true, get: function () { return UserRole_1.UserRole; } });
var CollectionService_1 = require("./services/CollectionService");
Object.defineProperty(exports, "CollectionService", { enumerable: true, get: function () { return CollectionService_1.CollectionService; } });
var CurrencyService_1 = require("./services/CurrencyService");
Object.defineProperty(exports, "CurrencyService", { enumerable: true, get: function () { return CurrencyService_1.CurrencyService; } });
var OrderService_1 = require("./services/OrderService");
Object.defineProperty(exports, "OrderService", { enumerable: true, get: function () { return OrderService_1.OrderService; } });
var ProductService_1 = require("./services/ProductService");
Object.defineProperty(exports, "ProductService", { enumerable: true, get: function () { return ProductService_1.ProductService; } });
var ReviewService_1 = require("./services/ReviewService");
Object.defineProperty(exports, "ReviewService", { enumerable: true, get: function () { return ReviewService_1.ReviewService; } });
var SettingService_1 = require("./services/SettingService");
Object.defineProperty(exports, "SettingService", { enumerable: true, get: function () { return SettingService_1.SettingService; } });
var StoreService_1 = require("./services/StoreService");
Object.defineProperty(exports, "StoreService", { enumerable: true, get: function () { return StoreService_1.StoreService; } });
var StoreTagService_1 = require("./services/StoreTagService");
Object.defineProperty(exports, "StoreTagService", { enumerable: true, get: function () { return StoreTagService_1.StoreTagService; } });
var ThemeService_1 = require("./services/ThemeService");
Object.defineProperty(exports, "ThemeService", { enumerable: true, get: function () { return ThemeService_1.ThemeService; } });
var UploadService_1 = require("./services/UploadService");
Object.defineProperty(exports, "UploadService", { enumerable: true, get: function () { return UploadService_1.UploadService; } });
var VariantService_1 = require("./services/VariantService");
Object.defineProperty(exports, "VariantService", { enumerable: true, get: function () { return VariantService_1.VariantService; } });
var VariantComboService_1 = require("./services/VariantComboService");
Object.defineProperty(exports, "VariantComboService", { enumerable: true, get: function () { return VariantComboService_1.VariantComboService; } });
