/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum FulfillmentPermissions {
  FULFILLMENT_AGENCY_VIEW_PLATFORM_PERFORMANCE = 'FULFILLMENT_AGENCY_VIEW_PLATFORM_PERFORMANCE',
  FULFILLMENT_AGENCY_VIEW_PRODUCT_PERFORMANCE = 'FULFILLMENT_AGENCY_VIEW_PRODUCT_PERFORMANCE',
  FULFILLMENT_AGENCY_VIEW_LIVE_VIEW = 'FULFILLMENT_AGENCY_VIEW_LIVE_VIEW',
  FULFILLMENT_AGENCY_VIEW_ORDER = 'FULFILLMENT_AGENCY_VIEW_ORDER',
  FULFILLMENT_AGENCY_VIEW_ORDER_FINANCIAL_DETAIL = 'FULFILLMENT_AGENCY_VIEW_ORDER_FINANCIAL_DETAIL',
  FULFILLMENT_AGENCY_REFUND_ORDER = 'FULFILLMENT_AGENCY_REFUND_ORDER',
  FULFILLMENT_AGENCY_IMPORT_AND_EXPORT_ORDER = 'FULFILLMENT_AGENCY_IMPORT_AND_EXPORT_ORDER',
  FULFILLMENT_AGENCY_MANAGE_PRODUCT_REQUESTING = 'FULFILLMENT_AGENCY_MANAGE_PRODUCT_REQUESTING',
  FULFILLMENT_AGENCY_MANAGE_PRODUCT_CATALOG = 'FULFILLMENT_AGENCY_MANAGE_PRODUCT_CATALOG',
  FULFILLMENT_AGENCY_MANAGE_FINANCE_TRANSACTION = 'FULFILLMENT_AGENCY_MANAGE_FINANCE_TRANSACTION',
  FULFILLMENT_AGENCY_MANAGE_FINANCE_ACCOUNTANCY = 'FULFILLMENT_AGENCY_MANAGE_FINANCE_ACCOUNTANCY',
  FULFILLMENT_AGENCY_VIEW_STORE_MANAGEMENT = 'FULFILLMENT_AGENCY_VIEW_STORE_MANAGEMENT',
  FULFILLMENT_AGENCY_APPROVE_STORE_AND_ASSIGN_GATE = 'FULFILLMENT_AGENCY_APPROVE_STORE_AND_ASSIGN_GATE',
  FULFILLMENT_AGENCY_SETTING_PAYMENT = 'FULFILLMENT_AGENCY_SETTING_PAYMENT',
  FULFILLMENT_AGENCY_SETTING_PAYOUT_REQUEST = 'FULFILLMENT_AGENCY_SETTING_PAYOUT_REQUEST',
  FULFILLMENT_AGENCY_SETTING_POLICY = 'FULFILLMENT_AGENCY_SETTING_POLICY',
  FULFILLMENT_AGENCY_SETTING_FEE_AND_HOLD = 'FULFILLMENT_AGENCY_SETTING_FEE_AND_HOLD',
  FULFILLMENT_AGENCY_SETTING_CONNECT_TO_BETTASUP = 'FULFILLMENT_AGENCY_SETTING_CONNECT_TO_BETTASUP',
  FULFILLMENT_AGENCY_SETTING_REFUND_EXEMPTION = 'FULFILLMENT_AGENCY_SETTING_REFUND_EXEMPTION',
  FULFILLMENT_AGENCY_SETTING_DEFAULT_COLLECTION = 'FULFILLMENT_AGENCY_SETTING_DEFAULT_COLLECTION',
  FULFILLMENT_AGENCY_SETTING_ADDITIONAL_COST = 'FULFILLMENT_AGENCY_SETTING_ADDITIONAL_COST',
}
