/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum HistoryTrackingType {
  ORDER_PLACED = 'ORDER_PLACED',
  PAYMENT_AUTHORIZED = 'PAYMENT_AUTHORIZED',
  PAYMENT_CAPTURED = 'PAYMENT_CAPTURED',
  EMAIL_CONFIRM_ORDER = 'EMAIL_CONFIRM_ORDER',
  FULFILLMENT = 'FULFILLMENT',
  EMAIL_SHIPPING_CONFIRM = 'EMAIL_SHIPPING_CONFIRM',
  REFUND_ORDER = 'REFUND_ORDER',
  DISPUTE_ORDER_IN_PROCESSING = 'DISPUTE_ORDER_IN_PROCESSING',
  DISPUTE_ORDER_WIN = 'DISPUTE_ORDER_WIN',
  DISPUTE_ORDER_LOSE = 'DISPUTE_ORDER_LOSE',
  COMMENT = 'COMMENT',
}
