export declare enum RequestSourcingStatus {
    REQUESTING = "REQUESTING",
    ADMIN_PROCESSING = "ADMIN_PROCESSING",
    ADMIN_ACCEPTED = "ADMIN_ACCEPTED",
    ADMIN_REJECTED = "ADMIN_REJECTED",
    SELLER_REJECTED = "SELLER_REJECTED",
    SELLER_ACCEPTED = "SELLER_ACCEPTED"
}
