export declare enum TransactionType {
    ORDER = "ORDER",
    DEBT_PAYMENT = "DEBT_PAYMENT",
    DOMAIN = "DOMAIN",
    PAYOUT = "PAYOUT",
    SUBSCRIPTION = "SUBSCRIPTION",
    WITH_DRAW = "WITH_DRAW",
    TOP_UP = "TOP_UP",
    REQUEST_PAYOUT = "REQUEST_PAYOUT"
}
