name: Build project

on:
  push:
    branches: ["ads"]
  pull_request:
    branches: ["ads"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
          registry-url: "https://npm.pkg.github.com"
      - run: yarn
      - run: yarn build
      - run: |
          cp package.json dist/
          cp yarn.lock dist/
      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: build-ads
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
